<?php $id_item = Genius_Class_Utils::idx($this->services, 'id', 0); ?>

<!-- Content wrapper -->
<div class="wrapper">

    <?php echo Genius_Class_Snippets::breadcrumb($this->translate("Services"), '/admin/services'); ?>

    <!-- Page header -->
    <div class="page-header">
        <div class="page-title">
            <h2><?php echo $this->translate("Services"); ?></h2>
        </div>
    </div>
    <!-- /page header -->

    <div class="line"></div>

    <div class="span12">
        <form method="post" action="" id="pages-form" class="form-horizontal form-to-validate">
            <input type="hidden" value="<?php echo Genius_Class_Utils::idx($this->services, 'id', ''); ?>" id="id" name="Services[id]">

            <div class="mt30"><?php Genius_Class_Snippets::multilingualTabs(); ?></div>	

	    	<div class="row-fluid">
		    	<div class="span9">
			    	<fieldset>

					    <div class="widget row-fluid">
					    	<div class="navbar">
						        <div class="navbar-inner">
						            <h6><?php echo $this->translate("Informations générales"); ?></h6>
						        </div>
						    </div>

						    <div class="well tab-form-content">
						    	<div class="control-group">
						    	    <label class="control-label" for="title"><span class="text-error">*</span> <?php echo $this->translate("Titre"); ?>:</label>
						    	    <div class="controls">
						    	        <?php 
						    	            $attributes = array(
						    	                'classic' => array(
						    	                    'id'            => 'title'
						    	                    ,'autocomplete' => 'off'
						    	                )
						    	                ,'custom' => array(
						    	                    'class'        => 'validate[required] span12 multilingual'
						    	                    ,'module'      => 'Services'
						    	                    ,'name'        => 'title'
						    	                    ,'data'        => $this->services
						    	                )
						    	            );
						    	            Genius_Class_Forms::textMultilingual($attributes); 
						    	        ?>
						    	    </div>
						    	</div>

					        	<div class="control-group">
					        	    <label class="control-label" for="text"> <?php echo $this->translate("Description"); ?>:</label>
					        	    <div class="controls">
					        	        <?php 
					        	            $attributes = array(
					        	                'classic' => array(
					        	                    'autocomplete' => 'off'
					        	                    ,'rows'         => 10
					        	                )
					        	                ,'custom' => array(
													'id'      => 'text'
													,'class'  => 'span12 multilingual ckeditor'
													,'module' => 'Services'
													,'name'   => 'text'
													,'data'   => $this->services
					        	                )
					        	            );
					        	            Genius_Class_Forms::textareaMultilingual($attributes);
					        	            Genius_Class_Ckeditor::initToggleCkeditor('text'); 
					        	        ?>
					        	    </div>
					        	</div>
                                
                                <div class="control-group">
						    	    <label class="control-label" for="link"><span class="text-error">*</span> <?php echo $this->translate("Lien"); ?>:</label>
						    	    <div class="controls">
						    	        <?php 
						    	            $attributes = array(
						    	                'classic' => array(
						    	                    'id'            => 'link'
						    	                    ,'autocomplete' => 'off'
						    	                )
						    	                ,'custom' => array(
						    	                    'class'        => 'validate[required] span12 multilingual'
						    	                    ,'module'      => 'Services'
						    	                    ,'name'        => 'link'
						    	                    ,'data'        => $this->services
						    	                )
						    	            );
						    	            Genius_Class_Forms::textMultilingual($attributes); 
						    	        ?>
						    	    </div>
						    	</div>
                                
                                
				            	
						   	</div>
                            
                            <?php
							if ($this->do == "edit") {
								Genius_Class_Forms::multipleUpload(
										'file-uploader'
										, 'folder=products&id_module=17&id_item=' . Genius_Class_Utils::idx($this->services, 'id', '')
								);
							}
							?>
                            <!-- Default Datatable -->
                        <div class="widget row-fluid">
                            <div class="table-overflow">
                                <table class="table table-striped table-bordered" id="data-table">
                                    <thead>
                                        <tr>
                                            <th width="80">Images</th>
                                            <th width="80">Couverture</th>
                                            <th>Name</th>
                                            <th>Caption</th>
                                            <th>Alt</th>
                                            <th class="acenter" width="10%">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td colspan="6" class="dataTables_empty">Loading data...</td>
                                        </tr>
                                    </tbody>
                                </table>

                                <script type="text/javascript">
                                    $(function () {
                                        $('#data-table').dataTable({
                                            "bJQueryUI": false,
                                            "bAutoWidth": false,
                                            "bProcessing": false,
                                            "bServerSide": true,
                                            "iDisplayLength": 5,
                                            "aLengthMenu": [
                                                [5, 10],
                                                [5, 10]
                                            ],
                                            "sAjaxSource": "/admin/upload/getimages/format/html?folder=products&id_module=17&id_item=<?php echo $id_item; ?>",
                                            "sPaginationType": "full_numbers",
                                            "sDom": '<"datatable-header"Cfril>t<"datatable-footer"p>',
                                            "oLanguage": {
                                                "sSearch": "_INPUT_",
                                                "sLengthMenu": "<span>Show entries:</span> _MENU_",
                                                "oPaginate": {"sFirst": "First", "sLast": "Last", "sNext": ">", "sPrevious": "<"}
                                            },
                                            "aoColumns": [
                                                {"bSortable": false},
                                                {"bSortable": false},
                                                {"bSortable": true},
                                                {"bSortable": true},
                                                {"bSortable": true},
                                                {"bSortable": false},
                                            ],
                                            "fnDrawCallback": function (oSettings) {
                                                $("#data-table_wrapper .styled").uniform();
                                                $('#data-table_wrapper .tip').tooltip();
                                                $("#data-table_wrapper #checkAll").closest('.checker > span').removeClass('checked');
                                                $('#data-table_wrapper .dataTables_filter input').attr("placeholder", "Enter seach terms here...");
                                            }
                                        });

                                        $(".delete").live("click", function (e) {
                                            e.preventDefault();

                                            var id = $(this).attr('id');
                                            bootbox.confirm("Voulez-vous vraiment supprimer cet item?", function (confirmed) {
                                                if (confirmed) {
                                                    $.post("/admin/upload/delete"
                                                            , {
                                                                "id": id
                                                            },
                                                    function (data) {
                                                        table = $('#data-table').dataTable();
                                                        table.fnDraw();
                                                    }
                                                    , 'json'
                                                            );
                                                }
                                            });
                                        });

                                        $(".cover").live("click", function (e) {
                                            var id = $(this).attr('value');
                                            $.post("/admin/upload/changecover"
                                                    , {
                                                        "id": id
                                                        , "id_module": 17
                                                        , "id_item": "<?php echo $id_item; ?>"
                                                    },
                                            function (data) {
                                                table = $('#data-table').dataTable();
                                                table.fnDraw();
                                            }
                                            , 'json'
                                                    );
                                        });
                                    });
                                </script>
                            </div>
                        </div>
                        <!-- /Default Datatable -->
					   	</div>
                        
                        <?php Genius_Class_Forms::boxSeo('Services', $this->services); ?>

					</fieldset>
			    </div>

			    
			</div>

            <div class="line mt30"></div>

            <div class="form-actions align-left nobordertop form-actions-bg">
                <button class="btn btn-primary" type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                <button type="button" class="btn btn-danger ml5" onclick="window.location.href='/admin/services'"><?php echo $this->translate("Retour"); ?></button>
            </div>

            <div class="line mb30"></div>
        </form>
    </div>

</div>
<!-- /content wrapper -->