<?php $id_item = Genius_Class_Utils::idx($this->seo, 'id', 0); ?>
<!-- Content wrapper -->
<div class="wrapper">
    <?php echo Genius_Class_Snippets::breadcrumb($this->translate("Seo"), '/admin/seo'); ?>
    <!-- Page header -->
    <div class="page-header">
        <div class="page-title">
            <h2><?php echo $this->translate("Seo"); ?></h2>
        </div>
    </div>
    <!-- /page header -->
    <div class="line"></div>
    <div class="span12">
        <form method="post" action="" id="pages-form" class="form-horizontal form-to-validate">
            <input type="hidden" value="<?php echo Genius_Class_Utils::idx($this->seo, 'id', ''); ?>" id="id" name="Seo[id]">
            <div class="mt30"><?php Genius_Class_Snippets::multilingualTabs(); ?></div>	
	    	<div class="row-fluid">
		    	<div class="span12">
			    	<fieldset>
					    <div class="widget row-fluid">
					    	<div class="navbar">
						        <div class="navbar-inner">
						            <h6><?php echo $this->translate("Information"); ?></h6>
						        </div>
						    </div>
						    <div class="well tab-form-content">
						    	<div class="control-group">
						    	    <label class="control-label" for="title"><span class="text-error">*</span> <?php echo $this->translate("Nom page"); ?>:</label>
						    	    <div class="controls">
						    	        <?php 
						    	            $attributes = array(
						    	                'classic' => array(
						    	                    'id'            => 'nom_page'
						    	                    ,'autocomplete' => 'off'
						    	                )
						    	                ,'custom' => array(
						    	                    'class'        => 'validate[required] span12 multilingual'
						    	                    ,'module'      => 'Seo'
						    	                    ,'name'        => 'nom_page'
						    	                    ,'data'        => $this->seo
						    	                )
						    	            );
						    	            Genius_Class_Forms::textMultilingual($attributes); 
						    	        ?>
						    	    </div>
						    	</div>
				        	
				            	
						   	</div>
					   	</div>


	   				   	<?php Genius_Class_Forms::seo('Seo', $this->seo); ?>

					</fieldset>
			    </div>
		    
			</div>

            <div class="line mt30"></div>

            <div class="form-actions align-left nobordertop form-actions-bg">
                <button class="btn btn-primary" type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                <button type="button" class="btn btn-danger ml5" onclick="window.location.href='/admin/seo'"><?php echo $this->translate("Retour"); ?></button>
            </div>

            <div class="line mb30"></div>
        </form>
    </div>

</div>
<!-- /content wrapper -->
