<div class="col-lg-3 col-md-3"> 
  <!-- start quick search widget -->
  <h3><?php echo $this->translate("Vente")?></h3>
  <div class="divider"></div>
  <ul class="arrows_list1">
    <li><a href="#"><i class="fa fa-angle-right"></i><?php echo $this->translate("Vous cherchez un produit ?")?>  </a></li>
    <li><a href="#"><i class="fa fa-angle-right"></i><?php echo $this->translate("TPV - Matériel d'encaissement")?> </a></li>
    <li><a href="#"><i class="fa fa-angle-right"></i><?php echo $this->translate("Equipements code-barres")?> </a></li>
    <li><a href="#"><i class="fa fa-angle-right"></i><?php echo $this->translate("TPE - Lecteur de Carte")?> </a></li>
    <li><a href="#"><i class="fa fa-angle-right"></i><?php echo $this->translate("Neuf ou reconditionné ?")?> </a></li>
  </ul>
  <!-- end quick search widget --> 
  <!-- start recent posts widget -->
  <h3><?php echo $this->translate("Vidéothèque")?></h3>
  <div class="divider"></div>
  <div class="video_tech"> <a href="/videotheque" title="video tech"><img src="<?php echo THEMES_DEFAULT_URL; ?>images/video_tech.png" alt="" /></a> </div>
  <!-- end recent posts widget --> 
</div>
