<section class="subHeader home bxslider">
    <div id="slide1">
        <div class="container">
            <div class="col-lg-6">
                <h1><span>580</span> Main St</h1>
                <div class="sliderTextBox">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam 
                eu nisl et lectus tempor pretium pellentesque rhoncus nisl. Sed 
                cursus ante eget orci lorem ipsum sodales.</p>
                <a class="buttonGrey large" href="#"><span class="icon-button-arrow"></span><span class="buttonText">VIEW DETAILS</span></a>
                <span class="or">OR</span>
                <a class="buttonColor" href="#"><span class="icon-button-user"></span><span class="buttonText">CONTACT AGENT</span></a>
                </div>
            </div>
            <div class="col-lg-3 col-lg-offset-3"><h1 class="sliderPrice">$525,000</h1></div>
        </div>
    </div>
    <div id="slide2">
        <div class="container">
            <div class="col-lg-6">
                <h1><span>134</span> Smith Avenue</h1>
                <div class="sliderTextBox">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam 
                eu nisl et lectus tempor pretium pellentesque rhoncus nisl. Sed 
                cursus ante eget orci lorem ipsum sodales.</p>
                <a class="buttonGrey large" href="#"><span class="icon-button-arrow"></span><span class="buttonText">VIEW DETAILS</span></a>
                <span class="or">OR</span>
                <a class="buttonColor" href="#"><span class="icon-button-user"></span><span class="buttonText">CONTACT AGENT</span></a>
                </div>
            </div>
            <div class="col-lg-3 col-lg-offset-3"><h1 class="sliderPrice">$85,000</h1></div>
        </div>
    </div>
    <div id="slide3">
        <div class="container">
            <div class="col-lg-6">
                <h1><span>834</span> Pratt Sreet</h1>
                <div class="sliderTextBox">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam 
                eu nisl et lectus tempor pretium pellentesque rhoncus nisl. Sed 
                cursus ante eget orci lorem ipsum sodales.</p>
                <a class="buttonGrey large" href="#"><span class="icon-button-arrow"></span><span class="buttonText">VIEW DETAILS</span></a>
                <span class="or">OR</span>
                <a class="buttonColor" href="#"><span class="icon-button-user"></span><span class="buttonText">CONTACT AGENT</span></a>
                </div>
            </div>
            <div class="col-lg-3 col-lg-offset-3"><h1 class="sliderPrice">$498,000</h1></div>
        </div>
    </div>
</section>