<!-- start subheader -->
<?php echo $this->render($this->subheader);?>
<!-- end subheader section -->
<!-- start recent properties -->
<section class="properties">
    <div class="container">
    	<ul class="propertyCat_list option-set">
    		<li><a href="#" data-filter="*" class="current triangle">ALL</a></li>
    	</ul>
    	<ul class="propertySort_list">
    		<li style="padding-right:0px;">
    			<form style="margin-top:-10px;">
    			<div class="formBlock select">
                    <select name="property type" id="propertyType" class="formDropdown" style="padding:6px;">
                        <option value="type1">Equipements code-barres</option>
                        <option value="type2 Home">Ecrans et visus</option>
                        <option value="type3">Tiroirs Caisse</option>
                        <option value="type4">Equipements code-barres</option>
                    </select>
                </div>
            	</form>
    		</li>
    		<li><p>Categorie Type:</p></li>
    		<li><div style="width:1px; height:45px; margin-top:-12px; background-color:#eee;"></div></li>
    	</ul>
        <div class="divider"></div>
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="propertyItem">
                    <div class="propertyContent">
                        <a class="propertyType" href="#">MONEYLINE</a>
                        <a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/produit1.jpg" alt="" /></a>
                        <h4><a href="property_single.html">I3070</a></h4>
                        <p>Quantité : <strong>524</strong></p>
                        <div class="divider thin"></div>
                        <p class="forSale"><a href="#"><i class="fa fa-plus-square-o"></i>Plus d'infos</a></p>
                        <p class="price">$687,000</p>
                    </div>
                   <div class="spacer"></div>  
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="propertyItem">
                    <div class="propertyContent">
                        <a class="propertyType" href="#">INGENICO</a>
                        <a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/produit2.jpg" alt="" /></a>
                        <h4><a href="property_single.html">L3000ES</a></h4>
                        <p>Quantité : <strong>23</strong></p>
                        <div class="divider thin"></div>
                        <p class="forSale"><a href="#"><i class="fa fa-plus-square-o"></i>Plus d'infos</a></p>
                        <p class="price">$1,200/mo</p>
                    </div>
                    <div class="spacer"></div> 
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="propertyItem">
                    <div class="propertyContent">
                        <a class="propertyType" href="#">MOTOROLA</a>
                        <a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/produit3.jpg" alt="" /></a>
                        <h4><a href="property_single.html">MC3190 - MC3100 series</a></h4>
                        <p>Quantité : <strong>120</strong></p>
                        <div class="divider thin"></div>
                        <p class="forSale"><a href="#"><i class="fa fa-plus-square-o"></i>Plus d'infos</a></p>
                        <p class="price">$687,000</p>
                    </div>
                    <div class="spacer"></div> 
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="propertyItem">
                    <div class="propertyContent">
                        <a class="propertyType" href="#">ZEBRA</a>
                        <a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/produit4.jpg" alt="" /></a>
                        <h4><a href="property_single.html">QL220</a></h4>
                        <p>Quantité : <strong>120</strong></p>
                        <div class="divider thin"></div>
                        <p class="forSale"><a href="#"><i class="fa fa-plus-square-o"></i>Plus d'infos</a></p>
                        <p class="price">$687,000</p>
                    </div>
                     <div class="spacer"></div>
                </div>
            </div>
           <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="propertyItem">
                    <div class="propertyContent">
                        <a class="propertyType" href="#">MONEYLINE</a>
                        <a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/produit1.jpg" alt="" /></a>
                        <h4><a href="property_single.html">I3070</a></h4>
                        <p>Quantité : <strong>524</strong></p>
                        <div class="divider thin"></div>
                        <p class="forSale"><a href="#"><i class="fa fa-plus-square-o"></i>Plus d'infos</a></p>
                        <p class="price">$687,000</p>
                    </div>
                   <div class="spacer"></div>  
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="propertyItem">
                    <div class="propertyContent">
                        <a class="propertyType" href="#">INGENICO</a>
                        <a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/produit2.jpg" alt="" /></a>
                        <h4><a href="property_single.html">L3000ES</a></h4>
                        <p>Quantité : <strong>23</strong></p>
                        <div class="divider thin"></div>
                        <p class="forSale"><a href="#"><i class="fa fa-plus-square-o"></i>Plus d'infos</a></p>
                        <p class="price">$1,200/mo</p>
                    </div>
                    <div class="spacer"></div> 
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="propertyItem">
                    <div class="propertyContent">
                        <a class="propertyType" href="#">MOTOROLA</a>
                        <a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/produit3.jpg" alt="" /></a>
                        <h4><a href="property_single.html">MC3190 - MC3100 series</a></h4>
                        <p>Quantité : <strong>120</strong></p>
                        <div class="divider thin"></div>
                        <p class="forSale"><a href="#"><i class="fa fa-plus-square-o"></i>Plus d'infos</a></p>
                        <p class="price">$687,000</p>
                    </div>
                    <div class="spacer"></div> 
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="propertyItem">
                    <div class="propertyContent">
                        <a class="propertyType" href="#">ZEBRA</a>
                        <a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/produit4.jpg" alt="" /></a>
                        <h4><a href="property_single.html">QL220</a></h4>
                        <p>Quantité : <strong>120</strong></p>
                        <div class="divider thin"></div>
                        <p class="forSale"><a href="#"><i class="fa fa-plus-square-o"></i>Plus d'infos</a></p>
                        <p class="price">$687,000</p>
                    </div>
                     <div class="spacer"></div>
                </div>
            </div>
        </div><!-- end row -->
        <ul class="pageList">
            <li><a href="#">&lt;</a></li>
            <li><a href="#" class="current">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">&gt;</a></li>
        </ul>
    </div><!-- end container -->
</section>
<!-- end recent properties -->
<!-- start widgets section -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div>&nbsp;</div>
    </div>
  </div>
  <div class="clients">
    <div class="container">
      <ul id="mycarouselthree" class="jcarousel-skin-tango">
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo1.png" alt="" /></li>
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo2.png" alt="" /></li>
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo3.png" alt="" /></li>
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo4.png" alt="" /></li>
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo5.png" alt="" /></li>
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo6.png" alt="" /></li>
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo7.png" alt="" /></li>
      </ul>
    </div>
  </div>
</section>
