<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Nouveau message - Formulaire de contact</title>
</head>

<body>
	<table width="100%" cellpadding="0" cellspacing="0">
		<tr>
			<td>
				<table cellpadding="20" cellspacing="0" width="600" align="center">
					Nom: <?php echo $this->name; ?><br />
					Email: <?php echo $this->email; ?><br />
					Objet: <?php echo $this->object; ?><br />
					Message: <?php echo $this->message; ?><br />
				</table><!-- top message -->
			</td>
		</tr>
	</table><!-- wrapper -->
</body>
</html>