<div class="row wrapper-brand">

    <a href="" class="brand-item col-lg-3  col-md-6 col-sm-6  ">
        <img src="<?php echo PROJECTS.'/upload/images/geo/brand/motorola.png' ?>" alt="">
    </a>

    <a href="" class="brand-item col-lg-3  col-md-6 col-sm-6  ">
        <img src="<?php echo PROJECTS.'/upload/images/geo/brand/zebra.png' ?>" alt="">
    </a>

    <a href="" class="brand-item col-lg-3  col-md-6 col-sm-6  ">
        <img src="<?php echo PROJECTS.'/upload/images/geo/brand/intermec.png' ?>" alt="">
    </a>

    <a href="" class="brand-item col-lg-3  col-md-6 col-sm-6">
        <img src="<?php echo PROJECTS.'/upload/images/geo/brand/honeywell.png' ?>" alt="">
    </a>

</div>