<div class="wrapper-content-index">
    <h1>DECOUVRIR EUROCOMPUTER</h1>
    <h3>En video</h3>

    <p>
        <b>V</b>ente de matériels de traçabilité reconditionnés (lecteur, scanner code barre, imprimante Zebra, etc.) et réparation.
        <br>
        <br>
        Depuis 25 ans, Eurocomputer propose son savoir-faire en matière d’optimisation des coûts informatiques.
        Consultez nos offres de déstockage en traçabilité :
        <a href="">Imprimantes étiquettes</a> &
        <a href="">Lecteurs Code-barres</a>
    </p>

    <p>
        <b>T</b>outes les plus grandes marques sont en stock : Zebra Motorola Symbol – Datalogic – Psion Teklogix – Intermec
        Profitez de nos promotions sur les périphériques de bureau : PC – écrans – portables – platines clients-légers - imprimantes laser – imprimantes matricielles
    </p>
    <p>
        marques HP – Lenovo – Dell Wyse – Lexmark – Epson – Oki
        Vous recherchez d’anciennes références, du matériel informatique reconditionné ou en déstockage,
        des accessoires & pièces détachées : contactez-nous, une réponse vous sera apportée dans les 24 heures.
    </p>
</div>
