<div class='card-wrapper'>
    <a href="/reparation" class="" title="">
        <div class='card-euro'>
            <div class='card-content'
                 style='background-image:url(<?php echo PROJECTS.'/upload/images/geo/zt600.jpg' ?>)'>
                <h3 class="imgtitlebox"><i class="fa fa-crop"> </i>
                    &nbsp;Dimensionner votre materiel
                </h3>
                <h4>Laisser vous guider par notre <b>CONFIGURATEUR</b></h4>
                <div class="card-overlay">&nbsp;</div>
            </div>
        </div>
    </a>
</div>