<?php
$menus = Genius_Model_Menu::getAllMenus();
$seo = new Genius_Class_Seo();
$frontController = Zend_Controller_Front::getInstance();
$controller_name = $frontController->getRequest()->getControllerName();

$page = Genius_Model_Page::getPageByCategoryAndIdOptimize(1);
$images_home = Genius_Model_Image::getHomeImageCoverById(18, 1);
$menus_ = Genius_Class_Seo::getMetasMenu(1);
?>

<section class="margin-top-clean ">
    <div class="col-lg-3 " style="padding-top:5px ">

        <div class="row">
            <div class="col-lg-12">
                <?php echo $this->render($this->filter); ?>
            </div>
        </div>

        <br><br>
        <br><br>

        <div class="row">
            <div class="col-lg-12">
                <div class='card-wrapper'>
                    <a href="/reparation" class="" title="Services Codeo">
                        <div class='card-euro' >
                            <div class='card-content'  style='background-image:url(http://sky.walker/upload/images/geo/zt600.jpg)'>
                                <h3 class="imgtitlebox"><i class="fa fa-gear"> </i>&nbsp;&nbsp;Services Eurocomputer</h3>
                                <div class="card-overlay">&nbsp;</div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-9 ">

        <?php echo $this->render($this->slider); ?>

        <!--            <section >-->
        <!--                <div class="col-md-12  infotel">-->
        <!--                    --><?php //echo $this->render($this->infotel); ?>
        <!--                </div>-->
        <!--            </section>-->

        <section class="">
            <div class="col-md-12 ">
                <div class="row">
                    <div class="col-lg-7" style="padding-top: 10px">
                        <br><br>
                        <h4 class="caps"><?php echo $page['title']; ?></h4>
                        <h1 id="h1_home"><?php echo $menus_['h1_noscript'] ?></h1>

<!--                        <div class="row">-->
<!--                           <div class="col-lg-12">-->
<!--                               <p>-->
<!--                                   Depuis 25 ans, Eurocomputer propose son savoir-faire en matière d’optimisation des coûts informatiques.-->
<!--                               </p>-->
<!---->
<!--                               <p>-->
<!--                                   Consultez nos offres de déstockage en traçabilité : <b>imprimantes étiquettes & lecteurs code-barres</b>-->
<!--                               </p>-->
<!--                           </div>-->
<!--                        </div>-->
<!--                        <br>-->
<!--                        <div class="row" >-->
<!--                            <div class="col-lg-6">-->
<!--                                <p>-->
<!--                                    Toutes les plus grandes marques sont en stock-->
<!--                                </p>-->
<!---->
<!--                                <ul>-->
<!--                                    <li  style="list-style: square inside;">Zebra Motorola Symbol</li>-->
<!--                                    <li  style="list-style: square inside;">Datalogic</li>-->
<!--                                    <li  style="list-style: square inside;">Psion Teklogix</li>-->
<!--                                    <li  style="list-style: square inside;">Intermec</li>-->
<!--                                </ul>-->
<!--                            </div>-->
<!---->
<!--                            <div class="col-lg-6">-->
<!--                                <p>-->
<!--                                    Profitez de nos promotions sur les périphériques de bureau <br>-->
<!--                                    PC – écrans – portables – platines clients-légers - imprimantes laser – imprimantes matricielles <br>-->
<!--                                    marques HP – Lenovo – Dell Wyse – Lexmark – Epson – Oki-->
<!--                                </p>-->
<!---->
<!--                            </div>-->
<!--                        </div>-->
<!---->




                        <p style="">
                            <?php echo $page['text']; ?>
                        </p>

                    </div>

                    <div class="col-lg-5 ">
                        <div class="video-container">
                            <iframe width="854" height="480" src="https://www.youtube.com/embed/XOZYtCMt80k"
                                    frameborder="0" allowfullscreen >
                            </iframe>
                        </div>
                    </div>
                </div>


            </div>
        </section>

    </div>
</section>

<style>
    .texte_video ul li {
        list-style: inherit !important
    }

    .btn_video {
        display: inline-block;
        margin-top: 20px !important;
        font-size: 16px;
    }

    #h1_home {
        font-weight: bold;
        line-height: 160%;
        margin-bottom: 15px;
        font-family: 'Open Sans', sans-serif, Arial;
        text-align: left;
        font-size: 15px;
        color: #464646;
    }
</style>


