<!-- Content wrapper -->
<div class="wrapper">

    <?php echo Genius_Class_Snippets::breadcrumb($this->translate("Groupes"), '/admin/groups'); ?>

    <!-- Page header -->
    <div class="page-header">
    	<div class="page-title">
	    	<h2><?php echo $this->translate("Groupes"); ?></h2>
    	</div>
    </div>
    <!-- /page header -->

    <div class="actions-wrapper">
    	<div class="list-buttons align-left nobordertop">
            <button type="button" class="btn btn-primary" onclick="window.location.href='/admin/groups/modify/do/add'"><b class="icon-plus"></b> <?php echo $this->translate("Ajouter"); ?></button>
            <button type="button" class="btn btn-danger ml5 massdelete"><b class="icon-remove"></b> <?php echo $this->translate("Supprimer"); ?></button>
        </div>
   	</div>

    <div class="span12">
	    <!-- Default datatable -->
	    <div class="widget">
	        <div class="table-overflow">
	            <table class="table table-striped table-bordered" id="data-table">
	                <thead>
	                    <tr>
	                        <th width="2%"><input type="checkbox" id="checkAll" name="checkAll" /></th>
	                        <th>Title</th>
	                        <th width="15%">Update time</th>
	                        <th class="acenter" width="10%">Actions</th>
	                    </tr>
	                </thead>
	                <tbody>
	                	<tr>
							<td colspan="4" class="dataTables_empty">Loading data...</td>
						</tr>
	                </tbody>
	            </table>

	            <script type="text/javascript">
		            $(function(){ 
		            	$('#data-table').dataTable({
		            		"bJQueryUI"  : false,
		            		"bAutoWidth" : false,
		            		"bProcessing": false,
		            		"bServerSide": true,
		            		"sAjaxSource": "/admin/groups/getgroups/format/html",
		            		"sPaginationType": "full_numbers",
		            		"sDom": '<"datatable-header"Cfril>t<"datatable-footer"p>',
		            		"oLanguage": {
		            			"sSearch": "_INPUT_",
		            			"sLengthMenu": "<span>Show entries:</span> _MENU_",
		            			"oPaginate": { "sFirst": "First", "sLast": "Last", "sNext": ">", "sPrevious": "<" }
		            		},
		            		"aoColumns": [
		            			{ "bSortable": false },
		            			{ "bSortable": true },
		            			{ "bSortable": true },
		            			{ "bSortable": false },
		            		],
		            		"fnDrawCallback": function (oSettings) {
		            		    $(".styled").uniform();
		            		    $('.tip').tooltip();
		            		    $("#checkAll").closest('.checker > span').removeClass('checked');
		            		    $('.dataTables_filter input').attr("placeholder", "Enter seach terms here...");
		            		}
		                });		 	 
		            });
	            </script>
	        </div>
	    </div>
	    <!-- /default datatable -->
	</div>
</div>
<!-- /content wrapper -->