<?php $id_item = Genius_Class_Utils::idx($this->product, 'id', 0); ?>

<!-- Content wrapper -->
<div class="wrapper">

    <?php echo Genius_Class_Snippets::breadcrumb($this->translate("Produits"), '/admin/products'); ?>

    <!-- Page header -->
    <div class="page-header">
        <div class="page-title">
            <h2><?php echo $this->translate("Produits"); ?></h2>
        </div>
    </div>
    <!-- /page header -->
    <div class="line"></div>
    <div class="span12">
        <form method="post" action="" id="pages-form" class="form-horizontal form-to-validate" enctype="multipart/form-data">
            <input type="hidden" value="<?php echo Genius_Class_Utils::idx($this->product, 'id', ''); ?>" id="id" name="Products[id]">

            <div class="mt30"><?php Genius_Class_Snippets::multilingualTabs(); ?></div>	

            <div class="row-fluid">
                <div class="span9">
                    <fieldset>
                        <div class="widget row-fluid">
                            <div class="navbar">
                                <div class="navbar-inner">
                                    <h6><?php echo $this->translate("Informations générales"); ?></h6>
                                </div>
                            </div>

                            <div class="well tab-form-content">
                                <div class="control-group">
                                    <label class="control-label" for="title"><span class="text-error">*</span> <?php echo $this->translate("Titre"); ?>:</label>
                                    <div class="controls">
                                        <?php
                                        $attributes = array(
                                            'classic' => array(
                                                'id' => 'title'
                                                , 'autocomplete' => 'off'
                                            )
                                            , 'custom' => array(
                                                'class' => 'validate[required] span12 multilingual'
                                                , 'module' => 'Products'
                                                , 'name' => 'title'
                                                , 'data' => $this->product
                                            )
                                        );
                                        Genius_Class_Forms::textMultilingual($attributes);
                                        ?>
                                    </div>
                                </div>	
                                <div class="control-group">
                                    <label class="control-label" for="order_item"> Order:</label>
                                    <div class="controls">
                                        <select class="styled" id="order_item" name="Products[order_item]" style="opacity: 0;">
                                            <?php
                                            if ($this->do == "edit"):
                                                $products = Genius_Model_Product::getProducts();
                                            else:
                                                $products = array();
                                            endif;

                                            $options = array(
                                                'atfirst' => array(
                                                    'value' => 1
                                                    , 'title' => "At first"
                                                )
                                                , 'atend' => array(
                                                    'title' => "At end"
                                                )
                                                , 'optgrouplabel' => "After"
                                                , 'options' => $products
                                                , 'tablename' => TABLE_PREFIX . 'products'
                                                , 'id' => ''
                                            );

                                            Genius_Class_Forms::optionsOrderItemProduct($options);
                                            ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="text"> <?php echo $this->translate("Description"); ?>:</label>
                                    <div class="controls">
                                        <?php
                                        $attributes = array(
                                            'classic' => array(
                                                'autocomplete' => 'off'
                                                , 'rows' => 10
                                            )
                                            , 'custom' => array(
                                                'id' => 'text'
                                                , 'class' => 'span12 multilingual ckeditor'
                                                , 'module' => 'Products'
                                                , 'name' => 'text'
                                                , 'data' => $this->product
                                            )
                                        );
                                        Genius_Class_Forms::textareaMultilingual($attributes);
                                        Genius_Class_Ckeditor::initToggleCkeditor('text');
                                        ?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="text_seo"> <?php echo $this->translate("Bloc texte produit"); ?>:</label>
                                    <div class="controls">
                                        <?php
                                        $attributes = array(
                                            'classic' => array(
                                                'autocomplete' => 'off'
                                                , 'rows' => 10
                                            )
                                            , 'custom' => array(
                                                'id' => 'text_seo'
                                                , 'class' => 'span12 multilingual ckeditor'
                                                , 'module' => 'Products'
                                                , 'name' => 'text_seo'
                                                , 'data' => $this->product
                                            )
                                        );
                                        Genius_Class_Forms::textareaMultilingual($attributes);
                                        Genius_Class_Ckeditor::initToggleCkeditor('text_seo');
                                        ?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="references"> <?php echo $this->translate("Références"); ?>:</label>
                                    <div class="controls">
                                        <?php
                                        $attributes = array(
                                            'classic' => array(
                                                'autocomplete' => 'off'
                                                , 'rows' => 10
                                            )
                                            , 'custom' => array(
                                                'id' => 'references'
                                                , 'class' => 'span12 multilingual ckeditor'
                                                , 'module' => 'Products'
                                                , 'name' => 'references'
                                                , 'data' => $this->product
                                            )
                                        );
                                        Genius_Class_Forms::textareaMultilingual($attributes);
                                        Genius_Class_Ckeditor::initToggleCkeditor('references');
                                        ?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="promotion"><?php echo $this->translate("Promotion"); ?>:</label>
                                    <div class="controls">
                                        <input type='checkbox' name="promotion" id="promotion" value="1" <?php if ($this->product['promotion'] == 1) echo "checked='cheked'"; ?> class="span12 multilingual">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="title"><?php echo $this->translate("Prix"); ?>:</label>
                                    <div class="controls">
                                        <input type='text' name="prix" id="prix" value="<?php echo (!empty($this->product['prix_' . DEFAULT_LANG_ABBR])) ? $this->product['prix_' . DEFAULT_LANG_ABBR] : ''; ?>" class="span12 multilingual">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="title"><?php echo $this->translate("Quantité"); ?>:</label>
                                    <div class="controls">
                                        <input type='text' name="quantite" id="quantite" value="<?php echo (!empty($this->product['quantite_' . DEFAULT_LANG_ABBR])) ? $this->product['quantite_' . DEFAULT_LANG_ABBR] : ''; ?>" class="span12 multilingual">
                                    </div>
                                </div> 
                                <div class="control-group">
                                    <label class="control-label" for="accessoires_produits_associes"><?php echo $this->translate("Accessoires et produits associés"); ?>:</label>
                                    <div class="controls">
                                        <input type='text' name="accessoires_produits_associes" id="accessoires_produits_associes" placeholder="identifiants des produits séparés par des points virgules" value="<?php echo (!empty($this->product['accessoires_produits_associes_' . DEFAULT_LANG_ABBR])) ? $this->product['accessoires_produits_associes_' . DEFAULT_LANG_ABBR] : ''; ?>" class="span12 multilingual">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="produits_similaires"><?php echo $this->translate("Produits similaires"); ?>:</label>
                                    <div class="controls">
                                        <input type='text' name="produits_similaires" id="produits_similaires" placeholder="identifiants des produits séparés par des points virgules" value="<?php echo (!empty($this->product['produits_similaires_' . DEFAULT_LANG_ABBR])) ? $this->product['produits_similaires_' . DEFAULT_LANG_ABBR] : ''; ?>" class="span12 multilingual">
                                    </div>
                                </div> 
                                <div class="control-group">
                                    <label class="control-label" for="title"><?php echo $this->translate("Fiche technique"); ?>:</label>
                                    <div class="controls">
                                        <input type="file" class="styled" name="pdf[]" value="" multiple="">
                                        <i>Le format pdf est accepté</i>
                                        <?php
                                        if ($this->do == "edit"):
                                            if (!empty($this->product['fiche_technique_' . DEFAULT_LANG_ABBR])):
                                                $tab = explode(',', $this->product['fiche_technique_' . DEFAULT_LANG_ABBR]);
                                                echo "<br>";
                                                foreach ($tab as $key => $file) {
                                                    $source = UPLOAD_URL . 'fiche_technique/' . $file;
                                                    $pdf = UPLOAD_PATH . 'fiche_technique/' . $file;
                                                    if (file_exists($pdf)) {
                                                        echo $file . '&nbsp;|&nbsp;<a href=' . $source . ' target="_blank">Télécharger le fichier</a><br>';
                                                    }
                                                }
                                                if(count($tab)>1):
                                                    echo "<a style='cursor:pointer'onclick='deletepdf($id_item)'>[ Supprimer tous les fichiers ]</a>";
                                                else:
                                                    echo "<a style='cursor:pointer'onclick='deletepdf($id_item)'>[ Supprimer le fichier ]</a>";
                                                endif;
                                            endif;
                                        endif;
                                        ?>
                                    </div>
                                </div>                                 
                            </div>
                        </div>
                        <?php
                        if ($this->do == "edit") {
                            $category_group = Genius_Model_Product::getGroup($this->product['id']);
                            $product_category = Genius_Model_Product::getProductCategoryById($this->product['id']);
                            $id_type = $product_category['id_category_box'][14];
                            $id_marque = $product_category['id_category_box'][13];
                            $id_category = $category_group[0];
                            $id_category_group = $category_group[1];
                            if (($id_category_group == 27 && ( $id_type == 87 || $id_type == 85 || $id_type == 86 || $id_type == 89 || $id_type == 121 || $id_type == 123 ) ) || $id_category_group == 14 || $id_category_group == 17 || $id_category_group == 21 || $id_category_group == 24 || $id_category_group == 32 || $id_category_group == 36) {
                                ?>
                                <div class="widget row-fluid">
                                    <div class="navbar">
                                        <div class="navbar-inner">
                                            <h6><?php echo $this->translate("Specificités en Un clin d'oeil"); ?></h6>
                                        </div>
                                    </div>
                                    <div class="well tab-form-content">
                                        <div class="control-group">
                                            <label class="control-label" for="carac_1"><span class="text-error">*</span> <?php echo Genius_Class_Products::getFeatures($id_category_group, 1, $id_type, $id_marque); ?>:</label>
                                            <div class="controls">
                                                <?php
                                                $attributes = array(
                                                    'classic' => array(
                                                        'id' => 'carac_1'
                                                        , 'autocomplete' => 'off'
                                                    )
                                                    , 'custom' => array(
                                                        'class' => 'span12 multilingual'
                                                        , 'module' => 'Products'
                                                        , 'name' => 'carac_1'
                                                        , 'data' => $this->product
                                                    )
                                                );
                                                Genius_Class_Forms::textMultilingual($attributes);
                                                ?>
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="carac_2"><span class="text-error">*</span> <?php echo Genius_Class_Products::getFeatures($id_category_group, 2, $id_type, $id_marque); ?>:</label>
                                            <div class="controls">
                                                <?php
                                                $attributes = array(
                                                    'classic' => array(
                                                        'id' => 'carac_2'
                                                        , 'autocomplete' => 'off'
                                                    )
                                                    , 'custom' => array(
                                                        'class' => 'span12 multilingual'
                                                        , 'module' => 'Products'
                                                        , 'name' => 'carac_2'
                                                        , 'data' => $this->product
                                                    )
                                                );
                                                Genius_Class_Forms::textMultilingual($attributes);
                                                ?>
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="carac_3"><span class="text-error">*</span> <?php echo Genius_Class_Products::getFeatures($id_category_group, 3, $id_type, $id_marque); ?>:</label>
                                            <div class="controls">
                                                <?php
                                                $attributes = array(
                                                    'classic' => array(
                                                        'id' => 'carac_3'
                                                        , 'autocomplete' => 'off'
                                                    )
                                                    , 'custom' => array(
                                                        'class' => 'span12 multilingual'
                                                        , 'module' => 'Products'
                                                        , 'name' => 'carac_3'
                                                        , 'data' => $this->product
                                                    )
                                                );
                                                Genius_Class_Forms::textMultilingual($attributes);
                                                ?>
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="carac_4"><span class="text-error">*</span> <?php echo Genius_Class_Products::getFeatures($id_category_group, 4, $id_type, $id_marque); ?>:</label>
                                            <div class="controls">
                                                <?php
                                                $attributes = array(
                                                    'classic' => array(
                                                        'id' => 'carac_4'
                                                        , 'autocomplete' => 'off'
                                                    )
                                                    , 'custom' => array(
                                                        'class' => 'span12 multilingual'
                                                        , 'module' => 'Products'
                                                        , 'name' => 'carac_4'
                                                        , 'data' => $this->product
                                                    )
                                                );
                                                Genius_Class_Forms::textMultilingual($attributes);
                                                ?>
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="carac_5"><span class="text-error">*</span> <?php echo Genius_Class_Products::getFeatures($id_category_group, 5, $id_type, $id_marque); ?>:</label>
                                            <div class="controls">
                                                <?php
                                                $attributes = array(
                                                    'classic' => array(
                                                        'id' => 'carac_5'
                                                        , 'autocomplete' => 'off'
                                                    )
                                                    , 'custom' => array(
                                                        'class' => 'span12 multilingual'
                                                        , 'module' => 'Products'
                                                        , 'name' => 'carac_5'
                                                        , 'data' => $this->product
                                                    )
                                                );
                                                Genius_Class_Forms::textMultilingual($attributes);
                                                ?>
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="carac_6"><span class="text-error">*</span> <?php echo Genius_Class_Products::getFeatures($id_category_group, 6, $id_type, $id_marque); ?>:</label>
                                            <div class="controls">
                                                <?php
                                                $attributes = array(
                                                    'classic' => array(
                                                        'id' => 'carac_6'
                                                        , 'autocomplete' => 'off'
                                                    )
                                                    , 'custom' => array(
                                                        'class' => 'span12 multilingual'
                                                        , 'module' => 'Products'
                                                        , 'name' => 'carac_6'
                                                        , 'data' => $this->product
                                                    )
                                                );
                                                Genius_Class_Forms::textMultilingual($attributes);
                                                ?>
                                            </div>
                                        </div>
                                    </div>    
                                </div>   
                                <?php
                            }
                        }
                        ?>
                        <?php
                        if ($this->do == "edit") {
                            Genius_Class_Forms::multipleUpload(
                                    'file-uploader'
                                    , 'folder=products&id_module=7&id_item=' . Genius_Class_Utils::idx($this->product, 'id', '')
                            );
                        }
                        ?>
                        <!-- Default Datatable -->
                        <div class="widget row-fluid">
                            <div class="table-overflow">
                                <table class="table table-striped table-bordered" id="data-table">
                                    <thead>
                                        <tr>
                                            <th width="80">Images</th>
                                            <th width="80">Couverture</th>
                                            <th>Name</th>
                                            <th>Caption</th>
                                            <th>Alt</th>
                                            <th class="acenter" width="10%">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td colspan="6" class="dataTables_empty">Loading data...</td>
                                        </tr>
                                    </tbody>
                                </table>

                                <script type="text/javascript">
                                    $(function () {
                                        $('#data-table').dataTable({
                                            "bJQueryUI": false,
                                            "bAutoWidth": false,
                                            "bProcessing": false,
                                            "bServerSide": true,
                                            "iDisplayLength": 5,
                                            "aLengthMenu": [
                                                [5, 10],
                                                [5, 10]
                                            ],
                                            "sAjaxSource": "/admin/upload/getimages/format/html?folder=products&id_module=7&id_item=<?php echo $id_item; ?>",
                                            "sPaginationType": "full_numbers",
                                            "sDom": '<"datatable-header"Cfril>t<"datatable-footer"p>',
                                            "oLanguage": {
                                                "sSearch": "_INPUT_",
                                                "sLengthMenu": "<span>Show entries:</span> _MENU_",
                                                "oPaginate": {"sFirst": "First", "sLast": "Last", "sNext": ">", "sPrevious": "<"}
                                            },
                                            "aoColumns": [
                                                {"bSortable": false},
                                                {"bSortable": false},
                                                {"bSortable": true},
                                                {"bSortable": true},
                                                {"bSortable": true},
                                                {"bSortable": false},
                                            ],
                                            "fnDrawCallback": function (oSettings) {
                                                $("#data-table_wrapper .styled").uniform();
                                                $('#data-table_wrapper .tip').tooltip();
                                                $("#data-table_wrapper #checkAll").closest('.checker > span').removeClass('checked');
                                                $('#data-table_wrapper .dataTables_filter input').attr("placeholder", "Enter seach terms here...");
                                            }
                                        });

                                        $(".delete").live("click", function (e) {
                                            e.preventDefault();

                                            var id = $(this).attr('id');
                                            bootbox.confirm("Voulez-vous vraiment supprimer cet item?", function (confirmed) {
                                                if (confirmed) {
                                                    $.post("/admin/upload/delete"
                                                            , {
                                                                "id": id
                                                            },
                                                    function (data) {
                                                        table = $('#data-table').dataTable();
                                                        table.fnDraw();
                                                    }
                                                    , 'json'
                                                            );
                                                }
                                            });
                                        });

                                        $(".cover").live("click", function (e) {
                                            var id = $(this).attr('value');
                                            $.post("/admin/upload/changecover"
                                                    , {
                                                        "id": id
                                                        , "id_module": 4
                                                        , "id_item": "<?php echo $id_item; ?>"
                                                    },
                                            function (data) {
                                                table = $('#data-table').dataTable();
                                                table.fnDraw();
                                            }
                                            , 'json'
                                                    );
                                        });
                                    });
                                </script>
                            </div>
                        </div>
                        <!-- /Default Datatable -->
                        <?php Genius_Class_Forms::boxSeo('Products', $this->product); ?>
                    </fieldset>
                </div>
                <div class="span3">
                    <?php //Genius_Class_Forms::boxCategory(7, 'Products', $this->product, 'products_categories', 'id_product');  ?>
                    <!-- debut rubrique -->
                    <div class="widget row-fluid">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6>Rubriques</h6>
                            </div>
                        </div>

                        <div class="well">
                            <div class="control-group">
                                <div>
                                    <label class="checkbox" style="cursor: pointer">
                                        <select name="rubriques" id="rubriques" onchange="getRubrique()">
                                            <option value="">Selectionnez une rubrique</option>
                                            <?php
                                            foreach ($this->modules as $item):
                                                if ($this->id_module_rubrique == $item['id']) {
                                                    $chk_rubrique = "selected='selected'";
                                                } else {
                                                    $chk_rubrique = "";
                                                }
                                                ?>
                                                <option <?php echo $chk_rubrique ?> value="<?php echo $item['id'] ?>"><?php echo $item['title'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- fin rubrique -->
                    <!-- debut groupes -->
                    <div class="widget row-fluid">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6>Groupes</h6>
                            </div>
                        </div>

                        <div class="well">
                            <div class="control-group">
                                <div>
                                    <label class="checkbox" style="cursor: pointer">
                                        <select name='groupes' id='groupes' onchange='getGroupes()'>                                            
                                            <option>Selectionnez le groupe</option>
                                            <?php
                                            foreach ($this->group_list as $key => $group_list):
                                                if ($this->id_category_group_parent == $key) {
                                                    $chk_group = "selected='selected'";
                                                } else {
                                                    $chk_group = "";
                                                }
                                                echo "<option $chk_group value=$key>$group_list</option>";
                                            endforeach;
                                            ?>
                                        </select>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- fin groupes -->
                    <!-- debut marques -->
                    <div class="widget row-fluid">
                        <div class="navbar">
                            <div class="navbar-inner" id="title-marques">
                                <h6>Marques</h6>
                            </div>
                        </div>

                        <div class="well">
                            <div class="control-group">
                                <div id="marques">
                                    <?php
                                    $return_marque = "";
                                    if (!empty($this->categories[13]['categories_list'])):
                                        foreach ($this->categories[13]['categories_list'] as $item) {
                                            if ($this->id_category_box[13] == $item['id_category']) {
                                                $chk_marque = "checked='checked'";
                                            } else {
                                                $chk_marque = "";
                                            }
                                            $return_marque .= '<label class="radio" style="cursor: pointer">';
                                            $return_marque .= '<input ' . $chk_marque . ' type="radio" name="Products[categories_marque]" id="categories_' . $item['id_category'] . '" value="' . $item['id_category'] . '" class="styled">';
                                            $return_marque .= $item['title'];
                                            $return_marque .= '</label>';
                                        }
                                        echo $return_marque;
                                    endif;
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- fin marques -->
                    <!-- debut types -->
                    <div class="widget row-fluid">
                        <div class="navbar">
                            <div class="navbar-inner" id="title-types">
                                <h6>Types</h6>
                            </div>
                        </div>

                        <div class="well">
                            <div class="control-group">
                                <div id="types">
                                    <?php
                                    if (!empty($this->categories[14]['categories_list'])):
                                        $return_type = "";
                                        foreach ($this->categories[14]['categories_list'] as $item) {

                                            if ($this->id_category_box[14] == $item['id_category']) {
                                                $chk_type = "checked='checked'";
                                            } else {
                                                $chk_type = "";
                                            }
                                            $return_type .= '<label class="radio" style="cursor: pointer">';
                                            $return_type .= '<input ' . $chk_type . ' type="radio" name="Products[categories_type]" id="categories_' . $item['id_category'] . '" value="' . $item['id_category'] . '" class="styled">';
                                            $return_type .= $item['title'];
                                            $return_type .= '</label>';
                                        }
                                        echo $return_type;
                                    endif;
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- fin types -->

                    <!-- debut types -->
                    <div class="widget row-fluid">
                        <div class="navbar">
                            <div class="navbar-inner" id="title-types">
                                <h6>Services associés</h6>
                            </div>
                        </div>

                        <div class="well">
                            <div class="control-group">
                                <div id="types">
                                    <?php
                                    $services = $this->services;
                                    $products_services = $this->products_services;
                                    $return_type = "";
                                    foreach ($services as $item) {
                                        if (in_array($item['id_service'], $products_services)) {
                                            $chk_type = "checked='checked'";
                                        } else {
                                            $chk_type = "";
                                        }
                                        $return_type .= '<label class="radio" style="cursor: pointer">';
                                        $return_type .= '<input ' . $chk_type . ' type="checkbox" name="Products[services][]" id="services_' . $item['id_service'] . '" value="' . $item['id_service'] . '" class="styled">';
                                        $return_type .= $item['title'];
                                        $return_type .= '</label>';
                                    }
                                    echo $return_type;
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- fin types -->

                </div>
            </div>

            <div class="line mt30"></div>

            <div class="form-actions align-left nobordertop form-actions-bg">
                <button class="btn btn-primary" type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                <button type="button" class="btn btn-danger ml5" onclick="window.location.href = '/admin/products'"><?php echo $this->translate("Retour"); ?></button>
            </div>

            <div class="line mb30"></div>
        </form>
    </div>

</div>
<!-- /content wrapper -->
