<?php $id_item = Genius_Class_Utils::idx($this->products_seo, 'id', 0); ?>
<!-- Content wrapper -->
<div class="wrapper">

    <?php echo Genius_Class_Snippets::breadcrumb($this->translate("Règles SEO Produits"), '/admin/products/seo'); ?>

    <!-- Page header -->
    <div class="page-header">
        <div class="page-title">
            <h2><?php echo $this->translate("Règles SEO Produits"); ?></h2>
        </div>
    </div>
    <!-- /page header -->
    <div class="line"></div>
    <div class="span12">
        <form method="post" action="" id="pages-form" class="form-horizontal form-to-validate" enctype="multipart/form-data">
            <input type="hidden" value="<?php echo Genius_Class_Utils::idx($this->products_seo, 'id', ''); ?>" id="id" name="Products[id]">

            <div class="mt30"><?php Genius_Class_Snippets::multilingualTabs(); ?></div>	

            <div class="row-fluid">
                <div class="span9">
                    <fieldset>
                        <?php Genius_Class_Forms::boxSeo('Products', $this->products_seo); ?>
                    </fieldset>
                </div>
            </div>

            <div class="line mt30"></div>

            <div class="form-actions align-left nobordertop form-actions-bg">
                <button class="btn btn-primary" type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                <button type="button" class="btn btn-danger ml5" onclick="window.location.href = '/admin/products'"><?php echo $this->translate("Retour"); ?></button>
            </div>

            <div class="line mb30"></div>
        </form>
    </div>

</div>
<!-- /content wrapper -->