<!-- start main content -->
<section class="properties" style="padding-top: 160px;padding-bottom:40px;">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 col-md-9">
        <div class="row">
          <div class="col-lg-12 col-md-12 col_blogPost">
            <h1>Paris</h1>
            <div class="divider" style="margin-bottom:30px !important"></div>
            <div class="blogPost">
             <h2 class="col-titre-interne">REPARATION</h2>
            <div class="propertyContent row">
            <div class="col-lg-12">
                <a class="col-links" href="#">
                <img src="http://eurocomputer.genius-at-work.com/upload/images/products/lexmark_t650-small-590.jpg" alt="Lexmark T650/T652/T654">
                </a>
                <h4><a href="#">Imprimantes-laser lexmark T656</a></h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu dignissim erat, el placerat risus. Proin luctus tortor sit 
                varius elementum. Duis ut condimentum risus, ac accumsan dui. Donec nibh elit, elementum dapibus massa sit amet, lorem
                lacusfaucibus lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique  
                senectus et netus et malesuada fames ac turpis egestas. Curabitur at est eu ipsum auctor suscipit.</p>
            </div>
            </div>
            </div>
          </div>
        </div>
        <!-- end row --> 
      </div>
      <!-- end col --> 
      
      <!-- START SIDEBAR -->
      <?php echo $this->render('statics/top_recherche.phtml');?>
      <!-- end col --> 
      
    </div>
    <!-- end row --> 
  </div>
  <!-- end container --> 
</section>
<!-- end main content --> 

<!-- start widgets section -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div class="hbigline1">&nbsp;</div>
    </div>
  </div>
  <?php echo $this->render('statics/carousel.phtml');?>
</section>
