<!-- Loader -->
<div id="loading">
	<img src="<?php echo THEMES_COMINGSOON_URL; ?>images/loader.gif" alt="Coming soon - Genius At Work Website Loader"/>
</div>
<!-- /Loader -->

<!-- HEADER -->
<div class="header">

	<!-- LOGO -->
	<div class="logo">
    	<a href="#homepage" title="Coming soon - Genius At Work">
            <img src="<?php echo THEMES_COMINGSOON_URL; ?>images/logo.png" alt="Coming soon - Genius At Work">
        </a>
    </div>
    <!-- /LOGO -->
    
    <!-- NAVIGATION -->
    <ul class="nav-bar hide-for-small">
        <li class="active"><a href="#homepage"><?php echo $this->translate("Accueil"); ?></a></li>
        <li><a href="#about-us"><?php echo $this->translate("A propos de nous / Nos services"); ?></a></li>
        <li><a href="#subscribe"><?php echo $this->translate("S'inscrire"); ?></a></li>
        <li><a href="#contact-us"><?php echo $this->translate("Contactez-nous"); ?></a></li>
    </ul>
    <!-- /NAVIGATION -->
        
    <!-- Mobile Navigation -->
    <select class="responsive-nav show-for-small" onchange="moveTo(this.value)" onFocus="moveTo(this.value)">
    	<option value="" selected=""><?php echo $this->translate("Menu principal"); ?></option>
    	<option value="#homepage"><?php echo $this->translate("Accueil"); ?></option>
        <option value="#about-us"><?php echo $this->translate("A propos de nous / Nos services"); ?></option>
    	<option value="#subscribe"><?php echo $this->translate("S'inscrire"); ?></option>
        <option value="#contact-us"><?php echo $this->translate("Contactez-nous"); ?></option>
	</select>
    <!-- /Mobile Navigation -->
</div>
<!-- /HEADER -->

<!-- Homepage -->
<div class="homepage-container" id="homepage">
	<div class="overlay"></div>
    <div class="homepage-content">
        <h1 class="homepage-title"><?php echo $this->translate("OUR NEW WEBSITE<br /> IS COMING VERY SOON"); ?></h1>
        <div class="divider"></div>
        <div class="countdown-container twelve columns"></div>
	</div>
</div>
<!-- /Homepage -->

<div id="wrapper">
    <div class="about-us" id="about-us">
        <div class="row">
            <div class="twelve columns">
                <h1 class="page-title">ABOUT US / OUR SERVICES</h1>
                <div class="divider"></div>
                <p class="page-content">A small introduction about our company / What services we offer for our clients</p>

                <p class="text_aboutus">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor.
                </p>

                <p class="text_ourservices">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
            </div>
        </div>

        <div class="row">
            <div class="twelve">
                <div class="four columns box_serv">
                    <div class="iconbox">
                        <i class="icon-1"></i><br>
                        <h4 class="name_serv"><b>45+ HTML Pages</b></h4>
                        <p class="text_serv">Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat.</p>
                    </div>
                </div>
                
                <div class="four columns box_serv">
                    <div class="iconbox">
                        <i class="icon-1"></i><br>
                        <h4 class="name_serv"><b>Fully responsive</b></h4>
                        <p class="text_serv">Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat.</p>
                    </div>
                </div>
                
                <div class="four columns box_serv">
                    <div class="iconbox">
                        <i class="icon-1"></i><br>
                        <h4 class="name_serv"><b>Minimal Design</b></h4>
                        <p class="text_serv">Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat.</p>
                    </div>   
                </div>
                
                <div class="four columns box_serv">
                    <div class="iconbox">
                        <i class="icon-1"></i><br>
                        <h4 class="name_serv"><b>Zurb Foundation</b></h4>
                        <p class="text_serv">Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat.</p>
                    </div>     
                </div>

                <div class="four columns box_serv">
                    <div class="iconbox">
                        <i class="icon-1"></i><br>
                        <h4 class="name_serv"><b>Customizations</b></h4>
                        <p class="text_serv">Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat.</p>
                    </div>     
                </div>
                
                <div class="four columns box_serv">
                    <div class="iconbox">
                        <i class="icon-1"></i><br>
                        <h4 class="name_serv"><b>Dedicated Support</b></h4>
                        <p class="text_serv">Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat.</p>
                    </div>     
                </div>

                <div class="four columns box_serv">
                    <div class="iconbox">
                        <i class="icon-1"></i><br>
                        <h4 class="name_serv"><b>iOS/Android</b></h4>
                        <p class="text_serv">Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat.</p>
                    </div>     
                </div>

                <div class="four columns box_serv end">
                    <div class="iconbox">
                        <i class="icon-1"></i><br>
                        <h4 class="name_serv"><b>Web Development</b></h4>
                        <p class="text_serv">Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat.</p>
                    </div>     
                </div>
            </div>
        </div>
    </div>

    <div class="subscribe twitter" id="subscribe">
        <div class="row">
            <div class="twelve columns">
                <h1 class="page-title">SUBSCRIBE TODAY</h1>
            	<div class="divider"></div>
                <p class="page-content">
                    <span class="orange">Sign up</span> for our newsletter to get notified.<br />
                    Enter your email address and we'll notify you when we launch!
                </p>
                <div class="subscription-form">
                    <form method="post" action="#">
                        <div class="subscription-form-email">
                            <input type="text" id="email" class="email" name="email" placeholder="<?php echo $this->translate("Votre courriel"); ?>" />
                        </div>
                        <input type="submit" value="<?php echo $this->translate("Inscrit moi"); ?>" class="submit-button" name="submit" id="submitButton" title="<?php echo $this->translate("Cliquer ici pour s'inscrire"); ?>!" />
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="contact-us" id="contact-us">
        <div class="row">
            <div class="twelve columns">
                <h1 class="page-title">CONTACT US</h1>
            	<div class="divider"></div>
                <p class="page-content">You can send us a message or visit us at our office</p>
            </div>                
        </div>

        <div class="row">
            <div class="six columns">
                <h4><span class="orange"><?php echo $this->translate("Envoyez-nous un message"); ?></span></h4>
                <div id="contact-form" class="contact-form">
                    <form method="post" action="#">
                        <div class="contact-form-name">
                            <input type="text" id="name" class="name" name="name" placeholder="<?php echo $this->translate("Nom"); ?>"/>
                        </div>

                        <div class="contact-form-email">
                            <input type="text" id="email" class="email" name="email" placeholder="<?php echo $this->translate("Courriel"); ?>"/>
                        </div>

                        <div class="contact-form-subject">
                            <input type="text" id="subject" class="subject" name="subject" placeholder="<?php echo $this->translate("Objet"); ?>"/>
                        </div>

                        <div class="contact-form-message">
                            <textarea id="message" name="message" placeholder="<?php echo $this->translate("Message"); ?>" rows="7"></textarea>
                        </div>

                        <input type="submit" value="<?php echo $this->translate("Envoyer le message"); ?>" class="submit-button" name="submit" id="submitButton" title="<?php echo $this->translate("Cliquer ici pour envoyer le message"); ?>!" />
                    </form>
                </div>
            </div>

            <div class="five columns offset-by-one">
                <h4><span class="orange"><?php echo $this->translate("Notre bureau"); ?></span></h4>
                <address>
                    <b>GENIUS AT WORK</b><br />
                    19 Ter H, Ankazolava Ambohitsoa<br />
                    Antananarivo 101, Madagascar<br />
                    <b><u><?php echo $this->translate("Courriel"); ?>:</u></b>&nbsp; contact(at)geniusatwork.mg<br />
                    <b><u><?php echo $this->translate("Téléphone"); ?>:</u></b>&nbsp; +261 34 45 819 21, +261 33 57 789 12<br />
                </address>

                <div id="map" class="map_canvas" 
                    data-lat="-18.937988"
                    data-lng="47.543502"
                    data-address="19 Ter H, Ankazolava Ambohitsoa, Antananarivo, Madagascar" 
                    data-zoom="12" 
                    data-mapTitle="Genius at work"
                    style="height:225px;width:100%;"></div>
            </div>
        </div>
    </div>

    <div class="footer">
        <div class="row">
            <div class="twelve columns">
            	<a href="#homepage" class="to-top"></a>
            </div>
            <div class="twelve columns copyright">
            	<a href="http://dev.geniuscms.mg/">&copy; <?php echo date('Y'); ?> Genius at work. <?php echo $this->translate("Tous droits réservés.") ?> </a>
            </div>
        </div>
    </div>
</div>

<!-- Included JS Files (Compressed) -->
<script src="<?php echo THEMES_COMINGSOON_URL; ?>javascripts/foundation.min.js"></script>
<!-- /Included JS Files (Compressed) -->

<!-- Initialize JS Plugins -->
<script src="<?php echo THEMES_COMINGSOON_URL; ?>javascripts/app.js"></script>
<!-- /Initialize JS Plugins -->

<!-- Countdown -->
<script type="text/javascript" src="<?php echo THEMES_COMINGSOON_URL; ?>javascripts/jquery.countdown.js"></script>
<script type="text/javascript">
	jQuery(function ($) {
		var austDay = new Date();
		austDay = new Date(2013, 8 - 1, 26);
		$('.countdown-container').countdown({until: austDay});
		$('#year').text(austDay.getFullYear());
	});
</script>
<!-- /Countdown -->

<!-- Loader -->
<script type="text/javascript">
	$(window).load(function() {
		$("#loading").fadeOut("1000", function() {
		// Animation complete
			$('#loading img').css("display","none");
			$('#loading').css("display","none");
			$('#loading').css("background","none");
			$('#loading').css("width","0");
			$('#loading').css("height","0");
	  	});
	  	// Homepage Height
		$('.homepage-container').css("height",$(window).height());
		$('.homepage-content').css("top",$(window).height() - $('.homepage-content').height() - "50");
	});
	
	$(document).ready(function(){
		$(window).resize(function() {
			// Homepage Height
			$('.homepage-container').css("height",$(window).height());
			$('.homepage-content').css("top",$(window).height() - $('.homepage-content').height() - "50");
		});
	});
</script>
<!-- /Loader -->
    
<!-- Supersized Background Slideshow -->
<script type="text/javascript" src="<?php echo THEMES_COMINGSOON_URL; ?>javascripts/jquery.easing.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_COMINGSOON_URL; ?>javascripts/supersized.3.2.7.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_COMINGSOON_URL; ?>javascripts/supersized.shutter.min.js"></script>

<script type="text/javascript">
	jQuery(function($){
		$.supersized({
			
			// Functionality
			slideshow               :   1,			// Slideshow on/off
			autoplay				:	1,			// Slideshow starts playing automatically
			start_slide             :   1,			// Start slide (0 is random)
			stop_loop				:	0,			// Pauses slideshow on last slide
			random					: 	0,			// Randomize slide order (Ignores start slide)
			slide_interval          :   4000,		// Length between transitions
			transition              :   1, 			// 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
			transition_speed		:	1500,		// Speed of transition
			new_window				:	1,			// Image links open in new window/tab
			pause_hover             :   0,			// Pause slideshow on hover
			keyboard_nav            :   1,			// Keyboard navigation on/off
			performance				:	1,			// 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
			image_protect			:	1,			// Disables image dragging and right click with Javascript
			
			// Size & Position						   
			min_width		        :   0,			// Min width allowed (in pixels)
			min_height		        :   0,			// Min height allowed (in pixels)
			vertical_center         :   1,			// Vertically center background
			horizontal_center       :   1,			// Horizontally center background
			fit_always				:	0,			// Image will never exceed browser width or height (Ignores min. dimensions)
			fit_portrait         	:   1,			// Portrait images will not exceed browser height
			fit_landscape			:   0,			// Landscape images will not exceed browser width
			
			// Components							
			slide_links				:	'blank',	// Individual links for each slide (Options: false, 'num', 'name', 'blank')
			thumb_links				:	1,			// Individual thumb links for each slide
			thumbnail_navigation    :   0,			// Thumbnail navigation
			slides 					:  	[			// Slideshow Images
				{image : '<?php echo THEMES_COMINGSOON_URL; ?>images/background-slideshow/1.jpg', url : ''},
                {image : '<?php echo THEMES_COMINGSOON_URL; ?>images/backgrounds/4.jpg', url : ''},
                {image : '<?php echo THEMES_COMINGSOON_URL; ?>images/backgrounds-slides/winter-road.jpg', url : ''},
                {image : '<?php echo THEMES_COMINGSOON_URL; ?>images/background-slideshow/3.jpg', url : ''},
                {image : '<?php echo THEMES_COMINGSOON_URL; ?>images/sliderImages/slide1.jpg', url : ''},
                {image : '<?php echo THEMES_COMINGSOON_URL; ?>images/background-slideshow/2.jpg', url : ''},
                {image : '<?php echo THEMES_COMINGSOON_URL; ?>images/backgrounds/5.jpg', url : ''},
                {image : '<?php echo THEMES_COMINGSOON_URL; ?>images/sliderImages/slide2.jpg', url : ''}
			],
			
			// Theme Options			   
			progress_bar			:	1,			// Timer for each slide							
			mouse_scrub				:	0
		});
	});
</script>
<!-- /Supersized Background Slideshow -->

<!-- Scroll -->
<script type="text/javascript">
	$(function() {
		// Get the height of the header
		var headerHeight = $(".header").height();
		
		// Attach the click event
		$('ul.nav-bar a[href*=#]').bind("click", function(e) {
			e.preventDefault();
			
			$('ul.nav-bar li').removeClass('active');
				$(this).parent().addClass('active');
		
			var target = $(this).attr("href"); //Get the target
			var scrollToPosition = $(target).offset().top - headerHeight;
		
			$('html,body').animate({ 'scrollTop': scrollToPosition }, 2000,'easeInOutQuart', function(){
				window.location.hash = "" + target;
				// This hash change will jump the page to the top of the div with the same id
				// so we need to force the page to back to the end of the animation
				$('html,body').animate({ 'scrollTop': scrollToPosition }, 0);
			});
		});
		
		$('.logo a').bind('click',function(event){
			var $anchor = $(this);
			
			$('html, body').stop().animate({
				scrollTop: $($anchor.attr('href')).offset().top
			}, 2000,'easeInOutQuart');
			
			event.preventDefault();
		});
		
		$('a.to-top').bind('click',function(event){
			var $anchor = $(this);
			
			$('html, body').stop().animate({
				scrollTop: $($anchor.attr('href')).offset().top
			}, 2000,'easeInOutQuart');
			
			event.preventDefault();
		});
	});
</script>
<!-- /Scroll -->

<!-- Validate Contact Form -->
<script type="text/javascript" src="<?php echo THEMES_COMINGSOON_URL; ?>javascripts/jquery-validate.min.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		// validate signup form on keyup and submit
		var validator = $(".subscription-form").validate({
			rules: {
				email: {
					required: true,
					email: true
				}
			},
			messages: {
				email: {
					required: "Please enter a valid email address",
					minlength: "Please enter a valid email address"
				}
			},
			// set this class to error-labels to indicate valid fields
			success: function(label) {
				label.addClass("checked");
			}
		});
	});
</script>
<!-- /Validate Contact Form -->

<script type="text/javascript">
	function moveTo(contentArea){
    	var goPosition = $(contentArea).offset().top;
		$('html, body').stop().animate({
			scrollTop: goPosition
		}, 2000,'easeInOutQuart');
    }
</script>

<!-- Google Map -->
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
$(document).ready(function(){
    if(typeof google.maps.LatLng !== "undefined"){
        $(".map_canvas").each(function(){

            var $canvas = $(this);
            var dataZoom = $canvas.attr("data-zoom") ? parseInt($canvas.attr("data-zoom")) : 8;

            var latlng = $canvas.attr("data-lat") ? 
                            new google.maps.LatLng($canvas.attr("data-lat"), $canvas.attr("data-lng")) :
                            new google.maps.LatLng(40.7143528, -74.0059731);

            var myOptions = {
                zoom: dataZoom,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                center: latlng
            };

            var map = new google.maps.Map(this, myOptions);

            if($canvas.attr('data-address')){
                var geocoder = new google.maps.Geocoder();
                geocoder.geocode({ 
                        'address' : $canvas.attr('data-address') 
                    },
                    function(results, status) {                 
                        if (status == google.maps.GeocoderStatus.OK) {
                            map.setCenter(results[0].geometry.location);
                            var marker = new google.maps.Marker({
                                map: map,
                                position: results[0].geometry.location,
                                title: $canvas.attr('data-mapTitle')
                            });
                        }
                });
            }
        });
    }
});
</script>
<!-- /Google Map -->