<div class="row">
    <div class="col-lg-12">
        <h4> <i class="fa fa-print" style="margin-right: 15px"> </i><b>Imprimante</b></h4>
    </div>
</div>

<form action="/filtre/apply" method="post">
    <div class="row">
        <div class="col-lg-4">
            <div class="row">
                <div class="col-lg-12">
                    <i class="fa fa-angle-right" style="margin-right: 15px"> </i>Résolution
                </div>
            </div>
            <div class="row">

            </div>
            <div class="row">
                <div class="col-lg-12">

                    <select class="form-control" name="dpi">
                        <option  value="200" <?php echo $this->printer['dpi'] == '200' ? 'selected' : ''?> >200dpi</option>
                        <option  value="300" <?php echo $this->printer['dpi'] == '300' ? 'selected' : ''?> >300dpi</option>
                        <option  value="600" <?php echo $this->printer['dpi'] == '600' ? "selected" : ''?> >600dpi</option>
                    </select>
                    
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="row">
                <div class="col-lg-12">
                    <i class="fa fa-angle-right" style="margin-right: 15px"> </i>Largeur impression
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <select class="form-control" name="width">
                        <option <?php echo $this->printer['width'] == '4' ? 'selected' : ''?> value="4" >4" (10cm)</option>
                        <option <?php echo $this->printer['width'] == '6' ? 'selected' : ''?> value="6">6" (14cm)</option>
                        <option <?php echo $this->printer['width'] == '8' ? 'selected' : ''?> value="8">8" (16cm)</option>
                        <option <?php echo $this->printer['width'] == '2' ? 'selected' : ''?> value="2">2" (5cm)</option>
                        <option <?php echo $this->printer['width'] == '5' ? 'selected' : ''?> value="5">5" (12cm)</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="row">
                <div class="col-lg-12">
                    <i class="fa fa-angle-right" style="margin-right: 15px"> </i>Gamme
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12" >
                    <select class="form-control" name="gamme">
                        <option <?php echo $this->printer['gamme'] == 'bureau' ? 'selected' : ''?> value="bureau">Bureau</option>
                        <option <?php echo $this->printer['gamme'] == 'si' ? 'selected' : ''?> value="si">Semi-Industrielle</option>
                        <option <?php echo $this->printer['gamme'] == 'i' ? 'selected' : ''?> value="i">Industrielle</option>
                        <option <?php echo $this->printer['gamme'] == 'portative' ? 'selected' : ''?> value="portative">Portatives</option>
                    </select>
                </div>
            </div>
        </div>


    </div>
    <br>
    <div class="row">

        <div class="col-lg-3">
            <div class="row">
                <div class="col-lg-12">
                    <i class="fa fa-angle-right" style="margin-right: 15px"> </i>Utilisation
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <select class="form-control" name="use">
                        <option <?php echo $this->printer['use'] == 'tt' ? 'selected' : ''?> value="tt">Transfert thermique</option>
                        <option <?php echo $this->printer['use'] == 'dt' ? 'selected' : ''?> value="dt">Direct Thermique</option>
                        <option <?php echo $this->printer['use'] == 'both' ? 'selected' : ''?> value="both">Les deux</option>

                    </select>
                </div>
            </div>
        </div>

        <div class="col-lg-3">
            <div class="row">
                <div class="col-lg-12">
                    <i class="fa fa-angle-right" style="margin-right: 15px"> </i>Options
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <select class="form-control" name="opt">
                        <option <?php echo $this->printer['opt'] == 'none' ? 'selected' : ''?> value="none">Aucunes</option>
                        <option <?php echo $this->printer['opt'] == 'tear' ? 'selected' : ''?> value="tear" >Déchirement</option>
                        <option <?php echo $this->printer['opt'] == 'peel' ? 'selected' : ''?> value="peel">Prédecollage( LTS + ré-enrouleur)</option>
                        <option <?php echo $this->printer['opt'] == 'cut' ? 'selected' : ''?> value="cut">Coupe</option>
                    </select>
                </div>
            </div>
        </div>



        <div class="col-lg-6">

            <div class="row">
                <div class="col-lg-12">
                    <i class="fa fa-angle-right" style="margin-right: 15px"> </i>Inteface de connection
                </div>
            </div>

            <div class="row">
                <div class="col-lg-2">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->printer['interface']['serie']) ? 'checked' : ''?>  type="checkbox" name="interface[]" value="serie">
                            Serie
                        </label>
                    </div>
                </div>

                <div class="col-lg-2">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->printer['interface']['parra']) ? 'checked' : ''?>  type="checkbox" name="interface[]" value="parra">
                            Parralléle
                        </label>
                    </div>
                </div>

                <div class="col-lg-2">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->printer['interface']['usb']) ? 'checked' : ''?> type="checkbox" name="interface[]" value="usb">
                            Usb
                        </label>
                    </div>
                </div>

                <div class="col-lg-2">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->printer['interface']['eth']) ? 'checked' : ''?> type="checkbox" name="interface[]" value="eth">
                            Réseau
                        </label>
                    </div>
                </div>

                <div class="col-lg-2">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->printer['interface']['wifi']) ? 'checked' : ''?> type="checkbox" name="interface[]" value="wifi">
                            Wifi
                        </label>
                    </div>
                </div>

            </div>

        </div>
    </div>

    <div class="row" style="padding-top: 10px">
        <div class="col-lg-8">
            <input type="submit" class="btn btn-euro-blue" value="Filtrer">
        </div>

        <div class="col-lg-4">
            <a href="filtre/delete" class="btn btn-euro-pink"
              >Reset</a>
        </div>
    </div>

</form>