<div class="row">
    <div class="col-lg-12">
        <h4> <i class="fa fa-print" style="margin-right: 15px"> </i><b>Terminal</b></h4>
        <span>

        </span>
    </div>
</div>

<form action="/filtre/apply" method="post">
    <div class="row">

        <!--TYPE MATERIEL -->
        <div class="col-lg-3 col-sm-4 col-xs-4">
            <div class="row">
                <div class="col-lg-12">
                    <?php if($this->input['type'] <> 'na' && $this->input['type'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> Type</b>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Type
                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <select class="form-control" name="type">
                        <option  value="na" <?php echo $this->input['type'] == 'na' ? 'selected' : ''?> >N.R</option>
                        <option  value="tm" <?php echo $this->input['type'] == 'tm' ? 'selected' : ''?> >Terminal Mobile</option>
                        <option  value="em" <?php echo $this->input['type'] == 'em' ? 'selected' : ''?> >Terminal Embarqué</option>
                        <option  value="ml" <?php echo $this->input['type'] == 'ml' ? "selected" : ''?> >Main libre</option>
                        <option  value="pda" <?php echo $this->input['type'] == 'pda' ? "selected" : ''?> >PDA</option>
                        <option  value="divers" <?php echo $this->input['type'] == 'divers' ? "selected" : ''?> >Divers</option>
                    </select>
                </div>
            </div>
        </div>
        <!--TYPE MATERIEL -->

        <!--GAMME -->
        <div class="col-lg-3 col-sm-4 col-xs-4">
            <div class="row">
                <div class="col-lg-12">
                    <?php if($this->input['gamme'] <> 'na' && $this->input['gamme'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> Gamme</b>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Gamme
                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <select class="form-control" name="gamme">
                        <option  value="na" <?php echo $this->input['gamme'] == 'na' ? 'selected' : ''?> >N.R</option>
                        <option  value="si" <?php echo $this->input['gamme'] == 'si' ? 'selected' : ''?> >Semie-industrielle</option>
                        <option  value="i" <?php echo $this->input['gamme'] == 'i' ? 'selected' : ''?> >Industrielle</option>
                        <option  value="gf" <?php echo $this->input['gamme'] == 'gf' ? "selected" : ''?> >Grand froid</option>
                    </select>
                </div>
            </div>
        </div>
        <!--GAMME -->

        <!--FORMAT-->
        <div class="col-lg-3 col-sm-4 col-xs-4">
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <?php if($this->input['format'] <> 'na' && $this->input['format'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> Format</b>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Format
                    <?php endif ?>

                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12" >
                    <select class="form-control" name="format">
                        <option <?php echo $this->input['format'] == 'na' ? 'selected' : ''?> value="na">N.R</option>
                        <option <?php echo $this->input['format'] == 'gun' ? 'selected' : ''?> value="gun">Gun</option>
                        <option <?php echo $this->input['format'] == 'rotatif' ? 'selected' : ''?> value="rotatif">Rotatif</option>
                        <option <?php echo $this->input['format'] == 'droit' ? 'selected' : ''?> value="droit">Droit</option>
                    </select>
                </div>
            </div>
        </div>
        <!--FORMAT-->

        <!--SYSTEM OS -->
        <div class="col-lg-3 col-sm-4 col-xs-4">
            <div class="row">
                <div class="col-lg-12">
                    <?php if($this->input['os'] <> 'na' && $this->input['os'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> Système</b>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Système
                    <?php endif ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <select class="form-control" name="os">
                        <option  value="na" <?php echo $this->input['os'] == 'na' ? 'selected' : ''?> >N.R</option>
                        <option  value="ce" <?php echo $this->input['os'] == 'ce' ? 'selected' : ''?> >WinCE</option>
                        <option  value="mo" <?php echo $this->input['os'] == 'mo' ? 'selected' : ''?> >WinMobile</option>
                        <option  value="android" <?php echo $this->input['os'] == 'android' ? "selected" : ''?> >Android</option>
                    </select>
                </div>
            </div>
        </div>
        <!--SYSTEM OS -->

    </div>
    <br>


    <div class="row">

        <!--TAILLE ECRAN-->
        <div class="col-lg-2 col-sm-4 col-xs-4">
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <?php if($this->input['lcd'] <> 'na' && $this->input['lcd'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> LCD</b>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> LCD
                    <?php endif ?>

                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12" >
                    <select class="form-control" name="lcd">
                        <option <?php echo $this->input['lcd'] == 'na' ? 'selected' : ''?> value="na">N.R</option>
                        <option <?php echo $this->input['lcd'] == '3p' ? 'selected' : ''?> value="3p">3"</option>
                        <option <?php echo $this->input['lcd'] == '4p' ? 'selected' : ''?> value="4p">4"</option>
                        <option <?php echo $this->input['lcd'] == '5p' ? 'selected' : ''?> value="5p">5"</option>
                    </select>
                </div>
            </div>
        </div>
        <!--TAILLE ECRAN-->

        <!--CLAVIER-->
        <div class="col-lg-2 col-sm-6 col-xs-6">
            <div class="row">
                <div class="col-lg-12">
                    <?php if($this->input['clavier'] <> 'na' && $this->input['clavier'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> Clavier</b>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Clavier
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <select class="form-control" name="clavier">
                        <option <?php echo $this->input['clavier'] == 'na' ? 'selected' : ''?> value="na">N.R</option>
                        <option <?php echo $this->input['clavier'] == 'nume' ? 'selected' : ''?> value="nume">Numerique</option>
                        <option <?php echo $this->input['clavier'] == 'alpha' ? 'selected' : ''?> value="alpha">Alphanumerique</option>
                        <option <?php echo $this->input['clavier'] == 'hybrid' ? 'selected' : ''?> value="hybrid">hybride</option>

                    </select>
                </div>
            </div>
        </div>
        <!--CLAVIER-->

        <!--Scanner-->
        <div class="col-lg-2 col-sm-6 col-xs-6">
            <div class="row">
                <div class="col-lg-12">
                    <?php if($this->input['scanner'] <> 'nr' && $this->input['scanner'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i> Scanner</b>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i> Scanner
                    <?php endif ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <select class="form-control" name="scanner">
                        <option <?php echo $this->input['scanner'] == 'nr' ? 'selected' : ''?> value="nr"> N.R </option>
                        <option <?php echo $this->input['scanner'] == '1std' ? 'selected' : ''?> value="1std">1d std</option>
                        <option <?php echo $this->input['scanner'] == '1ext' ? 'selected' : ''?> value="1ext">1d ext range</option>
                        <option <?php echo $this->input['scanner'] == '1lg' ? 'selected' : ''?> value="1lg">1d long range</option>
                        <option <?php echo $this->input['scanner'] == '2std' ? 'selected' : ''?> value="2std">2d std</option>
                        <option <?php echo $this->input['scanner'] == '2lg' ? 'selected' : ''?> value="2lg">2d long range</option>
                    </select>
                </div>
            </div>
        </div>
        <!--Scanner-->
        <div class="row visible-xs visible-sm visible-md " style="padding-bottom: 20px">&nbsp; </div>
        <!--INTERFACE LG -->
        <div class="col-lg-6 col-sm-12 col-xs-12 ">
            <div class="row">
                <div class="col-lg-12  col-xs-12">
                    <?php if($this->input['com'] <> 'na' && $this->input['com'] <> null): ?>
                        <b style="color: mediumseagreen">  <i class="fa fa-check-circle" style="margin-right: 5px"> </i>  Interaface de connection</b>
                    <?php else: ?>
                        <i class="fa fa-angle-right" style="margin-right: 15px"> </i>  Interface de connection
                    <?php endif ?>
                </div>
            </div>

            <div class="row">


                <div class="col-lg-4 col-xs-2">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['com']['wifi']) ? 'checked' : ''?> type="checkbox" name="com[]" value="wifi">
                            Wifi
                        </label>
                    </div>
                </div>

                <div class="col-lg-4 col-xs-2">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['com']['bluethooh']) ? 'checked' : ''?> type="checkbox" name="com[]" value="bluethooh">
                            Bluetooh
                        </label>
                    </div>
                </div>

                <div class="col-lg-4 col-xs-2">
                    <div class="checkbox">
                        <label>
                            <input <?php echo isset($this->input['com']['narrow']) ? 'checked' : ''?> type="checkbox" name="com[]" value="narrow">
                            Narrowband
                        </label>
                    </div>
                </div>

            </div>
        </div>
        <!--INTERFACE LG -->
    </div>






    <!--BOUTTON DE VALIDATION-->
    <div class="row" style="padding-top: 10px">

        <div class="col-lg-8 col-sm-8 col-xs-8">
            <input type="submit" class="btn btn-euro-blue " value="Filtrer">
        </div>

        <div class="col-lg-4 col-sm-4 col-xs-4">
            <a href="filtre/delete" class="btn btn-euro-pink"
            >Reset</a>
        </div>
    </div>
    <!--BOUTTON DE VALIDATION-->
</form>