

<section class="properties properties_contact">
    <div class="container">
        <div class="row visible-lg visible-md" style="margin-top: 80px"></div>
        <div class="row visible-sm" style="margin-top: 120px"></div>
        <div class="row visible-xs" style="margin-top: 70px"></div>
        <div class="row" >
            <div class="col-lg-12 col-md-12">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col_blogPost">
                        <h1> <i class="fa fa-search"> </i> Recherche de materiel</h1>

                        <div class="divider"></div>

                        <div class="blogPost">

                            <div class="row">
                                <div class="col-lg-12 col-xs-12">
                                   <?php if(isset($this->search)):?>

                                        <?php if($this->search == 'p') : ?>
                                           <span class="wrapper-choice-selected ">
                                               <b > <i class="fa fa-print" style="font-size: 1.5em"> </i>&nbsp;&nbsp;&nbsp; IMPRIMANTE</b>
                                           </span>
                                        <?php else : ?>
                                           <span class="wrapper-choice-unselected ">
                                               <a href="/filtre/form?f=p" class="link-blue">
                                                   <b><i class="fa fa-print" style="font-size: 1.5em"> </i>&nbsp;&nbsp;&nbsp;
                                                       IMPRIMANTE</b>
                                               </a>
                                           </span>
                                        <?php endif ?>

                                       <?php if($this->search == 'd') : ?>
                                           <span class="wrapper-choice-selected ">
                                               <b> <i class="fa fa-qrcode" style="font-size: 1.5em"> </i>&nbsp;&nbsp;&nbsp; DOUCHETTE</b>
                                           </span>
                                       <?php else : ?>
                                           <span class="wrapper-choice-unselected ">
                                               <a href="/filtre/form?f=d" class="link-blue">
                                                   <b><i class="fa fa-qrcode " style="font-size: 1.5em"> </i>&nbsp;&nbsp;&nbsp; DOUCHETTE</b>
                                               </a>
                                           </span>
                                       <?php endif ?>

                                       <?php if($this->search == 't') : ?>
                                           <span class="wrapper-choice-selected ">
                                               <b> <i class="fa fa-mobile" style="font-size: 1.5em"> </i>&nbsp;&nbsp;&nbsp;  TERMINAL</b>
                                           </span>
                                       <?php else : ?>
                                           <span class="wrapper-choice-unselected ">
                                               <a href="/filtre/form?f=t" class="link-blue"><b> <i class="fa fa-mobile" style="font-size: 1.5em"> </i>&nbsp;&nbsp;&nbsp;  TERMINAL</b></a>
                                           </span>

                                       <?php endif ?>

                                    <?php endif ?>



                                </div>
                            </div>
                            <?php if(isset($this->search))
                                {
                                    if($this->search == 'p')  include("form_printer.phtml");
                                    elseif($this->search == 'd')  include("form_douchette.phtml");
                                    elseif($this->search == 't')  include("form_terminal.phtml");
                                    else include("form_printer.phtml");
                                }
                                else
                                {
                                    include("form_printer.phtml");
                                } ?>

                            <?php include("result.phtml"); ?>
                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div>
            <!-- end col -->

        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
    <!-- end container -->






</section>
<!-- end main content -->
<!-- end properties -->
<!-- start call to action -->
<!-- end call to action -->

<link href="<?php echo URL_DEFAULT_CSS; ?>geo/css/app.css" rel="stylesheet" type="text/css" media="all" />


