
<!--<!-- start subheader -->-->
<?php //echo $this->render($this->subheader);?>
<!--<!-- end subheader section -->-->

<section class="properties properties_contact">
    <div class="container">
        <div class="page_title2">
            <div class="pagenation">
                <div class="padding-top">&nbsp;
                    <a href="/">home</a>
                    <i>/</i> Recherche</div>
                <?php echo $this->render('statics/moteur_v1.phtml'); ?>
            </div>
        </div>
        <div class="divider" style="margin-top:1px"></div>

        <div class="row">

        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col_blogPost">

                        <h1> <i class="fa fa-search"> </i> Recherche de materiel</h1>

                        <div class="divider"></div>

                        <div class="blogPost">
                            <div class="row">
                                <div class="col-lg-12">

                                    <?php
                                    //var_dump($this->session);
                                    //var_dump($this->printer);
                                    ?>
                                    <a href="/filtre/form?f=p">IMPRIMANTE</a>
                                    -
                                    <a href="/filtre/form?f=d">DOUCHETTE</a>
                                    -
                                    <a href="/filtre/form?f=t">TERMINAL</a>

                                </div>
                            </div>
                            <hr>


                            <?php
                                if(isset($this->session['search']))
                                {
                                    if($this->session['search'] == 'p')  include("form_printer.phtml");
                                    elseif($this->session['search'] == 'd')  include("form_douchette.phtml");
                                    elseif($this->session['search'] == 't')  include("form_terminal.phtml");
                                    else include("form_printer.phtml");
                                }
                                else
                                {
                                    include("form_printer.phtml");
                                }
                            ?>

                            <hr>

                            <?php include("result.phtml"); ?>

                        </div>
                    </div>
                </div>
                <!-- end row -->
            </div>
            <!-- end col -->

        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
    <!-- end container -->






</section>
<!-- end main content -->
<!-- end properties -->
<!-- start call to action -->
<!-- end call to action -->




