<?php 
error_reporting(E_ALL ^ E_NOTICE); // hide all basic notices from PHP
global $siteconfig;
//If the form is submitted
if(isset($_POST['submitted'])) {
    
    // require a name from user
    if(trim($_POST['contactName']) === '') {
        $nameError =  'Forgot your name!'; 
        $hasError = true;
    } else {
        $name = trim($_POST['contactName']);
    }
    
    // need valid email
    if(trim($_POST['email']) === '')  {
        $emailError = 'Forgot to enter in your e-mail address.';
        $hasError = true;
    } else if (!preg_match("/^[[:alnum:]][a-z0-9_.-]*@[a-z0-9.-]+\.[a-z]{2,4}$/i", trim($_POST['email']))) {
        $emailError = 'You entered an invalid email address.';
        $hasError = true;
    } else {
        $email = trim($_POST['email']);
    }
        
    // we need at least some content
    if(trim($_POST['comments']) === '') {
        $commentError = 'You forgot to enter a message!';
        $hasError = true;
    } else {
        if(function_exists('stripslashes')) {
            $comments = stripslashes(trim($_POST['comments']));
        } else {
            $comments = trim($_POST['comments']);
        }
    }
        
    // upon no failure errors let's email now!
    if(!isset($hasError)) {

        /*---------------------------------------------------------*/
        /* SET EMAIL YOUR EMAIL ADDRESS HERE                       */
        /*---------------------------------------------------------*/
        $emailTo = 'youremail@gmail.com';
        $subject = 'Submitted message from '.$name;
        $sendCopy = trim($_POST['sendCopy']);
        $body = "Name: $name \n\nEmail: $email \n\nComments: $comments";
        $headers = 'From: ' .' <'.$emailTo.'>' . "\r\n" . 'Reply-To: ' . $email;

        mail($emailTo, $subject, $body, $headers);
        
        // set our boolean completion value to TRUE
        $emailSent = true;
    }
}
?>


<!-- start subheader -->
<?php echo $this->render($this->subheader);?>
<!-- end subheader section -->

<section class="properties properties_contact">
  <div class="container">
    <div class="row">
            <!-- start left column -->
            <!-- end left column -->

            <!-- start contact form -->
            <div class="col-lg-12 col-md-12">
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <h1 class="maj"><?php echo $this->translate("Contact") ?></h1>
                        <div class="divider"></div>
                        <ul class="contactDetails">
                            <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/icon-mail.png" alt="" /> <?php echo str_replace('@',"<img style='margin-right:0px!important' src='".THEMES_DEFAULT_URL."images/arobase_grey.png' width='16' height='16'>",$siteconfig->email);?></li>
                            <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/icon-phone.png" alt="" /> <?php echo $siteconfig->phone?></li>
                           <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/icon-pin.png" alt=""><?php echo $siteconfig->adresse?></li> 
                        </ul>
                        <?php if(isset($emailSent) && $emailSent == true) { ?>
                            <p class="info">Your email was sent!</p>
                        <?php } else { ?>
                        <?php if(isset($hasError) || isset($captchaError) ) { ?>
                            <p class="alert">Error submitting the form</p>
                        <?php } ?>
                        <form method="post" action="contact.php" id="contact-us">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="formBlock">
                                        <label for="contactName"><?php echo $this->translate("Votre Nom") ?></label><br/>
                                        <?php if($nameError != '') { ?>
                                            <br /><span class="error"><?php echo $nameError;?></span> 
                                        <?php } ?>
                                        <input type="text" name="contactName" id="contactName" class="requiredField" value="<?php if(isset($_POST['contactName'])) echo $_POST['contactName'];?>" />
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="formBlock">
                                        <label for="email"><?php echo $this->translate("Votre e-mail") ?></label><br/>
                                        <?php if($emailError != '') { ?>
                                            <br /><span class="error"><?php echo $emailError;?></span>
                                        <?php } ?>
                                        <input type="text" name="email" id="email" class="requiredField email" value="<?php if(isset($_POST['email']))  echo $_POST['email'];?>" />
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="formBlock">
                                        <label for="message"><?php echo $this->translate("Votre message") ?></label><br/>
                                        <?php if($commentError != '') { ?>
                                            <br /><span class="error"><?php echo $commentError;?></span> 
                                        <?php } ?>
                                        <textarea name="comments" id="message" class="requiredField formDropdown"><?php if(isset($_POST['comments'])) { if(function_exists('stripslashes')) { echo stripslashes($_POST['comments']); } else { echo $_POST['comments']; } } ?></textarea>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-lg-offset-9 col-md-4 col-md-offset-8 col-sm-4 col-sm-offset-8">
                                    <div class="formBlock">
                                        <input class="buttonColor" type="submit" value="ENVOYER" />
                                        <input type="hidden" name="submitted" id="submitted" value="true" />
                                    </div>
                                </div>
                            </div><!-- end row -->
                        </form><!-- end form -->
                        <?php } ?>
                    </div><!-- col -->
                </div><!-- end row -->
            </div><!-- end contact form -->

        </div><!-- end row -->
  </div>
  <!-- end container --> 
</section>
<!-- end main content --> 
<!-- end properties --> 
<!-- start call to action -->
<!-- end call to action -->
<script src="<?php echo THEMES_DEFAULT_URL; ?>js/respond.js"></script>
