<?php $id_item = Genius_Class_Utils::idx($this->slide, 'id', 0); ?>

<!-- Content wrapper -->
<div class="wrapper">

    <?php echo Genius_Class_Snippets::breadcrumb($this->translate("Diaporamas"), '/admin/slides'); ?>

    <!-- Page header -->
    <div class="page-header">
        <div class="page-title">
            <h2><?php echo $this->translate("Diaporamas"); ?></h2>
        </div>
    </div>
    <!-- /page header -->

    <div class="line"></div>

    <div class="span12">
        <form method="post" action="" id="slides-form" class="form-horizontal form-to-validate">
            <input type="hidden" value="<?php echo Genius_Class_Utils::idx($this->slide, 'id', ''); ?>" id="id" name="Slides[id]">

            <div class="mt30"><?php Genius_Class_Snippets::multilingualTabs(); ?></div>	

	    	<div class="row-fluid">
		    	<div class="span12">
			    	<fieldset>

					    <div class="widget row-fluid">
					    	<div class="navbar">
						        <div class="navbar-inner">
						            <h6><?php echo $this->translate("Informations générales"); ?></h6>
						        </div>
						    </div>

						    <div class="well tab-form-content">
						    	<div class="control-group">
						    	    <label class="control-label" for="title"><span class="text-error">*</span> <?php echo $this->translate("Titre"); ?>:</label>
						    	    <div class="controls">
						    	        <?php 
						    	            $attributes = array(
						    	                'classic' => array(
						    	                    'id'            => 'title'
						    	                    ,'autocomplete' => 'off'
						    	                )
						    	                ,'custom' => array(
						    	                    'class'        => 'validate[required] span12 multilingual'
						    	                    ,'module'      => 'Slides'
						    	                    ,'name'        => 'title'
						    	                    ,'data'        => $this->slide
						    	                )
						    	            );
						    	            Genius_Class_Forms::textMultilingual($attributes); 
						    	        ?>
						    	    </div>
						    	</div>

						    	<div class="control-group">
						    		<label class="control-label" for="link"> <?php echo $this->translate("Lien"); ?>:</label>
						    		<div class="controls"><input type="text" class="span12" name="Slides[link]" id="Slide_link" value="<?php echo Genius_Class_Utils::idx($this->slide, 'link', ''); ?>"></div>
						    	</div>
                                
                                <div class="control-group">
                                    <label class="control-label" for="order_item"> Order:</label>
                                    <div class="controls">
                                        <select class="styled" id="order_item" name="Slides[order_item]" style="opacity: 0;">
                                            <?php
                                            if ($this->do == "edit"):
                                                $slides = Genius_Model_Slide::getSlideByIdOrder($this->id_slide);
                                            else:
                                                $slides = array();
                                            endif;

                                            $options = array(
                                                'atfirst' => array(
                                                    'value' => 1
                                                    , 'title' => "At first"
                                                )
                                                , 'atend' => array(
                                                    'title' => "At end"
                                                )
                                                , 'optgrouplabel' => "After"
                                                , 'options' => $slides
                                                , 'tablename' => TABLE_PREFIX . 'slides'
                                                , 'id_slide' => (!empty($this->id_slide)) ? $this->id_slide : ''
                                            );
                                            Genius_Class_Forms::optionsOrderItemSlide($options);
                                            ?>
                                        </select>
                                    </div>
                                </div>

					        	<div class="control-group">
					        	    <label class="control-label" for="text"> <?php echo $this->translate("Description"); ?>:</label>
					        	    <div class="controls">
					        	        <?php 
					        	            $attributes = array(
					        	                'classic' => array(
					        	                    'autocomplete' => 'off'
					        	                    ,'rows'         => 10
					        	                )
					        	                ,'custom' => array(
					        	                	'id'            => 'text'
					        	                    ,'class'        => 'span12 multilingual ckeditor'
					        	                    ,'module'      => 'Slides'
					        	                    ,'name'        => 'text'
					        	                    ,'data'        => $this->slide
					        	                )
					        	            );
					        	            Genius_Class_Forms::textareaMultilingual($attributes); 
					        	            Genius_Class_Ckeditor::initToggleCkeditor('text');
					        	        ?>
					        	    </div>
					        	</div>
				            	
						   	</div>
					   	</div>

					   	<?php
					   		if($this->do=="edit"){ 
					   			Genius_Class_Forms::multipleUpload(
					   				'file-uploader'
					   				,'folder=slides&id_module=5&id_item='.Genius_Class_Utils::idx($this->slide, 'id', '')
					   			); 	 
					   		} 
					   	?>

			   		    <!-- Default Datatable -->
			   		    <div class="widget row-fluid">
			   		        <div class="table-overflow">
			   		            <table class="table table-striped table-bordered" id="data-table">
			   		                <thead>
			   		                    <tr>
			   		                        <th width="80">Images</th>
			   		                        <th width="80">Couverture</th>
			   		                        <th>Name</th>
			   		                        <th>Caption</th>
			   		                        <th>Alt</th>
			   		                        <th class="acenter" width="10%">Actions</th>
			   		                    </tr>
			   		                </thead>
			   		                <tbody>
			   		                	<tr>
			   								<td colspan="6" class="dataTables_empty">Loading data...</td>
			   							</tr>
			   		                </tbody>
			   		            </table>

			   		            <script type="text/javascript">
			   			            $(function(){ 
			   			            	$('#data-table').dataTable({
			   			            		"bJQueryUI"  : false,
			   			            		"bAutoWidth" : false,
			   			            		"bProcessing": false,
			   			            		"bServerSide": true,
			   			            		"iDisplayLength": 5,
			   			            		"aLengthMenu": [
			   			            			[5, 10],
			   			            			[5, 10]
			   			            		],
			   			            		"sAjaxSource": "/admin/upload/getimages/format/html?folder=slides&id_module=5&id_item=<?php echo $id_item; ?>",
			   			            		"sPaginationType": "full_numbers",
			   			            		"sDom": '<"datatable-header"Cfril>t<"datatable-footer"p>',
			   			            		"oLanguage": {
			   			            			"sSearch": "_INPUT_",
			   			            			"sLengthMenu": "<span>Show entries:</span> _MENU_",
			   			            			"oPaginate": { "sFirst": "First", "sLast": "Last", "sNext": ">", "sPrevious": "<" }
			   			            		},
			   			            		"aoColumns": [
			   			            			{ "bSortable": false },
			   			            			{ "bSortable": false },
			   			            			{ "bSortable": true },
			   			            			{ "bSortable": true },
			   			            			{ "bSortable": true },
			   			            			{ "bSortable": false },
			   			            		],
			   			            		"fnDrawCallback": function (oSettings) {
			   			            		    $("#data-table_wrapper .styled").uniform();
			   			            		    $('#data-table_wrapper .tip').tooltip();
			   			            		    $("#data-table_wrapper #checkAll").closest('.checker > span').removeClass('checked');
			   			            		    $('#data-table_wrapper .dataTables_filter input').attr("placeholder", "Enter seach terms here...");
			   			            		}
			   			                });		

			   			                $(".delete").live("click", function(e){
			   			                	e.preventDefault();

			   			                	var id = $(this).attr('id');		
			   			                	bootbox.confirm("Voulez-vous vraiment supprimer cet item?", function(confirmed) {
			   			                		if(confirmed){ 
			   			                			$.post("/admin/upload/delete"
			   			                				,{ 
			   			                					"id" : id
			   			                				}, 
			   			                				function(data){
			   			                					table = $('#data-table').dataTable();
			   			                					table.fnDraw();		
			   			                				}
			   			                				,'json'
			   			                			);		 	 
			   			                		}
			   			                	});
			   			                });	 

			   			                $(".cover").live("click", function(e){
			   			                	var id = $(this).attr('value');		
			   	                			$.post("/admin/upload/changecover"
			   	                				,{ 
			   	                					"id" : id
			   	                					,"id_module" : 5
			   	                					,"id_item" : "<?php echo $id_item; ?>"
			   	                				}, 
			   	                				function(data){
			   	                					table = $('#data-table').dataTable();
			   	                					table.fnDraw();		
			   	                				}
			   	                				,'json'
			   	                			);		 	 
			   			                });	
			   			            });
			   		            </script>
			   		        </div>
			   		    </div>
			   		    <!-- /Default Datatable -->

					</fieldset>
			    </div>
			    
			</div>

            <div class="line mt30"></div>

            <div class="form-actions align-left nobordertop form-actions-bg">
                <button class="btn btn-primary" type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                <button type="button" class="btn btn-danger ml5" onclick="window.location.href='/admin/slides'"><?php echo $this->translate("Retour"); ?></button>
            </div>

            <div class="line mb30"></div>
        </form>
    </div>

</div>
<!-- /content wrapper -->