<!-- Fixed top -->
<div id="top">
	<div class="fixed">
		<a href="/admin" title="Lynxis Backoffice Panel" class="logo">Backoffice Panel</a>
	</div>
</div>
<!-- /fixed top -->

<!-- Breadcrumbs line -->
<div class="crumbs">
    <ul id="breadcrumbs" class="breadcrumb"> 
        <li><a href="/admin"><?php echo $this->translate("Tableau de bord"); ?></a></li>
        <li class="active"><a title="Login"><?php echo $this->translate("S'authentifier"); ?></a></li>
    </ul>
</div>
<!-- /breadcrumbs line -->