<!--    CATEGORIE DOUCHETTE-->
<div class="panel- panel-d">

    <div class="panel-h" role="tab" id="douchette">
        <div class="container panel-t">
            <div class="col-sm-9 col-md-9 col-lg-9 ">
                <h4 >
                        <span class="fa-stack fa-lg euro-stack">
                               <i class="fa fa-circle fa-stack-2x"></i>
                               <i class="fa fa-barcode fa-stack-1x fa-inverse "></i>
                        </span>
                    &nbsp;

                    <a class="collapsed"
                       role="button"
                       data-toggle="collapse"
                       data-parent="#accordion"
                       href="#douchettedata"
                       aria-expanded="false"
                       aria-controls="douchettedata">
                        <b>L</b>ecteur Code-barre
                    </a>
                </h4>
            </div>
            <div class="col-sm-3 col-md-3 col-lg-3 text-right" style="padding-top: 17px">
                <span class="badge-euro">3</span>
            </div>
        </div>
    </div>

    <div id="douchettedata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="douchette">
        <div class="panel-b">
            <div class="row bb3pink" >
                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                    <a href="/filtre">
                        <div class="row" id="image_configurateur">
                            <img src="<?php echo PROJECT.'/upload/images/geo/9300.jpg' ?>" alt="">
                        </div>
                        <div class="row pink b"><b>DOUCHETTE</b></div>
                    </a>
                </div>
                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                    <a href="/filtre">
                        <div class="row" id="image_configurateur">
                            <img src="<?php echo PROJECT.'/upload/images/geo/rs6000.jpg' ?>" alt="">
                        </div>
                        <div class="row pink b"><b>RING</b></div>
                    </a>
                </div>
                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                    <a href="/filtre">
                        <div class="row" id="image_configurateur">
                            <img src="<?php echo PROJECT.'/upload/images/geo/2200.jpg' ?>" alt="">
                        </div>
                        <div class="row pink b"><b>FIXE</b></div>
                    </a>

                </div>
                <br><br>
            </div>
        </div>
    </div>

</div>
<!--    FIN CATEGORIE DOUCHETTE-->