<br>
<br>

<div class="row">
    <div class="col-lg-12">
     <?php include('search_autocomplete.phtml') ?>
    </div>
</div>

<br>

<div class="row">
    <div class="col-md-12 text-left">
        <h3> <i class="fa fa-gear"> </i> &nbsp;CONFIGURATEUR</h3>
    </div>
</div>
<br>
<div class="panel-g" id="accordion" role="tablist" aria-multiselectable="true">
    <?php include('printer_filter.phtml') ?>
    <?php include('douchette_filter.phtml') ?>
    <?php include('terminal_filter.phtml') ?>
    <?php include('poste_filter.phtml') ?>
</div>