<br>
<br>
<div class="row">
    <div class="col-lg-12">
        <span class="euro-search">
        <input  type="text" class="form-control" placeholder="Rechercher un materiel">
        </span>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12 text-left">
        <h3>CONFIGURATEUR</h3>
    </div>
</div>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

    <div class="panel panel-default">

        <div class="panel-heading" role="tab" id="prt">
            <h4 class="panel-title">
                <a class="collapsed"
                   role="button"
                   data-toggle="collapse"
                   data-parent="#accordion"
                   href="#prtdata"
                   aria-expanded="false"
                   aria-controls="prtdata">
                    Imprimantes
                </a>
            </h4>
        </div>

        <div id="prtdata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="prt">
            <div class="panel-body">

                <div class="panel-group" id="prtl" role="tablist" aria-multiselectable="true">

                    <div class="panel panel-default">

                        <div class="panel-heading" role="tab" id="etik">
                            <h4 class="panel-title">
                                <a class="collapsed"
                                   role="button"
                                   data-toggle="collapse"
                                   data-parent="#prt"
                                   href="#etikdata"
                                   aria-expanded="false"
                                   aria-controls="etikdata">
                                    Etiquettes
                                </a>
                            </h4>
                        </div>

                        <div id="etikdata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="etik">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-md-4">Couleur</div>
                                    <div class="col-md-4">Thermique</div>
                                    <div class="col-md-4">XXXXX XXX</div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                </div>
        </div>

    </div>

    <div class="panel panel-default">

        <div class="panel-heading" role="tab" id="douchette">
            <h4 class="panel-title">
                <a class="collapsed"
                   role="button"
                   data-toggle="collapse"
                   data-parent="#accordion"
                   href="#douchettedata"
                   aria-expanded="false"
                   aria-controls="douchettedata">
                    Douchettes
                </a>
            </h4>
        </div>

        <div id="douchettedata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="douchette">
            <div class="panel-body">
                x
            </div>
        </div>

    </div>

    <div class="panel panel-default">

        <div class="panel-heading" role="tab" id="termi">
            <h4 class="panel-title">
                <a class="collapsed"
                   role="button"
                   data-toggle="collapse"
                   data-parent="#accordion"
                   href="#termidata"
                   aria-expanded="false"
                   aria-controls="termidata">
                    Douchettes
                </a>
            </h4>
        </div>

        <div id="termidata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="termi">
            <div class="panel-body">
                x
            </div>
        </div>

    </div>

</div>