<!--    CATEGORIE POSTE DE TRAVAIL-->
<div class="panel- panel-d">

    <div class="panel-h" role="tab" id="termi">
        <div class="container panel-t">
            <div class="col-sm-12 col-md-12 col-lg-12 ">
                <h4 >
                        <span class="fa-stack fa-lg euro-stack">
                               <i class="fa fa-circle fa-stack-2x"></i>
                               <i class="fa fa-laptop fa-stack-1x fa-inverse "></i>
                        </span>
                    &nbsp;

                    <a class="collapsed"
                       role="button"
                       data-toggle="collapse"
                       data-parent="#accordion"
                       href="#postedata"
                       aria-expanded="false"
                       aria-controls="postedata">
                        <b>P</b>ost de travail
                    </a>
                </h4>
            </div>

        </div>
    </div>

    <div id="postedata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="poste">
        <div class="panel-b">
            x
        </div>
    </div>

</div>
<!--    FIN CATEGORIE POSTE DE TRAVAIL-->