<!--    CATEGORIE POSTE DE TRAVAIL-->
<div class="panel- panel-d">

    <div class="panel-h" role="tab" id="termi">
        <div class="container panel-t">
            <div class="col-sm-9 col-md-9 col-lg-9 ">
                <h4 >
                        <span class="fa-stack fa-lg euro-stack">
                               <i class="fa fa-circle fa-stack-2x"></i>
                               <i class="fa fa-laptop fa-stack-1x fa-inverse "></i>
                        </span>
                    &nbsp;

                    <a class="collapsed"
                       role="button"
                       data-toggle="collapse"
                       data-parent="#accordion"
                       href="#douchettedata"
                       aria-expanded="false"
                       aria-controls="douchettedata">
                        <b>P</b>ost de travail
                    </a>
                </h4>
            </div>
            <div class="col-sm-3 col-md-3 col-lg-3 text-right" style="padding-top: 17px">
                <span class="badge-euro">4</span>
            </div>
        </div>
    </div>

    <div id="termidata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="termi">
        <div class="panel-b">
            x
        </div>
    </div>

</div>
<!--    FIN CATEGORIE POSTE DE TRAVAIL-->