<!--    CATEGORIE IMPRIMANTE-->
<div class="first-panel- ">
    <div class="panel-h" role="tab" id="prt">
        <div class="container panel-t">
            <div class="col-sx-12 col-sm-12 col-md-12 col-lg-12 ">
                <h4>
                <span class="fa-stack fa-lg euro-stack">
                       <i class="fa fa-circle fa-stack-2x"></i>
                       <i class="fa fa-print fa-stack-1x fa-inverse "></i>
                </span>
                    &nbsp;

                    <a class="collapsed"
                       role="button"
                       data-toggle="collapse"
                       data-parent="#accordion"
                       href="#prtdata"
                       aria-expanded="false"
                       aria-controls="prtdata">
                        <b>I</b>mprimantes
                    </a>
                </h4>
            </div>
        </div>
    </div>

    <div id="prtdata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="prt">
        <div class="panel-b">

            <div class="panel-g" id="prtl" role="tablist" aria-multiselectable="true">

                <div class="second-nested-panel- ">
                    <div class="second-nested-panel-h" role="tab" id="etik">
                        <div class="second-nested-panel-t">
                            <a class="collapsed"
                               role="button"
                               data-toggle="collapse"
                               data-parent="#prtdata"
                               href="#etikdata"
                               aria-expanded="false"
                               aria-controls="etikdata">
                                <i class="fa fa-angle-right"> </i> &nbsp; &nbsp; <b class="">E</b>tiquettes
                            </a>
                        </div>
                    </div>

                    <div id="etikdata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="etik">
                        <div class="second-nested-panel-b">
                            <div class="row" style="">
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a href="/filtre">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/zt600_.jpg' ?>" alt="">
                                        </div>
                                        <div class="row pink b"><b>THERMIQUE</b></div>
                                    </a>
                                </div>
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a href="/filtre">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/zt600_.jpg' ?>" alt="">
                                        </div>
                                        <div class="row pink b"><b>BADGEUSE</b></div>
                                    </a>
                                </div>
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a href="/filtre">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/zt600_.jpg' ?>" alt="">
                                        </div>
                                        <div class="row pink b"><b>COULEUR</b></div>
                                    </a>

                                </div>
                                <br><br>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="second-nested-panel- panel-d">
                    <div class="second-nested-panel-h" role="tab" id="laser">
                        <h4 class="second-nested-panel-t">
                            <a class="collapsed"
                               role="button"
                               data-toggle="collapse"
                               data-parent="#prtdata"
                               href="#laserdata"
                               aria-expanded="false"
                               aria-controls="laserdata">
                                <i class="fa fa-angle-right "> </i> &nbsp; &nbsp; <b>L</b>aser
                            </a>
                        </h4>
                    </div>

                    <div id="laserdata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="laser">
                        <div class="second-nested-panel-b">
                            <div class="row" style="">
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a href="/filtre">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/zt600_.jpg' ?>" alt="">
                                        </div>
                                        <div class="row pink b"><b>THERMIQUE</b></div>
                                    </a>
                                </div>
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a href="/filtre">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/zt600_.jpg' ?>" alt="">
                                        </div>
                                        <div class="row pink b"><b>BADGEUSE</b></div>
                                    </a>
                                </div>
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a href="/filtre">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/zt600_.jpg' ?>" alt="">
                                        </div>
                                        <div class="row pink b"><b>COULEUR</b></div>
                                    </a>

                                </div>
                                <br><br>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="second-nested-panel- panel-d">
                    <div class="second-nested-panel-h" role="tab" id="matri">
                        <h4 class="second-nested-panel-t">
                            <a class="collapsed"
                               role="button"
                               data-toggle="collapse"
                               data-parent="#prt"
                               href="#matridata"
                               aria-expanded="false"
                               aria-controls="matridata">
                                <i class="fa fa-angle-right "> </i> &nbsp; &nbsp; <b>M</b>atricielle
                            </a>
                        </h4>
                    </div>

                    <div id="matridata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="matri">
                        <div class="second-nested-panel-b">
                            <div class="row" style="">
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a href="/filtre">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/zt600_.jpg' ?>" alt="">
                                        </div>
                                        <div class="row pink b"><b>THERMIQUE</b></div>
                                    </a>
                                </div>
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a href="/filtre">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/zt600_.jpg' ?>" alt="">
                                        </div>
                                        <div class="row pink b"><b>BADGEUSE</b></div>
                                    </a>
                                </div>
                                <div class="col-sm-4 col-md-6 col-lg-4 text-center">
                                    <a href="/filtre">
                                        <div class="row" id="image_configurateur">
                                            <img src="<?php echo PROJECTS.'/upload/images/geo/zt600_.jpg' ?>" alt="">
                                        </div>
                                        <div class="row pink b"><b>COULEUR</b></div>
                                    </a>

                                </div>
                                <br><br>
                            </div>
                        </div>
                    </div>

                </div>


            </div>

        </div>
    </div>
</div>
<!--  FIN  CATEGORIE IMPRIMANTE-->