<!--    CATEGORIE TERMINAL-->
<div class="panel- panel-d">

    <div class="panel-h" role="tab" id="termi">
        <div class="container panel-t">
            <div class="col-sm-12 col-md-12 col-lg-12 ">
                <h4 >
                        <span class="fa-stack fa-lg euro-stack">
                               <i class="fa fa-circle fa-stack-2x"></i>
                               <i class="fa fa-mobile fa-stack-1x fa-inverse "></i>
                        </span>
                    &nbsp;

                    <a
                        style=""
                        class="collapsed"
                        role="button"
                        data-toggle="collapse"
                        data-parent="#accordion"
                        href="#terminaldata"
                        aria-expanded="false"
                        aria-controls="terminaldata">
                        <b>T</b>erminaux mobiles & <b>E</b>mbarqués
                    </a>
                </h4>
            </div>

        </div>
    </div>

    <div id="terminaldata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="terminal">
        <div class="panel-b">
            <div class="row" >
                <div class="col-sm-6 col-md-6 col-lg-6 text-center">
                    <a href="/filtre">
                        <div class="row" id="image_configurateur">
                            <img src="<?php echo PROJECTS.'/upload/images/geo/zt600_.jpg' ?>" alt="">
                        </div>
                        <div class="row pink b"><b>TERMINAL MOBILE</b></div>
                    </a>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6 text-center">
                    <a href="/filtre">
                        <div class="row" id="image_configurateur">
                            <img src="<?php echo PROJECTS.'/upload/images/geo/zt600_.jpg' ?>" alt="">
                        </div>
                        <div class="row pink b"><b>PDA</b></div>
                    </a>
                </div>
            </div>
            <br>
            <div class="row bb3pink" >
                <div class="col-sm-6 col-md-6 col-lg-6 text-center">
                    <a href="/filtre">
                        <div class="row" id="image_configurateur">
                            <img src="<?php echo PROJECTS.'/upload/images/geo/zt600_.jpg' ?>" alt="">
                        </div>
                        <div class="row pink b"><b>EMBARQUE</b></div>
                    </a>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6 text-center">
                    <a href="/filtre">
                        <div class="row" id="image_configurateur">
                            <img src="<?php echo PROJECTS.'/upload/images/geo/zt600_.jpg' ?>" alt="">
                        </div>
                        <div class="row pink b"><b>TERMINAL POIGNET</b></div>
                    </a>
                </div>

                <br><br>
            </div>
        </div>
    </div>

</div>
<!--    FIN CATEGORIE TERMINAL-->