<!--    CATEGORIE TERMINAL-->
<div class="panel- panel-d">

    <div class="panel-h" role="tab" id="termi">
        <div class="container panel-t">
            <div class="col-sm-10 col-md-10 col-lg-10 ">
                <h4 >
                        <span class="fa-stack fa-lg euro-stack">
                               <i class="fa fa-circle fa-stack-2x"></i>
                               <i class="fa fa-mobile fa-stack-1x fa-inverse "></i>
                        </span>
                    &nbsp;

                    <a
                        style="font-size: 0.9em"
                        class="collapsed"
                        role="button"
                        data-toggle="collapse"
                        data-parent="#accordion"
                        href="#douchettedata"
                        aria-expanded="false"
                        aria-controls="douchettedata">
                        <b>T</b>erminal mobile <b>E</b>mbarqué
                    </a>
                </h4>
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2 text-right" style="padding-top: 17px">
                <span class="badge-euro">5</span>
            </div>
        </div>
    </div>

    <div id="termidata" class="panel-collapse collapse" role="tabpanel" aria-labelledby="termi">
        <div class="panel-b">
            x
        </div>
    </div>

</div>
<!--    FIN CATEGORIE TERMINAL-->