<!-- Content wrapper -->
<div class="wrapper">
    <?php echo Genius_Class_Snippets::breadcrumb($this->translate("Catégories"), '/admin/categories'); ?>
    <!-- Page header -->
    <div class="page-header">
        <div class="page-title">
            <h2><?php echo $this->translate("Catégories"); ?></h2>
        </div>
    </div>
    <!-- /page header -->

    <div class="line"></div>

    <div class="span12">
        <form method="post" action="" id="categories-form" class="form-horizontal form-to-validate" enctype="multipart/form-data">
            <input type="hidden" value="<?php echo Genius_Class_Utils::idx($this->category, 'id', ''); ?>" id="id" name="Categories[id]">
            <input type="hidden" value="<?php echo Genius_Class_Utils::idx($this->category, 'order_item', ''); ?>" id="id" name="Categories[old_order_item]">

            <div class="widget row-fluid mt30">
                <div class="box">
                    <div class="tabbable"><!-- multilingual tabs -->
                        <?php Genius_Class_Snippets::multilingualTabs(); ?>

                        <div class="box">
                            <div class="navbar">
                                <div class="navbar-inner">
                                    <h6><i class="icon-cog"></i>General infos</h6>
                                </div>
                            </div>

                            <div class="well tab-form-content">
                                <div class="control-group">
                                    <label class="control-label" for="title"><span class="text-error">*</span> Title:</label>
                                    <div class="controls">
                                        <?php
                                        $attributes = array(
                                            'classic' => array(
                                                'id' => 'title'
                                                , 'autocomplete' => 'off'
                                            )
                                            , 'custom' => array(
                                                'class' => 'validate[required] span12 multilingual'
                                                , 'module' => 'Categories'
                                                , 'name' => 'title'
                                                , 'data' => $this->category
                                            )
                                        );
                                        Genius_Class_Forms::textMultilingual($attributes);
                                        ?>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="pastille"> Pastille :</label>
                                    <div class="controls">
                                        <?php
                                        $attributes = array(
                                            'classic' => array(
                                                'id' => 'pastille'
                                                , 'autocomplete' => 'off'
                                            )
                                            , 'custom' => array(
                                                'class' => ' span12 multilingual'
                                                , 'module' => 'Categories'
                                                , 'name' => 'pastille'
                                                , 'data' => $this->category
                                            )
                                        );
                                        Genius_Class_Forms::textMultilingual($attributes);
                                        ?>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="modele_pastille"> Modèle pastille :</label>
                                    <div class="controls">
                                        <select class="styled" id="modele_pastille" name="Categories[modele_pastille]" style="opacity: 0;">
                                            <option value="0">Selectionnez votre pastille</option>>
                                            <?php
                                            $types_pastille = Genius_Model_Global::select(TABLE_PREFIX . "pastilles", '*');
                                            foreach ($types_pastille as $key => $value):
                                                $selected = (($this->do == 'edit') && isset($this->category['modele_pastille']) && ($this->category['modele_pastille'] == $value['id'])) ? 'selected="selected"' : '';
                                                ?>
                                                <option value="<?php echo $value['id'] ?>" <?php echo $selected ?>><?php echo $value['title']; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="offre_speciale"> Est-ce une offre spéciale ? :</label>
                                    <div class="controls">
                                        <label class="radio inline">
                                            <input type="radio" id="is_os" class="" value="1" name="is_offre_speciale" <?php if ($this->do == 'edit') if ($this->category['is_offre_speciale'] == 1) echo "checked='checked'"; ?>>
                                            Oui
                                        </label>
                                        <label class="radio inline"> 
                                            <?php if ($this->do == 'edit'): ?>
                                                <input type="radio" id="is_os" class="" value="0" name="is_offre_speciale" <?php if ($this->category['is_offre_speciale'] == 0) echo "checked='checked'"; ?>>
                                            <?php else: ?>
                                                <input type="radio" id="is_os" class="" value="0" name="is_offre_speciale" checked='checked'>
                                            <?php endif; ?>
                                            Non
                                        </label>
                                    </div>
                                </div>
                                <?php
                                $display = "";
                                if ($this->do == 'edit'):
                                    $display = ($this->category['is_offre_speciale'] == 1) ? "display:block" : "display:none";
                                else:
                                    $display = "display:none";
                                endif;
                                ?>
                                <div class="control-group display_offre_speciale" style="<?php echo $display; ?>">
                                    <label class="control-label" for="offre_speciale"> Activer/Desactiver offre spéciale :</label>
                                    <div class="controls">
                                        <label class="radio inline">
                                            <input type="radio" id="aos_activer" class="" value="1" name="activation_offre_speciale" <?php if ($this->do == 'edit') if ((isset($this->category['etat_offre_speciale'])) && ($this->category['etat_offre_speciale'] == 1)) echo "checked='checked'"; ?>>
                                            Activer
                                        </label>
                                        <label class="radio inline">
                                            <input type="radio" id="aos_desactiver" class="" value="0" name="activation_offre_speciale" <?php if ($this->do == 'edit') if ((isset($this->category['etat_offre_speciale'])) && ($this->category['etat_offre_speciale'] == 0)) echo "checked='checked'"; ?>>
                                            Desactiver
                                        </label>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for=""> Lien offre spéciale :</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><?php echo BASE_URL ?>/</span><input id="prependedInput" type="text" placeholder="" name="Categories[lien_offre_speciale]" class="span12" width="100%" value="<?php echo Genius_Class_Utils::idx($this->category, 'lien_offre_speciale', ''); ?>"/>
                                        </div>
                                    </div>
                                </div>


                                <div class="control-group">
                                    <label class="control-label" for="id_category_group"><span class="text-error">*</span> Group:</label>
                                    <div class="controls">
                                        <select class="styled validate[required]" id="id_category_group" name="Categories[id_category_group]" style="opacity: 0;" onchange="getcategories(this.value)">
                                            <?php
                                            $modules_groups = Genius_Model_Module::getModulesGroups();
                                            $options = array(
                                                'default' => array(
                                                    'value' => ""
                                                    , 'title' => "Choose a group"
                                                )
                                                , 'selected' => (!empty($this->category['id_category_group'])) ? $this->category['id_category_group'] : ''
                                                , 'options' => $modules_groups
                                            );
                                            Genius_Class_Forms::optionsModulesGroups($options);
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="id_category">Catégorie (Pour offre spéciale):</label>
                                    <div class="controls">
                                        <?php if ($this->do == 'add'): ?>
                                            <select name="Categories[categories]" id="categories_offres_speciales" class="styled">
                                            </select>
                                            <?php
                                        else:
                                            ?>
                                            <select name="Categories[categories]" id="categories_offres_speciales" class="styled">
                                                <?php
                                                $categories = Genius_Model_Category::getCategoryByIdCategoryGroup($this->category['id_category_group']);
                                                foreach ($categories as $k => $item) {
                                                    $selected = ($this->category['id_cat_offre_speciale_concerne'] == $item['id']) ? 'selected="selected"' : '';
                                                    if ($item['id'] != $this->category['id']):
                                                        echo '<option ' . $selected . ' value="' . $item['id'] . '">' . $item['title'] . '</option>';
                                                    endif;
                                                }
                                                ?>
                                            </select>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="order_item"> Order:</label>
                                    <div class="controls">
                                        <select class="styled" id="order_item" name="Categories[order_item]" style="opacity: 0;">
                                            <?php
                                            if ($this->do == "edit"):
                                                $categories = Genius_Model_Category::getCategoryByIdCategoryGroup($this->category['id_category_group']);
                                            else:
                                                $categories = array();
                                            endif;

                                            $options = array(
                                                'atfirst' => array(
                                                    'value' => 1
                                                    , 'title' => "At first"
                                                )
                                                , 'atend' => array(
                                                    'title' => "At end"
                                                )
                                                , 'optgrouplabel' => "After"
                                                , 'options' => $categories
                                                , 'tablename' => TABLE_PREFIX . 'categories'
                                                , 'id_category_group' => (!empty($this->category['id_category_group'])) ? $this->category['id_category_group'] : ''
                                            );
                                            Genius_Class_Forms::optionsOrderItemCategory($options);
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="title">Logo marque:</label>
                                    <div class="controls">
                                        <input type="file" class="styled" name="logo" value="">
                                        <i>Le format png,jpg,gif sont acceptés - <b>90x30</b></i>
                                        <br>
                                        <?php
                                        if ($this->do == "edit"):
                                            if (!empty($this->category['logo_marque'])):
                                                $url = UPLOAD_URL . 'logo_marque/' . $this->category['logo_marque'];
                                                $path = UPLOAD_PATH . 'logo_marque/' . $this->category['logo_marque'];
                                                $img = Genius_Class_Timthumb::createThumb($path,90,30);
                                                if (file_exists($path) && is_file($path)) {
                                                    echo '<img src="' . $img . '">';
                                                }
                                            endif;
                                        endif;
                                        ?>
                                    </div>
                                </div>  
                                <div class="control-group">
                                    <label class="control-label" for="accroche"> Phrase d'accroche:</label>
                                    <div class="controls">
                                        <?php
                                        $attributes = array(
                                            'classic' => array(
                                                'autocomplete' => 'off'
                                                , 'rows' => 10
                                            )
                                            , 'custom' => array(
                                                'id' => 'accroche'
                                                , 'class' => 'span12 multilingual ckeditor'
                                                , 'module' => 'Categories'
                                                , 'name' => 'accroche'
                                                , 'data' => $this->category
                                            )
                                        );
                                        Genius_Class_Forms::textareaMultilingual($attributes);
                                        Genius_Class_Ckeditor::initToggleCkeditor('accroche');
                                        ?>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="text"> Description:</label>
                                    <div class="controls">
                                        <?php
                                        $attributes = array(
                                            'classic' => array(
                                                'autocomplete' => 'off'
                                                , 'rows' => 10
                                            )
                                            , 'custom' => array(
                                                'id' => 'text'
                                                , 'class' => 'span12 multilingual ckeditor'
                                                , 'module' => 'Categories'
                                                , 'name' => 'text'
                                                , 'data' => $this->category
                                            )
                                        );
                                        Genius_Class_Forms::textareaMultilingual($attributes);
                                        Genius_Class_Ckeditor::initToggleCkeditor('text');
                                        ?>
                                    </div>
                                </div>

                                <?php if ($this->is_marque || $this->is_type): ?>

                                    <div class="control-group">
                                        <label class="control-label" for="text_reparation"> Réparation :</label>
                                        <div class="controls">
                                            <?php
                                            $attributes = array(
                                                'classic' => array(
                                                    'autocomplete' => 'off'
                                                    , 'rows' => 10
                                                )
                                                , 'custom' => array(
                                                    'id' => 'text_reparation'
                                                    , 'class' => 'span12 multilingual ckeditor'
                                                    , 'module' => 'Categories'
                                                    , 'name' => 'text_reparation'
                                                    , 'data' => $this->category
                                                )
                                            );
                                            Genius_Class_Forms::textareaMultilingual($attributes);
                                            Genius_Class_Ckeditor::initToggleCkeditor('text_reparation');
                                            ?>
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label" for="text_vente"> Vente & Echange :</label>
                                        <div class="controls">
                                            <?php
                                            $attributes = array(
                                                'classic' => array(
                                                    'autocomplete' => 'off'
                                                    , 'rows' => 10
                                                )
                                                , 'custom' => array(
                                                    'id' => 'text_vente'
                                                    , 'class' => 'span12 multilingual ckeditor'
                                                    , 'module' => 'Categories'
                                                    , 'name' => 'text_vente'
                                                    , 'data' => $this->category
                                                )
                                            );
                                            Genius_Class_Forms::textareaMultilingual($attributes);
                                            Genius_Class_Ckeditor::initToggleCkeditor('text_vente');
                                            ?>
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label" for="text_maintenance"> Maintenance :</label>
                                        <div class="controls">
                                            <?php
                                            $attributes = array(
                                                'classic' => array(
                                                    'autocomplete' => 'off'
                                                    , 'rows' => 10
                                                )
                                                , 'custom' => array(
                                                    'id' => 'text_maintenance'
                                                    , 'class' => 'span12 multilingual ckeditor'
                                                    , 'module' => 'Categories'
                                                    , 'name' => 'text_maintenance'
                                                    , 'data' => $this->category
                                                )
                                            );
                                            Genius_Class_Forms::textareaMultilingual($attributes);
                                            Genius_Class_Ckeditor::initToggleCkeditor('text_maintenance');
                                            ?>
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label" for="text_location"> Location :</label>
                                        <div class="controls">
                                            <?php
                                            $attributes = array(
                                                'classic' => array(
                                                    'autocomplete' => 'off'
                                                    , 'rows' => 10
                                                )
                                                , 'custom' => array(
                                                    'id' => 'text_location'
                                                    , 'class' => 'span12 multilingual ckeditor'
                                                    , 'module' => 'Categories'
                                                    , 'name' => 'text_location'
                                                    , 'data' => $this->category
                                                )
                                            );
                                            Genius_Class_Forms::textareaMultilingual($attributes);
                                            Genius_Class_Ckeditor::initToggleCkeditor('text_location');
                                            ?>
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label" for="text_audit"> Audit :</label>
                                        <div class="controls">
                                            <?php
                                            $attributes = array(
                                                'classic' => array(
                                                    'autocomplete' => 'off'
                                                    , 'rows' => 10
                                                )
                                                , 'custom' => array(
                                                    'id' => 'text_audit'
                                                    , 'class' => 'span12 multilingual ckeditor'
                                                    , 'module' => 'Categories'
                                                    , 'name' => 'text_audit'
                                                    , 'data' => $this->category
                                                )
                                            );
                                            Genius_Class_Forms::textareaMultilingual($attributes);
                                            Genius_Class_Ckeditor::initToggleCkeditor('text_audit');
                                            ?>
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label" for="text_reprise"> Reprise :</label>
                                        <div class="controls">
                                            <?php
                                            $attributes = array(
                                                'classic' => array(
                                                    'autocomplete' => 'off'
                                                    , 'rows' => 10
                                                )
                                                , 'custom' => array(
                                                    'id' => 'text_reprise'
                                                    , 'class' => 'span12 multilingual ckeditor'
                                                    , 'module' => 'Categories'
                                                    , 'name' => 'text_reprise'
                                                    , 'data' => $this->category
                                                )
                                            );
                                            Genius_Class_Forms::textareaMultilingual($attributes);
                                            Genius_Class_Ckeditor::initToggleCkeditor('text_reprise');
                                            ?>
                                        </div>
                                    </div>

                                <?php endif; ?>

                            </div>  




                        </div>  
                        <br><br>
                        <?php
                        if ($this->do == "edit") {
                            Genius_Class_Forms::multipleUpload(
                                    'file-uploader'
                                    , 'folder=categories&id_module=9&id_item=' . Genius_Class_Utils::idx($this->category, 'id', '')
                            );
                        }
                        ?>
                        <!-- Default Datatable -->
                        <div class="widget row-fluid">
                            <div class="table-overflow">
                                <table class="table table-striped table-bordered" id="data-table">
                                    <thead>
                                        <tr>
                                            <th width="80">Images</th>
                                            <th width="80">Couverture</th>
                                            <th>Name</th>
                                            <th>Caption</th>
                                            <th>Alt</th>
                                            <th class="acenter" width="10%">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td colspan="6" class="dataTables_empty">Loading data...</td>
                                        </tr>
                                    </tbody>
                                </table>

                                <script type="text/javascript">
                                    $(function () {
                                        $('#data-table').dataTable({
                                            "bJQueryUI": false,
                                            "bAutoWidth": false,
                                            "bProcessing": false,
                                            "bServerSide": true,
                                            "iDisplayLength": 5,
                                            "aLengthMenu": [
                                                [5, 10],
                                                [5, 10]
                                            ],
                                            "sAjaxSource": "/admin/upload/getimages/format/html?folder=categories&id_module=9&id_item=<?php echo Genius_Class_Utils::idx($this->category, 'id', ''); ?>",
                                            "sPaginationType": "full_numbers",
                                            "sDom": '<"datatable-header"Cfril>t<"datatable-footer"p>',
                                            "oLanguage": {
                                                "sSearch": "_INPUT_",
                                                "sLengthMenu": "<span>Show entries:</span> _MENU_",
                                                "oPaginate": {"sFirst": "First", "sLast": "Last", "sNext": ">", "sPrevious": "<"}
                                            },
                                            "aoColumns": [
                                                {"bSortable": false},
                                                {"bSortable": false},
                                                {"bSortable": true},
                                                {"bSortable": true},
                                                {"bSortable": true},
                                                {"bSortable": false},
                                            ],
                                            "fnDrawCallback": function (oSettings) {
                                                $("#data-table_wrapper .styled").uniform();
                                                $('#data-table_wrapper .tip').tooltip();
                                                $("#data-table_wrapper #checkAll").closest('.checker > span').removeClass('checked');
                                                $('#data-table_wrapper .dataTables_filter input').attr("placeholder", "Enter seach terms here...");
                                            }
                                        });

                                        $(".delete").live("click", function (e) {
                                            e.preventDefault();
                                            var id = $(this).attr('id');
                                            bootbox.confirm("Voulez-vous vraiment supprimer cet item?", function (confirmed) {
                                                if (confirmed) {
                                                    $.post("/admin/upload/delete"
                                                            , {
                                                                "id": id
                                                            },
                                                    function (data) {
                                                        table = $('#data-table').dataTable();
                                                        table.fnDraw();
                                                    }
                                                    , 'json'
                                                            );
                                                }
                                            });
                                        });

                                        $(".cover").live("click", function (e) {
                                            var id = $(this).attr('value');
                                            $.post("/admin/upload/changecover"
                                                    , {
                                                        "id": id
                                                        , "id_module": 9
                                                        , "id_item": "<?php echo Genius_Class_Utils::idx($this->category, 'id', ''); ?>"
                                                    },
                                            function (data) {
                                                table = $('#data-table').dataTable();
                                                table.fnDraw();
                                            }
                                            , 'json'
                                                    );
                                        });
                                    });
                                </script>
                            </div>
                        </div>
                        <!-- /Default Datatable -->                        
                        <?php Genius_Class_Forms::boxSeo('Categories', $this->category); ?>
                    </div><!-- end multilingual tabs -->
                </div>
            </div>

            <div class="line"></div>

            <div class="form-actions align-left nobordertop form-actions-bg">
                <button class="btn btn-primary" type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                <button type="button" class="btn btn-danger ml5" onclick="window.location.href = '/admin/categories'"><?php echo $this->translate("Retour"); ?></button>
            </div>

            <div class="line mb30"></div>
        </form>
    </div>

</div>
<!-- /content wrapper -->