<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
</head>

<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center" valign="top" bgcolor="#ffe77b" style="background-color:#FFFFFF;"><br>
    <br>
    <table width="600" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="70" align="left" valign="middle"><img src="<?php echo $this->host?>/themes/default/img/template/logo.png" width="141" style="display:block"></td>
      </tr>
      <tr>
        <td align="left" valign="top"><div style="width:100%; height:13px; background:#C0921A; border-radius:5px 5px 0 0"></div></td>
      </tr>
      <tr>
        <td align="left" valign="middle" bgcolor="#564319" style="background-color:#C0921A; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; padding:10px;"><div style="font-size:26px; color:#ffffff;"><b><?php echo $this->subject?></b></div>
          </td>
      </tr>
      <tr style="border-left:#963 solid 1px;border-right:#963 solid 1px;">
        <td align="left" valign="top" bgcolor="#ffffff" style="background-color:#fffff;border-left:#963 solid 1px;border-right:#963 solid 1px;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
          
        </table>
          <table width="95%" border="0" align="center" cellpadding="0" cellspacing="0">
            <tr>
              
              <td align="left" valign="middle" style="color:#525252; font-family:Arial, Helvetica, sans-serif; padding:10px;">
              <div style="font-size:16px; font-weight:bold"><?php echo $this->translate("Bienvenu")?> <?php echo $this->name?>, <?php echo $this->translate("Voici vos informations de connexion sur Lynxis")?> :</div>
              <div style="font-size:12px;">
              <p><?php echo $this->translate("Login")?> : <?php echo $this->login?></p>
              <p><?php echo $this->translate("Mot de passe")?> : <?php echo $this->pwd?></p>
              </div>
              </td>
            </tr>
          </table>
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="center" valign="middle" style="padding:5px;"><img src="<?php echo $this->host?>/newsletters/divider.gif" width="566" height="30"></td>
            </tr>
          </table>
          <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="margin-bottom:15px;">
            <tr>
              <td align="left" valign="middle" style="padding:15px; font-family:Arial, Helvetica, sans-serif;">
              <div style="font-size:20px; color:#564319;"><?php echo $this->translate("Pour activer votre compte, veuillez cliquer sur le lien ci-dessous")?> :</div>
              <div style="font-size:13px; color:#525252; margin-top:20px; font-weight:bold; text-align:center">
              	<a href="<?php echo $this->host?>/users/activate/hash/<?php echo $this->hash?>" style="color:#FFF; background:#F90; cursor:pointer; border:1px solid #CCC; text-decoration:none; padding:5px 2%;"><?php echo $this->translate("Confirmer votre adresse email")?></a>
              </div>
              </td>
            </tr>
          </table>
          <table width="100%" border="0" cellspacing="0" cellpadding="0" style="margin-bottom:10px;">
            <tr>
              <td align="left" valign="middle" style="padding:15px; background-color:#564319; font-family:Arial, Helvetica, sans-serif;"><div style="font-size:20px; color:#ffe77b;"><?php echo $this->translate("Qui sommes nous ?")?></div>
                <div style="font-size:13px; color:#ffe77b;"><?php echo $this->translate("Lynxis SA est un leader mondial de la négociation, la promotion et la gestion de biens immobiliers destinés à l’hôtellerie d’affaires de grand luxe et à des ensembles résidentiels situés dans des lieux d’exception")?><br>
                  <br>
                  <a href="http://lynxis.eu/page/quisommesnous" style="color:#ffe77b; text-decoration:underline;"><?php echo $this->translate("CLIQUER ICI")?></a> <?php echo $this->translate("POUR PLUS D'INFORMATIONS")?> </div></td>
            </tr>
          </table>
          <table width="95%" border="0" align="center" cellpadding="0" cellspacing="0">
            <tr>
              <td width="30%" align="left" valign="middle" style="padding:10px;"><table width="75%" border="0" cellspacing="0" cellpadding="4">
                <tr>
                  <td align="left" valign="top" style="font-family:Verdana, Geneva, sans-serif; font-size:14px; color:#000000;"><b><img src="<?php echo $this->host?>/themes/default/img/template/logo.png" width="141" style="display:block"></b></td>
                </tr>
                <tr>
                  <td align="left" valign="top" style="font-family:Verdana, Geneva, sans-serif; font-size:12px; color:#000000;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      
                    </tr>
                  </table></td>
                </tr>
              </table></td>
              <td width="80%" align="left" valign="middle" style="color:#564319; font-size:11px; font-family:Arial, Helvetica, sans-serif; padding:10px;">
                <b><?php echo $this->translate("Numéro d’entreprise")?>  :</b> B132669 <br>
                <b><?php echo $this->translate("Date de création")?>  :</b> 24 Octobre 2007<br>
                <b><?php echo $this->translate("Catégorie d’entreprise")?> :</b> Société anonyme<br>
                <b><?php echo $this->translate("Capital social")?> :</b> 2 millions d'euros<br>
                <b><?php echo $this->translate("Siège social")?> :</b>5, Allée John W. Leonard - L-7526 Mersch (Luxembourg)<br></td>
            </tr>
          </table></td>
      </tr>
      <tr>
        <td align="left" valign="top"><img src="<?php echo $this->host?>/newsletters/bot.png" width="600" height="37" style="display:block;"></td>
      </tr>
      </table>
    <br>
    <br></td>
  </tr>
</table>
</body>
</html>
