<?php
$menus = Genius_Model_Menu::getAllMenus();
?>
<!-- start subheader -->

<!-- start subheader -->

<section class="subHeader page" style="height:auto !important">
    <div class="container">
    	<h1>Blog Classic</h1>
    	<form class="searchForm" method="post" action="#">
            <input type="text" name="search" value="Search our site">
        </form>
    </div><!-- end subheader container -->
</section>
<!-- end subheader section --> 

<!-- start main content -->
<section class="properties">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 col-md-9">
        <div class="row">
          <div class="col-lg-12 col-md-12 col_blogPost">
			<?php $page = Genius_Model_Page::getPageById(23);?>
            <h1><?php echo $page['title_'.DEFAULT_LANG_ABBR];?> </h1>
            <div class="divider"></div>
            <div class="blogPost">
              <?php echo $page['text_'.DEFAULT_LANG_ABBR];?>
            </div>
          </div>
        </div>
        <!-- end row --> 
      </div>
      <!-- end col --> 
      
      <!-- START SIDEBAR -->
      <?php echo $this->render('statics/right_sidebar.phtml');?>
      <!-- end col --> 
      
    </div>
    <!-- end row --> 
  </div>
  <!-- end container --> 
</section>
<!-- end main content --> 

<!-- start widgets section -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div class="hbigline1">&nbsp;</div>
    </div>
  </div>
  <?php echo $this->render('statics/carousel.phtml');?>
</section>
