<?php $other_mark = Genius_Class_Prestations::othermark();?>
<section class="subHeader page">
  <div class="container">
  </div>
  <!-- end subheader container --> 
</section>
<section class="properties pad_300">
  <div class="container">
  <div class="page_title2">
  <div class="pagenation">
      <div class="padding-top">
         &nbsp;
        <a href="/">Home</a>
         <i>/</i><a href="/location"> <?php echo $this->translate("Location")?></a></i>
         <i>/</i><i><?php echo $this->marque['title_'.DEFAULT_LANG_ABBR]?> - <?php echo $this->group['title_'.DEFAULT_LANG_ABBR]?></i>
         </div>
		 <?php echo $this->render('statics/moteur_v1.phtml'); ?> 
   </div>
   </div>      
    <div class="row"> 
      
      <!-- start content -->
      <div class="col-lg-12 col-md-12">
        <div class="row">
          <div class="col-lg-4">
            <div class="gallery col-images">
             <img src="<?php echo $this->photocrh_cover_group; ?>" alt="" title=""/> 
             <?php if (!in_array($this->id_category,$other_mark)){?><div class="picto_marque_rep"><img src="<?php echo $this->photocrh_cover_marque; ?>" alt="" /></div><?php }?> 
             </div>
          </div>
          <div class="col-lg-8 section_catalogue">
            <div class="col-lg-12">
              <div class="section_text">
                <div class="col-lg-12 no_padding">
                  <h1 class="article"><?php echo $this->translate("Location")?> : <?php echo $this->marque['title_'.DEFAULT_LANG_ABBR]?> - <?php echo $this->group['title_'.DEFAULT_LANG_ABBR]?></h1>
                  <div class="spacer"></div>
                </div>
              </div>
              <p><?php echo $this->marque['text_location_'.DEFAULT_LANG_ABBR]?></p>
              <div class="align_right"> 
            	<?php if ($this->id_category_group == 27){?>
                <a href="/devis?id_product=&id_marque=&id_type=<?php echo $this->id_category?>&prest=4&id_product=<?php echo $this->id_product?>" class="fancybox buttonColor" style="display:inline-block;font-size:16px;"><?php echo $this->translate("DEMANDER UN DEVIS") ?></a>
                <?php }else{?>
            	<a href="/devis?id_product=&id_marque=<?php echo $this->marque['id']?>&id_type=&prest=4&id_product=<?php echo $this->id_product?>" class="fancybox buttonColor" style="display:inline-block;font-size:16px;"><?php echo $this->translate("DEMANDER UN DEVIS") ?></a>
                <?php }?>
                </div>
            </div>
          </div>
          
          <!-- end col --> 
        </div>
        <!-- end row --> 
      </div>
      <!-- end content --> 
    </div>
    <!-- end row --> 
    
  </div>
  <!-- end container --> 
</section>
<!-- end main content -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div>&nbsp;</div>
    </div>
  </div>
  <?php echo $this->render("statics/carousel.phtml");?>
</section>