<?php $other_mark = Genius_Class_Prestations::othermark();?>
<section class="subHeader page">
  <div class="container">
  </div>
  <!-- end subheader container --> 
</section>
<section class="properties pad_300">
  <div class="container">
    <div class="row"> 
      
      <!-- start content -->
      <div class="col-lg-12 col-md-12">
        <div class="row">
          <div class="col-lg-4">
            <div class="gallery col-images">
             <img src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/accessoires/accessoire3.jpg" alt="" title=""/> 
             <?php if (!in_array($this->id_category,$other_mark)){?><div class="picto_marque_rep"><img src="<?php echo THEMES_DEFAULT_URL; ?>images/marque/marque_0.png" alt="" /></div><?php }?> 
             </div>
          </div>
          <div class="col-lg-4 section_catalogue">
            <div class="col-lg-12">
              <div class="section_text">
                <div class="col-lg-12 no_padding">
                  <h2>EPSON TM-H6000III</h2>
                  <div class="spacer"></div>
                </div>
              </div>
              <p><strong>La EPSON TM-H6000III</strong> Imprimante industrielle milieu de gamme, compacte, débit rapide. La PF4i dispose d’une structure métallique renforcée. Idéale pour l’agroalimentaire et les milieux difficiles. Disponible en 203 ou 300dpi, connectiques : série, parallèle, USB, réseau et Wifi en option.</p>
              
            </div>
          </div>
          <div class="col-lg-4">
            <div class="col-lg-12 no_padding">
                 <h3 class="no_border" style="">Coupon réparation</h3>
                 <div class="divider" style="margin-top:0 !important;margin-bottom:15px !important;"></div>
                 <p>Ce coupon inclus une aide pour la réparation de votre installation GPL</p>
                 <ul class="liste_lab">
                   <li><strong>Référence :</strong> COUPKITAV</li>
                   <li><label><strong>Quantité : </strong></label><input type="text" name="qty" id="quantity_wanted" class="text" value="1" size="2" maxlength="3"></li>
                 </ul>
                <div class="align_right"> 
            	<a href="#" class="buttonColor" style="display:inline-block;font-size:16px;"><?php echo $this->translate("DEMANDER UN DEVIS") ?></a>
                </div>
            </div>
          </div>
          <!-- end col --> 
        </div>
        <!-- end row --> 
      </div>
      <!-- end content --> 
    </div>
    <!-- end row --> 
    
  </div>
  <!-- end container --> 
</section>
<!-- end main content -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div>&nbsp;</div>
    </div>
  </div>
  <div class="clients">
    <div class="container">
      <ul id="mycarouselthree" class="jcarousel-skin-tango">
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo1.png" alt="" /></li>
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo2.png" alt="" /></li>
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo3.png" alt="" /></li>
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo4.png" alt="" /></li>
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo5.png" alt="" /></li>
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo6.png" alt="" /></li>
        <li><img src="<?php echo THEMES_DEFAULT_URL; ?>images/client/client-logo7.png" alt="" /></li>
      </ul>
    </div>
  </div>
</section>
