<div class="container">

	<div class="content_fullwidth_eror">

	<div class="error_pagenotfound">
        <p><?php echo $this->translate("« Votre demande a bien été prise en compte.
Un conseiller commercial vous contactera très rapidement. »")?>.
        
        <div class="clearfix margin_top3"></div>
    	
        <a href="/" class="but_goback"><i class="fa fa-arrow-circle-left fa-lg"></i>&nbsp; <?php echo $this->translate("Retour sur le site")?></a>
        
    </div><!-- end error page notfound -->
        
</div>

</div>