<?php
$menus = Genius_Model_Menu::getAllMenus();
?>
<!-- start subheader -->

<!-- start subheader -->

<section class="subHeader page">
  <div class="container">
    <h1>Imprimante Thermiques</h1>
  </div>
  <!-- end subheader container --> 
</section>
<!-- end subheader section --> 

<!-- start recent properties -->
<section class="properties pad30">
  <div class="container">
    <div class="page_title2">
        <div class="pagenation">&nbsp;<a href="/">Home</a> <i>/</i> <a href="/">Imprimantes Thermiques</a><i>/</i>Toutes marques</div>
    </div>    
    <div class="divider" style="margin-top:0 !important"></div>
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">PETITS MODÈLES</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/GK420.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>PETITS MODÈLES</h4>
                <ul>
                    <li>
                      <a href="#" class="current">Zebra</a>
                        <ul>
                            <li><a>Zebra xx</a></li>
                            <li><a>Zebra xx2</a></li>
                            <li><a>Zebra xx3</a></li>
                            <li><a>Zebra xx4</a></li>
                            <li><a>Zebra xx5</a></li>
                            <li><a>Zebra xx6</a></li>
                            <li><a>Zebra xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Intermec</a>
                      <ul>
                            <li><a>Intermec xx</a></li>
                            <li><a>Intermec xx2</a></li>
                            <li><a>Intermec xx3</a></li>
                            <li><a>Intermec xx4</a></li>
                            <li><a>Intermec xx5</a></li>
                            <li><a>Intermec xx6</a></li>
                            <li><a>Intermec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                        <a>Tec</a>
                        <ul>
                            <li><a>Tec xx</a></li>
                            <li><a>Tec xx2</a></li>
                            <li><a>Tec xx3</a></li>
                            <li><a>Tec xx4</a></li>
                            <li><a>Tec xx5</a></li>
                            <li><a>Tec xx6</a></li>
                            <li><a>Tec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                     <a>Datamax</a>
                     <ul>
                            <li><a>Datamax xx</a></li>
                            <li><a>Datamax xx2</a></li>
                            <li><a>Datamax xx3</a></li>
                            <li><a>Datamax xx4</a></li>
                            <li><a>Datamax xx5</a></li>
                            <li><a>Datamax xx6</a></li>
                            <li><a>Datamax xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Autres marques</a>
                      <ul>
                            <li><a>Autres xx</a></li>
                            <li><a>Autres xx2</a></li>
                            <li><a>Autres xx3</a></li>
                            <li><a>Autres xx4</a></li>
                            <li><a>Autres xx5</a></li>
                            <li><a>Autres xx6</a></li>
                            <li><a>Autres xx7</a></li>
                        </ul>
                    </li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">milieu gamme</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/PF4I.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu">
             <h4>milieu gamme</h4>
                <ul>
                    <li>
                      <a href="#" class="current">Zebra</a>
                        <ul>
                            <li><a>Zebra xx</a></li>
                            <li><a>Zebra xx2</a></li>
                            <li><a>Zebra xx3</a></li>
                            <li><a>Zebra xx4</a></li>
                            <li><a>Zebra xx5</a></li>
                            <li><a>Zebra xx6</a></li>
                            <li><a>Zebra xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Intermec</a>
                      <ul>
                            <li><a>Intermec xx</a></li>
                            <li><a>Intermec xx2</a></li>
                            <li><a>Intermec xx3</a></li>
                            <li><a>Intermec xx4</a></li>
                            <li><a>Intermec xx5</a></li>
                            <li><a>Intermec xx6</a></li>
                            <li><a>Intermec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                        <a>Tec</a>
                        <ul>
                            <li><a>Tec xx</a></li>
                            <li><a>Tec xx2</a></li>
                            <li><a>Tec xx3</a></li>
                            <li><a>Tec xx4</a></li>
                            <li><a>Tec xx5</a></li>
                            <li><a>Tec xx6</a></li>
                            <li><a>Tec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                     <a>Datamax</a>
                     <ul>
                            <li><a>Datamax xx</a></li>
                            <li><a>Datamax xx2</a></li>
                            <li><a>Datamax xx3</a></li>
                            <li><a>Datamax xx4</a></li>
                            <li><a>Datamax xx5</a></li>
                            <li><a>Datamax xx6</a></li>
                            <li><a>Datamax xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Autres marques</a>
                      <ul>
                            <li><a>Autres xx</a></li>
                            <li><a>Autres xx2</a></li>
                            <li><a>Autres xx3</a></li>
                            <li><a>Autres xx4</a></li>
                            <li><a>Autres xx5</a></li>
                            <li><a>Autres xx6</a></li>
                            <li><a>Autres xx7</a></li>
                        </ul>
                    </li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">gros volumes</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/170xi3.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu">
             <h4>gros volumes</h4>
                <ul>
                    <li>
                      <a href="#" class="current">Zebra</a>
                        <ul>
                            <li><a>Zebra xx</a></li>
                            <li><a>Zebra xx2</a></li>
                            <li><a>Zebra xx3</a></li>
                            <li><a>Zebra xx4</a></li>
                            <li><a>Zebra xx5</a></li>
                            <li><a>Zebra xx6</a></li>
                            <li><a>Zebra xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Intermec</a>
                      <ul>
                            <li><a>Intermec xx</a></li>
                            <li><a>Intermec xx2</a></li>
                            <li><a>Intermec xx3</a></li>
                            <li><a>Intermec xx4</a></li>
                            <li><a>Intermec xx5</a></li>
                            <li><a>Intermec xx6</a></li>
                            <li><a>Intermec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                        <a>Tec</a>
                        <ul>
                            <li><a>Tec xx</a></li>
                            <li><a>Tec xx2</a></li>
                            <li><a>Tec xx3</a></li>
                            <li><a>Tec xx4</a></li>
                            <li><a>Tec xx5</a></li>
                            <li><a>Tec xx6</a></li>
                            <li><a>Tec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                     <a>Datamax</a>
                     <ul>
                            <li><a>Datamax xx</a></li>
                            <li><a>Datamax xx2</a></li>
                            <li><a>Datamax xx3</a></li>
                            <li><a>Datamax xx4</a></li>
                            <li><a>Datamax xx5</a></li>
                            <li><a>Datamax xx6</a></li>
                            <li><a>Datamax xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Autres marques</a>
                      <ul>
                            <li><a>Autres xx</a></li>
                            <li><a>Autres xx2</a></li>
                            <li><a>Autres xx3</a></li>
                            <li><a>Autres xx4</a></li>
                            <li><a>Autres xx5</a></li>
                            <li><a>Autres xx6</a></li>
                            <li><a>Autres xx7</a></li>
                        </ul>
                    </li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> 
          <a class="propertyType" href="#">imprimantes mobiles</a> 
          <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/QL420.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu">
             <h4>imprimantes mobiles</h4>
                <ul>
                    <li>
                      <a href="#" class="current">Zebra</a>
                        <ul>
                            <li><a>Zebra xx</a></li>
                            <li><a>Zebra xx2</a></li>
                            <li><a>Zebra xx3</a></li>
                            <li><a>Zebra xx4</a></li>
                            <li><a>Zebra xx5</a></li>
                            <li><a>Zebra xx6</a></li>
                            <li><a>Zebra xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Intermec</a>
                      <ul>
                            <li><a>Intermec xx</a></li>
                            <li><a>Intermec xx2</a></li>
                            <li><a>Intermec xx3</a></li>
                            <li><a>Intermec xx4</a></li>
                            <li><a>Intermec xx5</a></li>
                            <li><a>Intermec xx6</a></li>
                            <li><a>Intermec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                        <a>Tec</a>
                        <ul>
                            <li><a>Tec xx</a></li>
                            <li><a>Tec xx2</a></li>
                            <li><a>Tec xx3</a></li>
                            <li><a>Tec xx4</a></li>
                            <li><a>Tec xx5</a></li>
                            <li><a>Tec xx6</a></li>
                            <li><a>Tec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                     <a>Datamax</a>
                     <ul>
                            <li><a>Datamax xx</a></li>
                            <li><a>Datamax xx2</a></li>
                            <li><a>Datamax xx3</a></li>
                            <li><a>Datamax xx4</a></li>
                            <li><a>Datamax xx5</a></li>
                            <li><a>Datamax xx6</a></li>
                            <li><a>Datamax xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Autres marques</a>
                      <ul>
                            <li><a>Autres xx</a></li>
                            <li><a>Autres xx2</a></li>
                            <li><a>Autres xx3</a></li>
                            <li><a>Autres xx4</a></li>
                            <li><a>Autres xx5</a></li>
                            <li><a>Autres xx6</a></li>
                            <li><a>Autres xx7</a></li>
                        </ul>
                    </li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">imprimantes badge</a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/imprimante_badge.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>imprimantes badge</h4>
                <ul>
                    <li>
                      <a href="#" class="current">Zebra</a>
                        <ul>
                            <li><a>Zebra xx</a></li>
                            <li><a>Zebra xx2</a></li>
                            <li><a>Zebra xx3</a></li>
                            <li><a>Zebra xx4</a></li>
                            <li><a>Zebra xx5</a></li>
                            <li><a>Zebra xx6</a></li>
                            <li><a>Zebra xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Intermec</a>
                      <ul>
                            <li><a>Intermec xx</a></li>
                            <li><a>Intermec xx2</a></li>
                            <li><a>Intermec xx3</a></li>
                            <li><a>Intermec xx4</a></li>
                            <li><a>Intermec xx5</a></li>
                            <li><a>Intermec xx6</a></li>
                            <li><a>Intermec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                        <a>Tec</a>
                        <ul>
                            <li><a>Tec xx</a></li>
                            <li><a>Tec xx2</a></li>
                            <li><a>Tec xx3</a></li>
                            <li><a>Tec xx4</a></li>
                            <li><a>Tec xx5</a></li>
                            <li><a>Tec xx6</a></li>
                            <li><a>Tec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                     <a>Datamax</a>
                     <ul>
                            <li><a>Datamax xx</a></li>
                            <li><a>Datamax xx2</a></li>
                            <li><a>Datamax xx3</a></li>
                            <li><a>Datamax xx4</a></li>
                            <li><a>Datamax xx5</a></li>
                            <li><a>Datamax xx6</a></li>
                            <li><a>Datamax xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Autres marques</a>
                      <ul>
                            <li><a>Autres xx</a></li>
                            <li><a>Autres xx2</a></li>
                            <li><a>Autres xx3</a></li>
                            <li><a>Autres xx4</a></li>
                            <li><a>Autres xx5</a></li>
                            <li><a>Autres xx6</a></li>
                            <li><a>Autres xx7</a></li>
                        </ul>
                    </li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">imprimante couleur</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/epson.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu">
             <h4>imprimante couleur</h4>
                <ul>
                    <li>
                      <a href="#" class="current">Zebra</a>
                        <ul>
                            <li><a>Zebra xx</a></li>
                            <li><a>Zebra xx2</a></li>
                            <li><a>Zebra xx3</a></li>
                            <li><a>Zebra xx4</a></li>
                            <li><a>Zebra xx5</a></li>
                            <li><a>Zebra xx6</a></li>
                            <li><a>Zebra xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Intermec</a>
                      <ul>
                            <li><a>Intermec xx</a></li>
                            <li><a>Intermec xx2</a></li>
                            <li><a>Intermec xx3</a></li>
                            <li><a>Intermec xx4</a></li>
                            <li><a>Intermec xx5</a></li>
                            <li><a>Intermec xx6</a></li>
                            <li><a>Intermec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                        <a>Tec</a>
                        <ul>
                            <li><a>Tec xx</a></li>
                            <li><a>Tec xx2</a></li>
                            <li><a>Tec xx3</a></li>
                            <li><a>Tec xx4</a></li>
                            <li><a>Tec xx5</a></li>
                            <li><a>Tec xx6</a></li>
                            <li><a>Tec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                     <a>Datamax</a>
                     <ul>
                            <li><a>Datamax xx</a></li>
                            <li><a>Datamax xx2</a></li>
                            <li><a>Datamax xx3</a></li>
                            <li><a>Datamax xx4</a></li>
                            <li><a>Datamax xx5</a></li>
                            <li><a>Datamax xx6</a></li>
                            <li><a>Datamax xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Autres marques</a>
                      <ul>
                            <li><a>Autres xx</a></li>
                            <li><a>Autres xx2</a></li>
                            <li><a>Autres xx3</a></li>
                            <li><a>Autres xx4</a></li>
                            <li><a>Autres xx5</a></li>
                            <li><a>Autres xx6</a></li>
                            <li><a>Autres xx7</a></li>
                        </ul>
                    </li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a class="propertyType" href="#">accessoires & produits associes</a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/pieces.jpg" alt="" /></a> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a class="propertyType" href="#">Reparation et services</a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/reparation.jpg" alt="" /></a>

          </div>
        </div>
      </div>
    </div>
    <!-- end row -->
    <div class="spacer"></div>
  </div>
  <!-- end container --> 
</section>
<!-- end recent properties --> 

<!-- start widgets section -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div class="hbigline1">&nbsp;</div>
    </div>
  </div>
  <?php echo $this->render('statics/carousel.phtml');?>
</section>
