<?php
$menus = Genius_Model_Menu::getAllMenus();
$seo = new Genius_Class_Seo();
?>
<!-- start subheader -->

<!-- start subheader -->

<section class="subHeader page">
  <div class="container">
    <h1><?php echo $this->translate("Imprimantes - Toutes marques")?></h1>
  </div>
  <!-- end subheader container --> 
</section>
<!-- end subheader section --> 

<!-- start recent properties -->
<section class="properties pad30">
  <div class="container">
    <div class="page_title2">
        <div class="pagenation">&nbsp;<a href="/" style="font-size:18px;font-weight:bold;color:#38B1FF;">Home</a><i>/</i><i style="font-size:18px;font-weight:bold;color:#38B1FF;"><?php echo $this->translate("Imprimantes")?></i>
        <?php echo $this->render('statics/moteur_v1.phtml'); ?>
        </div>
    </div>    
    <div class="divider" style="margin-top:0 !important"></div>
	  <div class="row" id="banniere">
	  	<img src="<?php echo UPLOAD_URL?>images/multimedias/banniere_imprimante.jpg" width="1010" height="235">
	  </div>
	<div class="divider" style="margin-top:0 !important"></div> 
    <div class="row">
      <?php 
	  $groups = Genius_Model_Module::getCategoryGroupByModule(11); 
	  foreach ($groups as $group):
	  $id_type = Genius_Model_Group::getIdTypeGroup($group['id_category_group']);
	  $types   = Genius_Model_Category::getCategoryBox($id_type);	
	  $id_marque = Genius_Model_Group::getIdMarqueGroup($group['id_category_group']);
	  $marques = Genius_Model_Category::getCategoryBox($id_marque);
	  
	  $photocover = Genius_Model_Group::getGroupImageCoverById($group['id_category_group']);
	  $ppath = (!empty($photocover)) ? $photocover['path_folder'].'/'.$photocover['filename'].'-cover-'.$photocover['id_image'].'.'.$photocover['format'] : '';

	  $photocrh_cover = THEMES_DEFAULT_URL . 'images/non_dispo.png';
	  if(file_exists(UPLOAD_PATH.'images/'.$ppath) && is_file(UPLOAD_PATH.'images/'.$ppath)){
		  $photocrh_cover = UPLOAD_URL . 'images/' . $ppath;
	  }
	   if ($group['id_category_group'] != 36){
	  ?>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem  uniform_height">
          <div class="propertyContent"> <a class="propertyType color_imprimantes"><?php echo $group['title']?></a> <a class="propertyImgLink"  href="<?php echo $seo->getLinkGroup(11,$group['id_category_group'],0);?>"><img class="propertyImg" src="<?php echo $photocrh_cover; ?>" alt="" /></a>
          <!--Sous Menu Bloc-->
           <?php if(1==2){?>
            <div class="box_menu box_menu_left">
             <h4><?php echo $group['title']?></a></h4>
                <ul>
                    <li><a title="<?php echo $this->translate("Toutes marques")?>" href="<?php echo $seo->getLinkGroup(10,$group['id_category_group'],$marque['id_category']);?>" class="current"><?php echo $this->translate("Toutes marques")?></a> </li>
                    <?php
					foreach ($marques['categories_list'] as $marque):
                    ?>
                    <li>
                      <a title="<?php echo $marque['title']?>" href="<?php echo $seo->getLinkGroupMarque(10,$group['id_category_group'],$marque['id_category']);?>"><?php echo $marque['title']?></a>
                    </li>
                    <?php
                    endforeach;
					?>
                </ul>         
            </div>
            <?php }?>
            <ul class="list-group view_marque">
               <li><a title="<?php echo $this->translate("Toutes marques")?>" href="<?php echo $seo->getLinkGroup(11,$group['id_category_group'],0);?>" class="current"> &raquo;&nbsp;&nbsp;&nbsp;<?php echo $this->translate("Toutes marques")?></a> </li>
			   <?php
                  foreach ($marques['categories_list'] as $marque):
                  ?>
                  <li class="list-group-item">
                    <a title="<?php echo $marque['title']?>" href="<?php echo $seo->getLinkGroupMarque(11,$group['id_category_group'],$marque['id_category']);?>"> &raquo;&nbsp;&nbsp;&nbsp;<?php echo $marque['title']?></a>
                  </li>
                  <?php
                  endforeach;
                  ?>
            </ul>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <?php
	   }else{
	  ?>	
	  <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem  uniform_height">
          <div class="propertyContent"> <a class="propertyType color_imprimantes"><?php echo $group['title']?></a> <a class="propertyImgLink"  href="<?php echo $seo->getLinkGroup(11,$group['id_category_group'],$marque['id_category']);?>"><img class="propertyImg" src="<?php echo $photocrh_cover; ?>" alt="" /></a>
          <!--Sous Menu Bloc-->
            <ul class="list-group view_marque">
               <li><a title="<?php echo $this->translate("Tous les accessoires")?>" href="<?php echo $seo->getLinkGroup(11,$group['id_category_group'],$marque['id_category']);?>" class="current"> &raquo;&nbsp;&nbsp;&nbsp;<?php echo $this->translate("Tous les accessoires")?></a> </li>
			   <?php
		 
		       foreach ($types['categories_list'] as $kt => $type):
		         $products = Genius_Model_Product::getProductsWithinCategories(array($type['id_category']));
                 $ids_products = array();
                            if (!empty($products)) {

                                foreach ($products as $kp => $pro) {
                                    $ids_products[] = $pro['id_product'];
                                }
                            }
		         $marques_products = Genius_Model_Product::getProductsMarques($group['id_category_group'], $ids_products);
		           if (!empty($marques_products)) {
                                        foreach ($marques_products as $kmp => $marque) {
                                            $products = Genius_Model_Product::getProductsByCategoryIds($marque['id_category'], $type['id_category']);
                                            if (count($products) > 0) {
                                                foreach ($products as $kp => $product) {
                  ?>
                  <li class="list-group-item">
                    <a title="<?php echo $product['title']; ?>" href="<?php echo $seo->getLinkProduct($product['id_product']); ?>"> &raquo;&nbsp;&nbsp;&nbsp;<?php echo $product['title']; ?></a>
                  </li>
                  <?php }
                                            }
                                        }
                                    }
                  endforeach;
                  ?>
            </ul>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>   
	  <?php	   
	   }
      endforeach;
	  ?>
    </div>
    
    <div class="row desc_rubrique">
    	<?php 
		$menus = Genius_Class_Seo::getMetasMenu(4);
		echo $menus['text'];
		?>
    </div>
    <!-- end row -->
    <div class="spacer"></div>
  </div>
  <!-- end container --> 
</section>
<!-- end recent properties --> 

<!-- start widgets section -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div class="hbigline1">&nbsp;</div>
    </div>
  </div>
  <?php echo $this->render('statics/carousel.phtml');?>
</section>
<style>
ul.view_marque{
	margin-top:10px;
}
ul.view_marque li{
	padding: 5px 15px 5px 5px!important;
	border: none!important;
}
ul.view_marque li:hover{
	background: #efefef;
	}
ul.view_marque li a:visited{
	text-decoration: none;
	}
ul.view_marque li a{
	color:#686868;
	font-size: 13px;
}
.uniform_height{
	height:450px!important;
}
.color_imprimantes{
	background:#38B1FF!important;
	width: 100%;
	font-size:11px;
    display: block;
	text-align: center;
    position: inherit!important;
	margin-bottom: 10px;
  font-family: sans-serif!important;
}
	#banniere{margin:0px auto;}
	#banniere img{
		width:100%;
		height:auto;
	}
</style>
