<section class="subHeader page">
  <div class="container">
    
  </div>
</section> 

<!-- start recent properties -->
<section class="properties pad30">
  <div class="container">
    <div class="page_title2">
        <div class="pagenation">&nbsp;<a href="/">Home</a> <i>/</i><?php echo $this->translate("Marques")?>
        <?php echo $this->render('statics/moteur_v1.phtml'); ?>
        </div>
    </div>
    
    
    <div class="row feature_section1">
                    <div class="col-lg-2b col-md-2d col-sm-2d one_fourth color_0"> 
                        <a href="/marque/tracabilite" title="<?php echo $this->translate("TRACABILITE")?>">
                            <div class="arrow_box"><i class="fa_bloc"></i></div>
                            <h5 class="caps"><?php echo $this->translate("TRACABILITE")?></h5>
                        </a> 
                    </div>
                    <div class="col-lg-2b col-md-2d col-sm-2d one_fourth color_1"> 
                        <a href="/marque/imprimantes" title="<?php echo $this->translate("IMPRIMANTES")?>">
                            <div class="arrow_box"><i class="fa_bloc"></i></div>
                            <h5 class="caps"><?php echo $this->translate("IMPRIMANTES")?></h5>
                        </a> 
                    </div>
                    <div class="col-lg-2b col-md-2d col-sm-2d one_fourth color_2"> 
                        <a href="/marque/micro" title="<?php echo $this->translate("MICRO")?>">
                            <div class="arrow_box"><i class="fa_bloc"></i></div>
                            <h5 class="caps"><?php echo $this->translate("MICRO")?></h5>
                        </a> 
                    </div>
        </div> 
         <div class="row desc_rubrique">
         
    	<?php 
		$menus = Genius_Class_Seo::getMetasMenu(7);
		echo "<h1>".$menus['title']."</h1>";
		echo $menus['text'];
		?>
    </div>
    <!-- end row -->
    <div class="spacer"></div>
  </div>
  <!-- end container --> 
</section>
<!-- end recent properties --> 

<!-- start widgets section -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div class="hbigline1">&nbsp;</div>
    </div>
  </div>
  <?php echo $this->render('statics/carousel.phtml');?>
</section>
