<section class="subHeader page">
  <div class="container">
    <h1>Toutes marques</h1>
  </div>
</section> 

<!-- start recent properties -->
<section class="properties pad30">
  <div class="container">
    <div class="page_title2">
        <div class="pagenation">&nbsp;<a href="/">Home</a> <i>/</i><?php echo $this->translate("Marques")?></div>
    </div>
    
    
    <div class="row feature_section1">
                    <div class="col-lg-2b col-md-2d col-sm-2d one_fourth color_0"> 
                        <a href="/marquepartenaires/tracabilite" title="<?php echo $this->translate("TRACABILITE")?>">
                            <div class="arrow_box"><i class="fa_bloc"></i></div>
                            <h5 class="caps"><?php echo $this->translate("TRACABILITE")?></h5>
                        </a> 
                    </div>
                    <div class="col-lg-2b col-md-2d col-sm-2d one_fourth color_1"> 
                        <a href="/marquepartenaires/imprimantes" title="<?php echo $this->translate("IMPRIMANTES")?>">
                            <div class="arrow_box"><i class="fa_bloc"></i></div>
                            <h5 class="caps"><?php echo $this->translate("IMPRIMANTES")?></h5>
                        </a> 
                    </div>
                    <div class="col-lg-2b col-md-2d col-sm-2d one_fourth color_2"> 
                        <a href="/marquepartenaires/micro" title="<?php echo $this->translate("MICRO")?>">
                            <div class="arrow_box"><i class="fa_bloc"></i></div>
                            <h5 class="caps"><?php echo $this->translate("MICRO")?></h5>
                        </a> 
                    </div>
        </div> 
        
           
    <!--<div class="divider" style="margin-top:0 !important"></div>
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem" style="background:#BD56B5 !important">
          <div class="propertyContent"> <a title="<?php echo $this->translate("TRACABILITE")?>" class="propertyType" href="/marquepartenaires/tracabilite" style="top: 17%;left: 28%;font-size: 18px;color:#FFF !important;background:none !important"><img src="<?php echo THEMES_DEFAULT_URL; ?>images/menu/menu1.png" style="display:block;margin: 5px auto;" /><?php echo $this->translate("TRACABILITE")?></a> <a style="top: 31%;left: 28%;font-size: 18px;color:#333333 !important;background:none !important" title="<?php echo $this->translate("TRACABILITE")?>" href="/marquepartenaires/tracabilite" class="propertyImgLink"></a>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem" style="background:#00CAFF !important">
          <div class="propertyContent"> <a style="top: 17%;left: 28%;font-size: 18px;color:#FFF !important;background:none !important" title="<?php echo $this->translate("IMPRIMANTES")?>" class="propertyType" href="/marquepartenaires/imprimantes"><img src="<?php echo THEMES_DEFAULT_URL; ?>images/menu/menu2.png" style="display:block;margin: 5px auto;" /><?php echo $this->translate("IMPRIMANTES")?></a> <a  style="top: 31%;left: 28%;font-size: 18px;color:#333333 !important;background:none !important" title="<?php echo $this->translate("IMPRIMANTES")?>" href="/marquepartenaires/imprimantes" class="propertyImgLink"></a>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem" style="background:#004FAE !important">
          <div class="propertyContent"> <a  style="top: 17%;left: 36%;font-size: 18px;color:#FFF !important;background:none !important" title="<?php echo $this->translate("MICRO")?>" class="propertyType" href="/marquepartenaires/micro"><img src="<?php echo THEMES_DEFAULT_URL; ?>images/menu/menu3.png" style="display:block;margin: 5px auto;" /><?php echo $this->translate("MICRO")?></a> <a style="top: 31%;left: 36%;font-size: 18px;color:#333333 !important;background:none !important" title="<?php echo $this->translate("MICRO")?> "href="/marquepartenaires/micro" class="propertyImgLink"></a>
          </div>
        </div>
      </div>
    </div>-->
    <!-- end row -->
    <div class="spacer"></div>
  </div>
  <!-- end container --> 
</section>
<!-- end recent properties --> 

<!-- start widgets section -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div class="hbigline1">&nbsp;</div>
    </div>
  </div>
  <?php echo $this->render('statics/carousel.phtml');?>
</section>
