<?php
$menus = Genius_Model_Menu::getAllMenus();
?>
<!-- start subheader -->

<!-- start subheader -->

<section class="subHeader page">
  <div class="container">
    <h1>Toutes marques</h1>
  </div>
  <!-- end subheader container --> 
</section>
<!-- end subheader section --> 

<!-- start recent properties -->
<section class="properties pad30">
  <div class="container">
    <div class="page_title2">
        <div class="pagenation">&nbsp;<a href="/">Home</a> <i>/</i> <a href="/">Reparation & services</a><i>/</i>Reparation</div>
    </div>    
    <div class="divider" style="margin-top:0 !important"></div>
    <div class="row">
      <div class="col-lg-12 col-md-6 col-sm-6 texte_reparation">
        <p>Découvrez en images le leader européen du matériel reconditionné, spécialiste des équipements code-barres, TPV et TPE. Notre coeur de métier est la Reprise d’anciens équipements et la Vente de matériel reconditionné. Nous proposons également la location de terminaux d’inventaire, et de la maintenance de parc. Nous proposons également la location de terminaux d’inventaire, et de la maintenance de parc.
</p>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">Imprimantes thermiques</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/GK420.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>Imprimantes thermiques</h4>
                <ul>
                    <li>
                      <a href="/fiche" class="current">Zebra</a>
                    </li>
                    <li>
                      <a href="/fiche" >Intermec</a>
                    </li>
                    <li>
                        <a href="/fiche" >Tec</a>
                    </li>
                    <li>
                     <a href="/fiche" >Datamax</a>
                    </li>
                    <li>
                      <a href="/fiche" >Autres marques</a>
                    </li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">Terminaux mobiles</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/PF4I.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>Terminaux mobiles</h4>
                <ul>
                    <li>
                      <a href="/fiche"  class="current">Motorola / Symbol</a>
                    </li>
                    <li>
                      <a href="/fiche" >Psion / Teklogix</a>
                    </li>
                    <li>
                        <a href="/fiche" >Intermec / Honeywell / LXE</a>
                    </li>
                    <li>
                     <a href="/fiche" >Datalogic</a>
                    </li>
                    
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">Laser</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/170xi3.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>Laser</h4>
                <ul>
                    <li>
                      <a href="/fiche" class="current">HP</a>
                    </li>
                    <li>
                      <a href="/fiche" >Lexmark</a>
                    </li>
                    <li>
                        <a href="/fiche" >Epson</a>
                    </li>
                    <li>
                     <a href="/fiche" >Autres marques</a>
                    </li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> 
          <a class="propertyType" href="#">matricielle</a> 
          <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/QL420.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>matricielle</h4>
                <ul>
                    <li>
                      <a href="/fiche"  class="current">Lexmark</a>
                    </li>
                    <li>
                      <a href="/fiche" >IBM</a>
                    </li>
                    <li>
                        <a href="/fiche" >Epson</a>
                    </li>
                    <li>
                     <a href="/fiche" >Oki</a>
                    </li>
                    
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">Micro</a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/imprimante_badge.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>Micro</h4>
                <ul>
                    <li>
                      <a href="/fiche" class="current">PC</a>
                        
                    </li>
                    <li>
                      <a href="/fiche" >Portable</a>
                      
                    </li>
                    <li>
                        <a href="/fiche" >Serveurs</a>
                        
                    </li>
                    
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
    </div>
    <!-- end row -->
    <div class="spacer"></div>
  </div>
  <!-- end container --> 
</section>
<!-- end recent properties --> 

<!-- start widgets section -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div class="hbigline1">&nbsp;</div>
    </div>
  </div>
  <?php echo $this->render('statics/carousel.phtml');?>
</section>
