<?php
$menus = Genius_Model_Menu::getAllMenus();
?>
<!-- start subheader -->

<!-- start subheader -->

<section class="subHeader page">
  <div class="container">
    <h1>Imprimantes thermiques Zebra</h1>
  </div>
  <!-- end subheader container --> 
</section>
<!-- end subheader section --> 

<!-- start recent properties -->
<section class="properties">
  <div class="container">
    <div class="page_title2">
        <div class="pagenation">&nbsp;<a href="/">Home</a> <i>/</i> <a href="/page">Imprimantes Thermiques</a> <i>/</i> Zebra</div>
    </div>
    <h3>Petit modèle</h3>
    <div class="divider"></div>
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/GK420.jpg" alt="" /></a>
            <h4><a href="property_single.html">GK420</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/PF4I.jpg" alt="" /></a>
            <h4><a href="property_single.html">GX420</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/170xi3.jpg" alt="" /></a>
            <h4><a href="property_single.html">GX430</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/QL420.jpg" alt="" /></a>
            <h4><a href="property_single.html">LP/TLP2844 – LP2824 </a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/epson.jpg" alt="" /></a>
            <h4><a href="property_single.html">PD41</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/imprimante_badge.jpg" alt="" /></a>
            <h4><a href="property_single.html">PD42 </a></h4>
          </div>
        </div>
      </div>
    </div>
    <!-- end row -->
    <h3>Milieu gamme</h3>
    <div class="divider"></div>
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/GK420.jpg" alt="" /></a>
            <h4><a href="property_single.html">GK420</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/PF4I.jpg" alt="" /></a>
            <h4><a href="property_single.html">GX420</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/170xi3.jpg" alt="" /></a>
            <h4><a href="property_single.html">GX430</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/QL420.jpg" alt="" /></a>
            <h4><a href="property_single.html">LP/TLP2844 – LP2824 </a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/epson.jpg" alt="" /></a>
            <h4><a href="property_single.html">PD41</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/imprimante_badge.jpg" alt="" /></a>
            <h4><a href="property_single.html">PD42 </a></h4>
          </div>
        </div>
      </div>
    </div>
    <!-- end row -->
    <h3>Modèle industriel / haut gamme </h3>
    <div class="divider"></div>
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/GK420.jpg" alt="" /></a>
            <h4><a href="property_single.html">GK420</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/PF4I.jpg" alt="" /></a>
            <h4><a href="property_single.html">GX420</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/170xi3.jpg" alt="" /></a>
            <h4><a href="property_single.html">GX430</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/QL420.jpg" alt="" /></a>
            <h4><a href="property_single.html">LP/TLP2844 – LP2824 </a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/epson.jpg" alt="" /></a>
            <h4><a href="property_single.html">PD41</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/imprimante_badge.jpg" alt="" /></a>
            <h4><a href="property_single.html">PD42 </a></h4>
          </div>
        </div>
      </div>
    </div>
    <!-- end row -->
     <h3>Modèle industriel / haut gamme </h3>
    <div class="divider"></div>
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/GK420.jpg" alt="" /></a>
            <h4><a href="property_single.html">GK420</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/PF4I.jpg" alt="" /></a>
            <h4><a href="property_single.html">GX420</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/170xi3.jpg" alt="" /></a>
            <h4><a href="property_single.html">GX430</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/QL420.jpg" alt="" /></a>
            <h4><a href="property_single.html">LP/TLP2844 – LP2824 </a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/epson.jpg" alt="" /></a>
            <h4><a href="property_single.html">PD41</a></h4>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a href="property_single.html" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/imprimante_badge.jpg" alt="" /></a>
            <h4><a href="property_single.html">PD42 </a></h4>
          </div>
        </div>
      </div>
    </div>
    <!-- end row -->
    <div class="spacer"></div>
  </div>
  <!-- end container --> 
</section>
<!-- end recent properties --> 

<!-- start widgets section -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div class="hbigline1">&nbsp;</div>
    </div>
  </div>
  <?php echo $this->render('statics/carousel.phtml');?>
</section>
