<?php
$menus = Genius_Model_Menu::getAllMenus();
?>
<!-- start subheader -->

<!-- start subheader -->

<section class="subHeader page">
  <div class="container">
    <h1>Imprimantes Thermiques </h1>
  </div>
  <!-- end subheader container --> 
</section>
<!-- end subheader section --> 

<!-- start recent properties -->
<section class="properties pad30">
  <div class="container">
    <div class="page_title2">
        <div class="pagenation">&nbsp;<a href="/">Home</a> <i>/</i> <a href="/">Imprimantes Thermiques</a><i>/</i>Zebra</div>
    </div>    
    <div class="divider" style="margin-top:0 !important"></div>
    <div class="row">
     <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">PETITS MODÈLES</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/GK420.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>PETITS MODÈLES</h4>
            <ul>
                <li><a>PETITS MODÈLES Zebra xx</a></li>
                <li><a>PETITS MODÈLES Zebra xx2</a></li>
                <li><a>PETITS MODÈLES Zebra xx3</a></li>
                <li><a>PETITS MODÈLES Zebra xx4</a></li>
                <li><a>PETITS MODÈLES Zebra xx5</a></li>
                <li><a>PETITS MODÈLES Zebra xx6</a></li>
                <li><a>PETITS MODÈLES Zebra xx7</a></li>
            </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">milieu gamme</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/PF4I.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>MILIEU GAMME</h4>
              <ul>
                <li><a>MILIEU GAMME Zebra xx</a></li>
                <li><a>MILIEU GAMME Zebra xx2</a></li>
                <li><a>MILIEU GAMME Zebra xx3</a></li>
                <li><a>MILIEU GAMME Zebra xx4</a></li>
                <li><a>MILIEU GAMME Zebra xx5</a></li>
                <li><a>MILIEU GAMME Zebra xx6</a></li>
                <li><a>MILIEU GAMME Zebra xx7</a></li>
            </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">gros volumes</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/170xi3.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>GROS VOLUMES</h4>
             <ul>
                <li><a>GROS VOLUMES Zebra xx</a></li>
                <li><a>GROS VOLUMES Zebra xx2</a></li>
                <li><a>GROS VOLUMES Zebra xx3</a></li>
                <li><a>GROS VOLUMES Zebra xx4</a></li>
                <li><a>GROS VOLUMES Zebra xx5</a></li>
                <li><a>GROS VOLUMES Zebra xx6</a></li>
                <li><a>GROS VOLUMES Zebra xx7</a></li>
            </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> 
          <a class="propertyType" href="#">imprimantes mobiles</a> 
          <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/QL420.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>IMPRIMANTES MOBILES</h4>
              <ul>
                <li><a>IMPRIMANTES MOBILES Zebra xx</a></li>
                <li><a>IMPRIMANTES MOBILES Zebra xx2</a></li>
                <li><a>IMPRIMANTES MOBILES Zebra xx3</a></li>
                <li><a>IMPRIMANTES MOBILES Zebra xx4</a></li>
                <li><a>IMPRIMANTES MOBILES Zebra xx5</a></li>
                <li><a>IMPRIMANTES MOBILES Zebra xx6</a></li>
                <li><a>IMPRIMANTES MOBILES Zebra xx7</a></li>
              </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">imprimantes badge</a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/imprimante_badge.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>IMPRIMANTES BADGE</h4>
                <ul>
                <li><a>IMPRIMANTES BADGE Zebra xx</a></li>
                <li><a>IMPRIMANTES BADGE Zebra xx2</a></li>
                <li><a>IMPRIMANTES BADGE Zebra xx3</a></li>
                <li><a>IMPRIMANTES BADGE Zebra xx4</a></li>
                <li><a>IMPRIMANTES BADGE Zebra xx5</a></li>
                <li><a>IMPRIMANTES BADGE Zebra xx6</a></li>
                <li><a>IMPRIMANTES BADGE Zebra xx7</a></li>
              </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">imprimante couleur</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/epson.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>IMPRIMANTE COULEUR</h4>
                <ul>
                <li><a>IMPRIMANTE COULEUR Zebra xx</a></li>
                <li><a>IMPRIMANTE COULEUR Zebra xx2</a></li>
                <li><a>IMPRIMANTE COULEUR Zebra xx3</a></li>
                <li><a>IMPRIMANTE COULEUR Zebra xx4</a></li>
                <li><a>IMPRIMANTE COULEUR Zebra xx5</a></li>
                <li><a>IMPRIMANTE COULEUR Zebra xx6</a></li>
                <li><a>IMPRIMANTE COULEUR Zebra xx7</a></li>
              </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a class="propertyType" href="#">accessoires & produits associes</a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/pieces.jpg" alt="" /></a> 
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a class="propertyType" href="#">Reparation et services</a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/reparation.jpg" alt="" /></a>

          </div>
        </div>
      </div>
    </div>
    <!-- end row -->
    <div class="spacer"></div>
  </div>
  <!-- end container --> 
</section>
<!-- end recent properties --> 

<!-- start widgets section -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div class="hbigline1">&nbsp;</div>
    </div>
  </div>
  <?php echo $this->render('statics/carousel.phtml');?>
</section>
