<?php
$menus = Genius_Model_Menu::getAllMenus();
?>
<!-- start subheader -->

<!-- start subheader -->

<section class="subHeader page">
  <div class="container">
    <h1>Imprimante laser</h1>
  </div>
  <!-- end subheader container --> 
</section>
<!-- end subheader section --> 

<!-- start recent properties -->
<section class="properties pad30">
  <div class="container">
    <div class="page_title2">
        <div class="pagenation">&nbsp;<a href="/">Home</a> <i>/</i> <a href="/">Imprimantes Laser</a><i>/</i>HP</div>
    </div>    
    <div class="divider" style="margin-top:0 !important"></div>
    <div class="row three_box">
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">GROUPE DE TRAVAIL</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/groupe-de-travail.png" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>GROUPE DE TRAVAIL</h4>
                                <ul>
                    <li><a>GROUPE DE TRAVAIL HPxx</a></li>
                    <li><a>GROUPE DE TRAVAIL HPxx2</a></li>
                    <li><a>GROUPE DE TRAVAIL HPxx3</a></li>
                    <li><a>GROUPE DE TRAVAIL HPxx4</a></li>
                    <li><a>GROUPE DE TRAVAIL HPxx5</a></li>
                    <li><a>GROUPE DE TRAVAIL HPxx6</a></li>
                    <li><a>GROUPE DE TRAVAIL HPxx7</a></li>
                </ul>           
           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">DÉPARTEMENTAL</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/departemental.gif" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>DÉPARTEMENTAL</h4>
                <ul>
                    <li><a>DÉPARTEMENTAL HPxx</a></li>
                    <li><a>DÉPARTEMENTAL HPxx2</a></li>
                    <li><a>DÉPARTEMENTAL HPxx3</a></li>
                    <li><a>DÉPARTEMENTAL HPxx4</a></li>
                    <li><a>DÉPARTEMENTAL HPxx5</a></li>
                    <li><a>DÉPARTEMENTAL HPxx6</a></li>
                    <li><a>DÉPARTEMENTAL HPxx7</a></li>
                </ul>            
            </div>
          <!--Fin Sous Menu Bloc-->  
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">Grand format / A3</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/170xi3.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>Grand format / A3</h4>
                <ul>
                    <li><a>Grand format HPxx</a></li>
                    <li><a>Grand format HPxx2</a></li>
                    <li><a>Grand format HPxx3</a></li>
                    <li><a>Grand format HPxx4</a></li>
                    <li><a>Grand format HPxx5</a></li>
                    <li><a>Grand format HPxx6</a></li>
                    <li><a>Grand format HPxx7</a></li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> 
          <a class="propertyType" href="#">imprimantes couleur</a> 
          <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/QL420.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>imprimantes couleur</h4>
                <ul>
                    <li><a>imprimantes couleur HPxx</a></li>
                    <li><a>imprimantes couleur HPxx2</a></li>
                    <li><a>imprimantes couleur HPxx3</a></li>
                    <li><a>imprimantes couleur HPxx4</a></li>
                    <li><a>imprimantes couleur HPxx5</a></li>
                    <li><a>imprimantes couleur HPxx6</a></li>
                    <li><a>imprimantes couleur HPxx7</a></li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a class="propertyType" href="#">accessoires & produits associes</a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/pieces.jpg" alt="" /></a>

          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a class="propertyType" href="#">Reparation et services</a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/reparation.jpg" alt="" /></a>
          </div>
        </div>
      </div>
    </div>
    <!-- end row -->
    <div class="spacer"></div>
  </div>
  <!-- end container --> 
</section>
<!-- end recent properties --> 

<!-- start widgets section -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div class="hbigline1">&nbsp;</div>
    </div>
  </div>
  <?php echo $this->render('statics/carousel.phtml');?>
</section>
