<?php
$menus = Genius_Model_Menu::getAllMenus();
?>
<!-- start subheader -->

<!-- start subheader -->

<section class="subHeader page">
  <div class="container">
    <h1>Imprimante laser toutes marques</h1>
  </div>
  <!-- end subheader container --> 
</section>
<!-- end subheader section --> 

<!-- start recent properties -->
<section class="properties pad30">
  <div class="container">
    <div class="page_title2">
        <div class="pagenation">&nbsp;<a href="/">Home</a> <i>/</i> <a href="/">Imprimantes Laser</a><i>/</i>toutes marques</div>
    </div>    
    <div class="divider" style="margin-top:0 !important"></div>
    <div class="row three_box">
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">GROUPE DE TRAVAIL</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/groupe-de-travail.png" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>GROUPE DE TRAVAIL</h4>
                <ul>
                    <li>
                      <a href="#" class="current">Hp</a>
                        <ul>
                            <li><a>Hp xx</a></li>
                            <li><a>Hp xx2</a></li>
                            <li><a>Hp xx3</a></li>
                            <li><a>Hp xx4</a></li>
                            <li><a>Hp xx5</a></li>
                            <li><a>Hp xx6</a></li>
                            <li><a>Hp xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Lexmark</a>
                      <ul>
                            <li><a>Lexmark xx</a></li>
                            <li><a>Lexmark xx2</a></li>
                            <li><a>Lexmark xx3</a></li>
                            <li><a>Lexmark xx4</a></li>
                            <li><a>Lexmark xx5</a></li>
                            <li><a>Lexmark xx6</a></li>
                            <li><a>Lexmark xx7</a></li>
                        </ul>
                    </li>
                    <li>
                        <a>Epson</a>
                        <ul>
                            <li><a>Epson xx</a></li>
                            <li><a>Epson xx2</a></li>
                            <li><a>Epson xx3</a></li>
                            <li><a>Epson xx4</a></li>
                            <li><a>Epson xx5</a></li>
                            <li><a>Epson xx6</a></li>
                            <li><a>Epson xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Autres marques</a>
                      <ul>
                            <li><a>Autres xx</a></li>
                            <li><a>Autres xx2</a></li>
                            <li><a>Autres xx3</a></li>
                            <li><a>Autres xx4</a></li>
                            <li><a>Autres xx5</a></li>
                            <li><a>Autres xx6</a></li>
                            <li><a>Autres xx7</a></li>
                        </ul>
                    </li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">DÉPARTEMENTAL</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/departemental.gif" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>DÉPARTEMENTAL</h4>
                <ul>
                    <li>
                      <a href="#" class="current">Hp</a>
                        <ul>
                            <li><a>Hp xx</a></li>
                            <li><a>Hp xx2</a></li>
                            <li><a>Hp xx3</a></li>
                            <li><a>Hp xx4</a></li>
                            <li><a>Hp xx5</a></li>
                            <li><a>Hp xx6</a></li>
                            <li><a>Hp xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Lexmark</a>
                      <ul>
                            <li><a>Lexmark xx</a></li>
                            <li><a>Lexmark xx2</a></li>
                            <li><a>Lexmark xx3</a></li>
                            <li><a>Lexmark xx4</a></li>
                            <li><a>Lexmark xx5</a></li>
                            <li><a>Lexmark xx6</a></li>
                            <li><a>Lexmark xx7</a></li>
                        </ul>
                    </li>
                    <li>
                        <a>Epson</a>
                        <ul>
                            <li><a>Epson xx</a></li>
                            <li><a>Epson xx2</a></li>
                            <li><a>Epson xx3</a></li>
                            <li><a>Epson xx4</a></li>
                            <li><a>Epson xx5</a></li>
                            <li><a>Epson xx6</a></li>
                            <li><a>Epson xx7</a></li>
                        </ul>
                    </li>
                    
                    <li>
                      <a>Autres marques</a>
                      <ul>
                            <li><a>Autres xx</a></li>
                            <li><a>Autres xx2</a></li>
                            <li><a>Autres xx3</a></li>
                            <li><a>Autres xx4</a></li>
                            <li><a>Autres xx5</a></li>
                            <li><a>Autres xx6</a></li>
                            <li><a>Autres xx7</a></li>
                        </ul>
                    </li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc-->  
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">Grand format / A3</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/170xi3.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>Grand format / A3</h4>
                <ul>
                    <li>
                      <a href="#" class="current">Hp</a>
                        <ul>
                            <li><a>Hp xx</a></li>
                            <li><a>Hp xx2</a></li>
                            <li><a>Hp xx3</a></li>
                            <li><a>Hp xx4</a></li>
                            <li><a>Hp xx5</a></li>
                            <li><a>Hp xx6</a></li>
                            <li><a>Hp xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Lexmark</a>
                      <ul>
                            <li><a>Lexmark xx</a></li>
                            <li><a>Lexmark xx2</a></li>
                            <li><a>Lexmark xx3</a></li>
                            <li><a>Lexmark xx4</a></li>
                            <li><a>Lexmark xx5</a></li>
                            <li><a>Lexmark xx6</a></li>
                            <li><a>Lexmark xx7</a></li>
                        </ul>
                    </li>
                    <li>
                        <a>Epson</a>
                        <ul>
                            <li><a>Epson xx</a></li>
                            <li><a>Epson xx2</a></li>
                            <li><a>Epson xx3</a></li>
                            <li><a>Epson xx4</a></li>
                            <li><a>Epson xx5</a></li>
                            <li><a>Epson xx6</a></li>
                            <li><a>Epson xx7</a></li>
                        </ul>
                    </li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> 
          <a class="propertyType" href="#">imprimantes couleur</a> 
          <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/QL420.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>imprimantes couleur</h4>
                <ul>
                    <li>
                      <a href="#" class="current">Zebra</a>
                        <ul>
                            <li><a>Zebra xx</a></li>
                            <li><a>Zebra xx2</a></li>
                            <li><a>Zebra xx3</a></li>
                            <li><a>Zebra xx4</a></li>
                            <li><a>Zebra xx5</a></li>
                            <li><a>Zebra xx6</a></li>
                            <li><a>Zebra xx7</a></li>
                        </ul>
                    </li>
                    <li>
                      <a>Intermec</a>
                      <ul>
                            <li><a>Intermec xx</a></li>
                            <li><a>Intermec xx2</a></li>
                            <li><a>Intermec xx3</a></li>
                            <li><a>Intermec xx4</a></li>
                            <li><a>Intermec xx5</a></li>
                            <li><a>Intermec xx6</a></li>
                            <li><a>Intermec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                        <a>Tec</a>
                        <ul>
                            <li><a>Tec xx</a></li>
                            <li><a>Tec xx2</a></li>
                            <li><a>Tec xx3</a></li>
                            <li><a>Tec xx4</a></li>
                            <li><a>Tec xx5</a></li>
                            <li><a>Tec xx6</a></li>
                            <li><a>Tec xx7</a></li>
                        </ul>
                    </li>
                    <li>
                     <a>Datamax</a>
                     <ul>
                            <li><a>Datamax xx</a></li>
                            <li><a>Datamax xx2</a></li>
                            <li><a>Datamax xx3</a></li>
                            <li><a>Datamax xx4</a></li>
                            <li><a>Datamax xx5</a></li>
                            <li><a>Datamax xx6</a></li>
                            <li><a>Datamax xx7</a></li>
                        </ul>
                    </li>
                    
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a class="propertyType" href="#">accessoires & produits associes</a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/pieces.jpg" alt="" /></a>

          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a class="propertyType" href="#">Reparation et services</a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/reparation.jpg" alt="" /></a>
          </div>
        </div>
      </div>
    </div>
    <!-- end row -->
    <div class="spacer"></div>
  </div>
  <!-- end container --> 
</section>
<!-- end recent properties --> 

<!-- start widgets section -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div class="hbigline1">&nbsp;</div>
    </div>
  </div>
  <?php echo $this->render('statics/carousel.phtml');?>
</section>
