<?php
$menus = Genius_Model_Menu::getAllMenus();
?>
<!-- start subheader -->

<!-- start subheader -->

<section class="subHeader page">
  <div class="container">
    <h1>Imprimante matricielle</h1>
  </div>
  <!-- end subheader container --> 
</section>
<!-- end subheader section --> 

<!-- start recent properties -->
<section class="properties pad30">
  <div class="container">
    <div class="page_title2">
        <div class="pagenation">&nbsp;<a href="/">Home</a> <i>/</i> <a href="/">Imprimantes matricielle</a><i>/</i>Lexmark</div>
    </div>    
    <div class="divider" style="margin-top:0 !important"></div>
    <div class="row three_box">
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">Imprimante 80 colonnes</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/80_colonne.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>Imprimante 80</h4>
                                <ul>
                    <li><a>Imprimante 80 Lexmark xx</a></li>
                    <li><a>Imprimante 80 Lexmark xx2</a></li>
                    <li><a>Imprimante 80 Lexmark xx3</a></li>
                    <li><a>Imprimante 80 Lexmark xx4</a></li>
                    <li><a>Imprimante 80 Lexmark xx5</a></li>
                    <li><a>Imprimante 80 Lexmark xx6</a></li>
                    <li><a>Imprimante 80 Lexmark xx7</a></li>
                </ul>           
           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">Imprimante 132 colonnes</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/132_colonne.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>Imprimante 132</h4>
                <ul>
                    <li><a>Imprimante 132 Lexmark xx</a></li>
                    <li><a>Imprimante 132 Lexmark xx2</a></li>
                    <li><a>Imprimante 132 Lexmark xx3</a></li>
                    <li><a>Imprimante 132 Lexmark xx4</a></li>
                    <li><a>Imprimante 132 Lexmark xx5</a></li>
                    <li><a>Imprimante 132 Lexmark xx6</a></li>
                    <li><a>Imprimante 132 Lexmark xx7</a></li>
                </ul>            
            </div>
          <!--Fin Sous Menu Bloc-->  
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"> <a class="propertyType" href="#">Imprimante Cabines</a> <a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/Cabine_Nice_Cisco_500.jpg" alt="" /></a>
          <!--Sous Menu Bloc-->
            <div class="box_menu box_menu_left">
             <h4>Imprimante Cabines</h4>
                <ul>
                    <li><a>Imprimante Cabines Lexmark xx</a></li>
                    <li><a>Imprimante Cabines Lexmark xx2</a></li>
                    <li><a>Imprimante Cabines Lexmark xx3</a></li>
                    <li><a>Imprimante Cabines Lexmark xx4</a></li>
                    <li><a>Imprimante Cabines Lexmark xx5</a></li>
                    <li><a>Imprimante Cabines Lexmark xx6</a></li>
                    <li><a>Imprimante Cabines Lexmark xx7</a></li>
                </ul>           
            </div>
          <!--Fin Sous Menu Bloc--> 
          </div>
        </div>
      </div>
      <div class="spacer"></div>
      <div class="col-lg-6 col-md-6 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a class="propertyType" href="#">accessoires & produits associes</a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/pieces.jpg" alt="" /></a>

          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6">
        <div class="propertyItem">
          <div class="propertyContent"><a class="propertyType" href="#">Reparation et services</a><a href="#" class="propertyImgLink"><img class="propertyImg" src="<?php echo THEMES_DEFAULT_URL; ?>images/produit/new/reparation.jpg" alt="" /></a>
          </div>
        </div>
      </div>
    </div>
    <!-- end row -->
    <div class="spacer"></div>
  </div>
  <!-- end container --> 
</section>
<!-- end recent properties --> 

<!-- start widgets section -->
<section class="genericSection2">
  <div class="container">
    <div class="row">
      <div class="hbigline1">&nbsp;</div>
    </div>
  </div>
  <?php echo $this->render('statics/carousel.phtml');?>
</section>
